export type ConnectorStatus = "configured_safe" | "configured_disabled" | "missing_key" | "missing_account" | "missing_env" | "needs_approval" | "blocked" | "future_only" | "legacy_owned" | "duplicate_risk" | "unknown";
export type ConnectorDefinition = { id: string; name: string; purpose: string; envVars: string[]; status: ConnectorStatus; requiredNow: boolean; feature: string; safety: "local" | "read_only" | "approval_gated" | "blocked"; approvalRequired: boolean; inputLocation: string; notes?: string };

const definitions: ConnectorDefinition[] = [
  { id:"supabase", name:"Supabase", purpose:"Nexus authentication and approved storage", envVars:["VITE_SUPABASE_URL","VITE_SUPABASE_ANON_KEY"], status:"configured_disabled", requiredNow:false, feature:"Authenticated Nexus data", safety:"approval_gated", approvalRequired:true, inputLocation:".env.local", notes:"Writes remain gated; Alpha access prohibited." },
  { id:"netlify", name:"Netlify", purpose:"Preview deployment", envVars:["NETLIFY_AUTH_TOKEN","NETLIFY_SITE_ID"], status:"missing_env", requiredNow:false, feature:"Hosted preview", safety:"approval_gated", approvalRequired:true, inputLocation:"local shell or Netlify environment" },
  { id:"github", name:"GitHub", purpose:"Source control and CI", envVars:["GITHUB_TOKEN"], status:"unknown", requiredNow:false, feature:"Remote automation", safety:"approval_gated", approvalRequired:true, inputLocation:"GitHub/gh credential store" },
  { id:"cloudflare", name:"Cloudflare tunnel", purpose:"Secure tunnel", envVars:["CLOUDFLARE_TUNNEL_TOKEN"], status:"missing_env", requiredNow:false, feature:"Remote local access", safety:"approval_gated", approvalRequired:true, inputLocation:"local environment" },
  { id:"resend", name:"Resend", purpose:"Transactional email", envVars:["RESEND_API_KEY"], status:"configured_disabled", requiredNow:false, feature:"Email sending", safety:"blocked", approvalRequired:true, inputLocation:"server-only environment", notes:"Sending prohibited in this sprint." },
  { id:"meta", name:"Meta/Facebook/Instagram", purpose:"Social publishing and insights", envVars:["META_ACCESS_TOKEN","META_PAGE_ID"], status:"configured_disabled", requiredNow:false, feature:"Social workflows", safety:"blocked", approvalRequired:true, inputLocation:"server-only environment" },
  { id:"gsc", name:"Google Search Console", purpose:"SEO query performance", envVars:["GOOGLE_SEARCH_CONSOLE_CREDENTIALS"], status:"missing_key", requiredNow:false, feature:"Measured SEO opportunities", safety:"read_only", approvalRequired:true, inputLocation:"server-only environment" },
  { id:"ga", name:"Google Analytics", purpose:"Site analytics", envVars:["GOOGLE_ANALYTICS_PROPERTY_ID","GOOGLE_APPLICATION_CREDENTIALS"], status:"missing_key", requiredNow:false, feature:"Audience and conversion evidence", safety:"read_only", approvalRequired:true, inputLocation:"server-only environment" },
  { id:"youtube", name:"YouTube API", purpose:"Research metadata", envVars:["YOUTUBE_API_KEY"], status:"unknown", requiredNow:false, feature:"Fresh video metadata", safety:"read_only", approvalRequired:false, inputLocation:".env.local or shell" },
  { id:"notebooklm", name:"NotebookLM export folder", purpose:"Local research imports", envVars:[], status:"configured_safe", requiredNow:true, feature:"Local research memory", safety:"local", approvalRequired:false, inputLocation:"data/exports/notebooklm" },
  { id:"drive", name:"Google Drive/manual export", purpose:"Manual artifact intake", envVars:["GOOGLE_DRIVE_FOLDER_ID"], status:"missing_account", requiredNow:false, feature:"Drive intake", safety:"read_only", approvalRequired:true, inputLocation:"server-only environment" },
  { id:"oanda", name:"Oanda practice", purpose:"Demo account read checks", envVars:["OANDA_API_TOKEN","OANDA_ACCOUNT_ID","OANDA_ENVIRONMENT"], status:"configured_disabled", requiredNow:false, feature:"Practice/demo verification", safety:"approval_gated", approvalRequired:true, inputLocation:"server-only environment", notes:"No orders; funded/live is blocked." },
  { id:"ollama_local", name:"Ollama local", purpose:"Local model inference", envVars:["OLLAMA_BASE_URL"], status:"unknown", requiredNow:false, feature:"Private local Hermes inference", safety:"local", approvalRequired:false, inputLocation:"local environment" },
  { id:"ollama_cloud", name:"Ollama cloud/Pro", purpose:"Hosted model inference", envVars:["OLLAMA_API_KEY"], status:"missing_key", requiredNow:false, feature:"Hosted Alpha inference", safety:"approval_gated", approvalRequired:true, inputLocation:"server-only environment" },
  { id:"openrouter", name:"OpenRouter", purpose:"Alpha model routing", envVars:["OPENROUTER_API_KEY"], status:"missing_key", requiredNow:false, feature:"Hosted model selection", safety:"approval_gated", approvalRequired:true, inputLocation:"server-only environment" },
  { id:"groq", name:"Groq", purpose:"Fast hosted inference", envVars:["GROQ_API_KEY"], status:"missing_key", requiredNow:false, feature:"Fast model inference", safety:"approval_gated", approvalRequired:true, inputLocation:"server-only environment" },
  { id:"stripe", name:"Stripe test mode", purpose:"Payment-flow testing", envVars:["STRIPE_SECRET_KEY","VITE_STRIPE_PUBLISHABLE_KEY"], status:"configured_disabled", requiredNow:false, feature:"Test checkout", safety:"approval_gated", approvalRequired:true, inputLocation:"server-only and frontend environment", notes:"Charges remain blocked." },
  { id:"firecrawl", name:"Firecrawl", purpose:"Future web research", envVars:["FIRECRAWL_API_KEY"], status:"future_only", requiredNow:false, feature:"Web extraction", safety:"approval_gated", approvalRequired:true, inputLocation:"server-only environment" },
  { id:"n8n", name:"n8n", purpose:"Future workflow orchestration", envVars:["N8N_API_KEY","N8N_BASE_URL"], status:"future_only", requiredNow:false, feature:"External workflow automation", safety:"blocked", approvalRequired:true, inputLocation:"server-only environment" },
  { id:"postiz_mixpost", name:"Postiz/Mixpost", purpose:"Future social scheduling", envVars:["SOCIAL_SCHEDULER_API_KEY"], status:"future_only", requiredNow:false, feature:"Social scheduling", safety:"blocked", approvalRequired:true, inputLocation:"server-only environment" },
];

export const affiliatePlaceholders = ["credit_monitoring","online_mailing","business_bank_account","business_setup_llc","funding_marketplace","newsletter_platform","seo_content_tools","ai_tools","trading_education_tools","tax_bookkeeping_future"].map(id => ({ id, value:"", status:"missing_account" as const, approvalRequired:true }));
export function getConnectorRegistry() { return definitions.map(item => ({...item, envPresent:item.envVars.map(name => ({name, present:false}))})); }
export function connectorSafetyInvariants() { return { secretsExposed:false, alphaSupabase:false, externalActionsEnabled:false, liveTradingEnabled:false }; }
