import type { ParsedCreditAccount, ParsedInquiry, ParsedPersonalInfoVariation, CreditReportConfidence } from './creditReportParserTypes'

export type BureauName = 'experian' | 'equifax' | 'transunion' | 'other'
export type DiscrepancyType = 'balance_mismatch'|'credit_limit_mismatch'|'high_limit_mismatch'|'past_due_mismatch'|'date_opened_mismatch'|'last_reported_date_mismatch'|'account_status_mismatch'|'payment_status_mismatch'|'account_number_fragment_mismatch'|'ownership_mismatch'|'creditor_name_mismatch'|'collection_status_mismatch'|'charge_off_status_mismatch'|'duplicate_possible'|'bureau_omission'|'inconsistent_remarks'|'personal_information_mismatch'|'inquiry_mismatch'

export interface CanonicalBureauRecord { bureau:BureauName; balance:number|null; creditLimit:number|null; highLimit:number|null; pastDue:number|null; dateOpened:string|null; lastReportedDate:string|null; accountStatus:string|null; paymentStatus:string|null; accountNumberMasked:string|null; ownership:string|null; remarks:string|null; rawFieldConfidence:CreditReportConfidence }
export interface CanonicalAccount { canonicalAccountId:string; furnisher:string; originalCreditor:string|null; maskedAccountReference:string; accountType:string; bureauRecords:CanonicalBureauRecord[]; matchConfidence:CreditReportConfidence; matchReasons:string[]; unmatchedWarnings:string[]; sourceParserResultId:string; sourceDocumentId:string }
export interface BureauDiscrepancy { discrepancyId:string; canonicalAccountId:string; discrepancyType:DiscrepancyType; comparedFields:string[]; bureauValues:Record<string,unknown>; differenceSummary:string; exactDifference:number|null; confidence:CreditReportConfidence; severity:'high'|'medium'|'low'; fundingImpact:string; tier1Impact:'high'|'medium'|'low'; tier2Impact:'high'|'medium'|'low'; possibleStrategyCategories:string[]; clientConfirmationRequired:boolean; specialistExceptionRequired:boolean; supportingParserFields:string[] }

const bureau=(v:unknown):BureauName=>{const x=String(v||'').toLowerCase().replace(/[^a-z]/g,''); return x.includes('experian')?'experian':x.includes('equifax')?'equifax':x.includes('transunion')?'transunion':'other'}
const name=(v:unknown)=>String(v||'').toLowerCase().replace(/\b(inc|llc|corp|corporation|company|co)\b/g,'').replace(/[^a-z0-9]/g,'')
const mask=(v:unknown)=>{const s=String(v||'').replace(/[^a-zA-Z0-9]/g,''); return s.slice(-4).toLowerCase()}
const money=(v:unknown)=>{if(v===null||v===undefined||v==='')return null; const n=Number(String(v).replace(/[^0-9.-]/g,'')); return Number.isFinite(n)?n:null}
const date=(v:unknown)=>{if(!v)return null; const d=new Date(String(v)); return Number.isNaN(d.valueOf())?String(v).trim().toLowerCase():d.toISOString().slice(0,10)}
const field=(a:ParsedCreditAccount,...keys:string[])=>{const row=a as unknown as Record<string,unknown>; return keys.map(k=>row[k]).find(v=>v!==undefined&&v!==null&&v!=='')}
const id=(prefix:string,value:string)=>`${prefix}_${value.replace(/[^a-z0-9]/gi,'_').slice(0,64)}`

function record(a:ParsedCreditAccount):CanonicalBureauRecord{return {bureau:bureau(a.bureau),balance:money(field(a,'reportedBalance','balance')),creditLimit:money(field(a,'creditLimit')),highLimit:money(field(a,'highLimit','originalBalance')),pastDue:money(field(a,'pastDue','pastDueAmount')),dateOpened:date(a.dateOpened),lastReportedDate:date(field(a,'dateReported','lastReportedDate')),accountStatus:String(a.status||'')||null,paymentStatus:String(a.paymentStatus||'')||null,accountNumberMasked:String(a.accountNumberMasked||'')||null,ownership:String(field(a,'ownership','responsibility')||'')||null,remarks:String(a.notes||'')||null,rawFieldConfidence:a.confidence||'low'}}

export function normalizeCrossBureauAccounts(accounts:ParsedCreditAccount[],sourceParserResultId='',sourceDocumentId=''):CanonicalAccount[]{
  const groups:CanonicalAccount[]=[]
  accounts.forEach((a,index)=>{const furnisher=a.furnisherName||a.accountName||'Unknown furnisher'; const suffix=mask(a.accountNumberMasked); const normalized=name(furnisher); const opened=date(a.dateOpened); const candidate=groups.find(g=>{const existingSuffix=mask(g.maskedAccountReference); const sameName=name(g.furnisher)===normalized&&normalized.length>=4; const sameSuffix=suffix&&existingSuffix===suffix; const sameType=g.accountType===a.itemType; const sameDate=opened&&g.bureauRecords.some(r=>r.dateOpened===opened); if(suffix&&existingSuffix&&!sameSuffix)return false; return Boolean(sameSuffix&&(sameName||sameType)||(sameName&&sameType&&sameDate))})
    if(candidate){candidate.bureauRecords.push(record(a)); candidate.matchReasons.push(suffix?'masked suffix plus supporting field':'furnisher, type, and opened date'); candidate.matchConfidence=suffix?'high':'medium'}
    else groups.push({canonicalAccountId:id('acct',`${normalized||'unknown'}_${suffix||index}`),furnisher,originalCreditor:String(field(a,'originalCreditor')||'')||null,maskedAccountReference:a.accountNumberMasked||'Not available',accountType:a.itemType||'other',bureauRecords:[record(a)],matchConfidence:'low',matchReasons:['single parsed record; not merged by name alone'],unmatchedWarnings:[],sourceParserResultId,sourceDocumentId})
  })
  groups.forEach(g=>{const seen=new Set(g.bureauRecords.map(r=>r.bureau)); if(seen.size<3)g.unmatchedWarnings.push(`Missing ${(['experian','equifax','transunion'] as BureauName[]).filter(b=>!seen.has(b)).join(', ')} record; omission is not a confirmed error.`)})
  return groups
}

const strategy:Record<string,string[]>={balance_mismatch:['cross_bureau_balance_review','inaccurate_balance_documentation'],date_opened_mismatch:['cross_bureau_date_review'],last_reported_date_mismatch:['cross_bureau_date_review'],account_status_mismatch:['cross_bureau_status_review'],payment_status_mismatch:['incorrect_payment_status_review'],credit_limit_mismatch:['incorrect_limit_review'],high_limit_mismatch:['incorrect_limit_review'],past_due_mismatch:['cross_bureau_balance_review'],account_number_fragment_mismatch:['account_number_review'],ownership_mismatch:['account_ownership_review','purchased_debt_documentation'],bureau_omission:['bureau_omission_review'],duplicate_possible:['duplicate_account_review']}
const labels:Record<string,string>={balance:'balance',creditLimit:'credit limit',highLimit:'high limit',pastDue:'past-due amount',dateOpened:'date opened',lastReportedDate:'last-reported date',accountStatus:'account status',paymentStatus:'payment status',accountNumberMasked:'masked account fragment',ownership:'ownership'}

export function compareCanonicalAccountAcrossBureaus(account:CanonicalAccount):BureauDiscrepancy[]{
  const out:BureauDiscrepancy[]=[]; const fields:[keyof CanonicalBureauRecord,DiscrepancyType][]=[['balance','balance_mismatch'],['creditLimit','credit_limit_mismatch'],['highLimit','high_limit_mismatch'],['pastDue','past_due_mismatch'],['dateOpened','date_opened_mismatch'],['lastReportedDate','last_reported_date_mismatch'],['accountStatus','account_status_mismatch'],['paymentStatus','payment_status_mismatch'],['accountNumberMasked','account_number_fragment_mismatch'],['ownership','ownership_mismatch']]
  for(const [key,type] of fields){const rows=account.bureauRecords.filter(r=>r[key]!==null&&r[key]!==''); const vals=[...new Set(rows.map(r=>String(r[key]).toLowerCase()))]; if(rows.length>=2&&vals.length>1){const bureauValues=Object.fromEntries(rows.map(r=>[r.bureau,r[key]])); const nums=rows.map(r=>typeof r[key]==='number'?r[key] as number:null).filter((v):v is number=>v!==null); const diff=nums.length>1?Math.max(...nums)-Math.min(...nums):null; const summary=diff!==null?`${labels[key]} differs by ${new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(diff)} across reporting bureaus.`:`${labels[key]} differs across reporting bureaus.`; out.push({discrepancyId:id('disc',`${account.canonicalAccountId}_${type}`),canonicalAccountId:account.canonicalAccountId,discrepancyType:type,comparedFields:[String(key)],bureauValues,differenceSummary:summary,exactDifference:diff,confidence:rows.every(r=>r.rawFieldConfidence==='high')?'high':'medium',severity:['balance_mismatch','past_due_mismatch','account_status_mismatch'].includes(type)?'high':'medium',fundingImpact:'Inconsistent reporting may affect Credit Profile interpretation and funding readiness.',tier1Impact:'medium',tier2Impact:'medium',possibleStrategyCategories:strategy[type]||['report_item_review'],clientConfirmationRequired:false,specialistExceptionRequired:account.matchConfidence==='low',supportingParserFields:[String(key),'bureau']})}}
  const present=new Set(account.bureauRecords.map(r=>r.bureau)); const missing=(['experian','equifax','transunion'] as BureauName[]).filter(b=>!present.has(b)); if(account.bureauRecords.length>=2&&missing.length)out.push({discrepancyId:id('disc',`${account.canonicalAccountId}_omission`),canonicalAccountId:account.canonicalAccountId,discrepancyType:'bureau_omission',comparedFields:['bureau'],bureauValues:Object.fromEntries([...present].map(b=>[b,'reported'])),differenceSummary:`No matching record was parsed for ${missing.join(', ')}; this is an omission for review, not a confirmed reporting error.`,exactDifference:null,confidence:account.matchConfidence,severity:'low',fundingImpact:'Different bureau coverage may change lender-visible profile information.',tier1Impact:'low',tier2Impact:'low',possibleStrategyCategories:['bureau_omission_review'],clientConfirmationRequired:false,specialistExceptionRequired:account.matchConfidence==='low',supportingParserFields:['bureau']})
  return out
}

export function compareCreditReportAcrossBureaus(input:{accounts:ParsedCreditAccount[];inquiries?:ParsedInquiry[];personalInfoVariations?:ParsedPersonalInfoVariation[];parserResultId?:string;documentId?:string}){
  const canonicalAccounts=normalizeCrossBureauAccounts(input.accounts,input.parserResultId,input.documentId)
  const accountDiscrepancies=canonicalAccounts.flatMap(compareCanonicalAccountAcrossBureaus)
  const duplicateDiscrepancies:BureauDiscrepancy[]=[]
  canonicalAccounts.forEach((a,i)=>canonicalAccounts.slice(i+1).forEach(b=>{
    const ar=a.bureauRecords[0], br=b.bureauRecords[0]
    if(name(a.furnisher)===name(b.furnisher)&&a.accountType===b.accountType&&ar.dateOpened&&ar.dateOpened===br.dateOpened&&ar.balance!==null&&ar.balance===br.balance){
      duplicateDiscrepancies.push({discrepancyId:id('disc',`${a.canonicalAccountId}_${b.canonicalAccountId}_duplicate`),canonicalAccountId:a.canonicalAccountId,discrepancyType:'duplicate_possible',comparedFields:['furnisher','accountType','dateOpened','balance'],bureauValues:{first:a.maskedAccountReference,second:b.maskedAccountReference},differenceSummary:'Two separately grouped records share furnisher, type, opened date, and balance; duplicate review may be appropriate.',exactDifference:null,confidence:'medium',severity:'medium',fundingImpact:'Possible duplicate reporting may overstate obligations.',tier1Impact:'medium',tier2Impact:'medium',possibleStrategyCategories:['duplicate_account_review'],clientConfirmationRequired:true,specialistExceptionRequired:false,supportingParserFields:['furnisherName','itemType','dateOpened','reportedBalance']})
    }
  }))
  const inquiryGroups=new Map<string,ParsedInquiry[]>()
  ;(input.inquiries||[]).forEach(q=>{const k=`${name(q.company)}_${date(q.date)}`; inquiryGroups.set(k,[...(inquiryGroups.get(k)||[]),q])})
  const inquiryDiscrepancies:BureauDiscrepancy[]=[]
  inquiryGroups.forEach((rows,k)=>{
    const seen=new Set(rows.map(q=>bureau(q.bureau)))
    if(rows.length>=2&&seen.size<3){
      inquiryDiscrepancies.push({discrepancyId:id('inq',k),canonicalAccountId:'inquiries',discrepancyType:'inquiry_mismatch',comparedFields:['company','date','bureau'],bureauValues:Object.fromEntries(rows.map(q=>[bureau(q.bureau),q.date||'reported'])),differenceSummary:`${rows[0].company} inquiry reporting differs by bureau; authorization still requires client confirmation.`,exactDifference:null,confidence:rows.every(q=>q.confidence==='high')?'high':'medium',severity:'low',fundingImpact:'Recent inquiry reporting may affect some funding evaluations.',tier1Impact:'medium',tier2Impact:'low',possibleStrategyCategories:['unauthorized_inquiry'],clientConfirmationRequired:true,specialistExceptionRequired:false,supportingParserFields:['company','date','bureau']})
    }
  })
  const personalDiscrepancies=(input.personalInfoVariations||[]).map((v,i):BureauDiscrepancy=>({discrepancyId:`personal_${i}`,canonicalAccountId:'personal_information',discrepancyType:'personal_information_mismatch',comparedFields:[v.field],bureauValues:{[bureau(v.bureau)]:v.value},differenceSummary:`A ${v.field} variation was parsed for review; Nexus has not verified it as inaccurate.`,exactDifference:null,confidence:v.confidence,severity:'low',fundingImpact:'Identity inconsistencies can delay documentation review.',tier1Impact:'low',tier2Impact:'low',possibleStrategyCategories:['personal_information_correction'],clientConfirmationRequired:true,specialistExceptionRequired:v.confidence==='low',supportingParserFields:[v.field,'bureau']}))
  return {canonicalAccounts,discrepancies:[...accountDiscrepancies,...duplicateDiscrepancies,...inquiryDiscrepancies,...personalDiscrepancies]}
}
