/** Canonical customer-plan contracts. Unknown evidence is never promoted to verified. */
export type EvidenceStatus = 'SUPPORTED' | 'PARTIAL' | 'MISSING' | 'UNVERIFIED' | 'NOT_APPLICABLE'
export type GoalStatus = 'NOT_STARTED' | 'IN_PROGRESS' | 'BLOCKED' | 'READY_FOR_REVIEW' | 'COMPLETE'
export type GoalEvidence = { status: EvidenceStatus; source: string; evidenceId?: string; provenance?: string; lastVerifiedAt?: string; confidence: 'HIGH' | 'MEDIUM' | 'LOW' | 'NONE' }
export type CustomerMilestone = { milestoneId: string; title: string; status: GoalStatus; targetDate?: string; completionState: 'COMPLETE' | 'OPEN' | 'BLOCKED' | 'UNKNOWN'; evidence: GoalEvidence; dependencies: string[]; nextAction: string }
export type CustomerGoal = { goalId: string; customerOrClientId: string; goalType: string; title: string; description: string; targetOutcome: string; targetAmount?: number; targetDate?: string; priority: number; currentStatus: GoalStatus; currentProgress: number | null; milestones: CustomerMilestone[]; dependencies: string[]; blockers: string[]; evidenceRequirements: string[]; relatedFundingObjective?: string; relatedBusinessPlan?: string; evidence: GoalEvidence; createdAt: string; updatedAt: string }
export type UseOfFundsItem = { useOfFundsId: string; category: string; description: string; requestedAmount?: number; allocationPercent?: number; businessPurpose: string; relatedGoal: string; relatedMilestone?: string; supportingEvidence: GoalEvidence; evidenceStatus: EvidenceStatus; confidence: GoalEvidence['confidence']; knownGaps: string[] }
export function evidence(source: string, status: EvidenceStatus, evidenceId?: string): GoalEvidence { return { source, status, evidenceId, provenance: source, confidence: status === 'SUPPORTED' ? 'HIGH' : status === 'PARTIAL' ? 'MEDIUM' : 'NONE' } }
export function buildBusinessPlanContext(goal: CustomerGoal, useOfFunds: UseOfFundsItem[]) { return { goal: { id: goal.goalId, title: goal.title, status: goal.currentStatus, progress: goal.currentProgress }, milestones: goal.milestones.map((m) => ({ id: m.milestoneId, title: m.title, status: m.status, nextAction: m.nextAction })), useOfFunds: useOfFunds.filter((i) => i.relatedGoal === goal.goalId).map((i) => ({ category: i.category, amount: i.requestedAmount, evidenceStatus: i.evidenceStatus, knownGaps: i.knownGaps })), blockers: goal.blockers, evidence: goal.evidence, recommendedNextAction: goal.milestones.find((m) => m.completionState !== 'COMPLETE')?.nextAction || 'Review the completed plan.' } }
export function readinessFromEvidence(goal: CustomerGoal, funds: UseOfFundsItem[]) { const linked = funds.filter((i) => i.relatedGoal === goal.goalId); const unsupported = linked.filter((i) => i.evidenceStatus !== 'SUPPORTED'); return { status: goal.evidence.status === 'SUPPORTED' && unsupported.length === 0 ? 'SUPPORTED' : 'UNVERIFIED', missingItems: [...goal.evidenceRequirements.filter((r) => goal.blockers.includes(r)), ...unsupported.flatMap((i) => i.knownGaps)], unsupportedPositiveClaims: unsupported.length } as const }
