/** Bounded Funding workflow contract: package preparation is allowed; submission is not. */
export type FundingEvidence = { source: string; evidenceId?: string; status: 'SUPPORTED' | 'PARTIAL' | 'MISSING' | 'UNVERIFIED'; confidence: 'HIGH' | 'MEDIUM' | 'LOW' | 'NONE'; lastVerifiedAt?: string }
export type FundingDocument = { documentType: string; requiredFor: string; status: 'PRESENT' | 'MISSING' | 'STALE' | 'INVALID' | 'UNVERIFIED'; source: string; artifactId?: string; missingReason?: string; nextAction: string; evidence: FundingEvidence }
export type FundingOffer = { offerType: string; readinessState: string; eligibilityReason: string; source: string; amountRange?: string; termsIfKnown?: string; requiredDocuments: string[]; limitations: string[]; confidence: FundingEvidence['confidence']; evidenceLinks: FundingEvidence[]; status: 'SUPPORTED' | 'CONDITIONAL' | 'UNSUPPORTED' }
export type FundingWorkflowInput = { clientOrBusinessId: string; fundingGoal: string; requestedAmount?: number; useOfFunds: string[]; entityReadiness: string; creditReadiness: string; businessCreditReadiness: string; documents: FundingDocument[]; blockers: string[]; riskFlags: string[]; knownGaps: string[]; confidence: FundingEvidence['confidence']; nextAction: string; currentStage: string }
export function traceOffer(offer: FundingOffer) { return { ...offer, unsupportedPromotion: offer.status === 'UNSUPPORTED' || offer.confidence === 'NONE' } }
export function buildPreSubmissionPackage(input: FundingWorkflowInput, offer: FundingOffer) { const missing = input.documents.filter((d) => d.status !== 'PRESENT'); return { applicationTarget: 'GOVERNED_FUNDING_REVIEW', offerSelected: traceOffer(offer), readinessState: { entity: input.entityReadiness, credit: input.creditReadiness, businessCredit: input.businessCreditReadiness }, documentPackage: input.documents, useOfFunds: input.useOfFunds, blockers: input.blockers, riskFlags: input.riskFlags, knownUncertainties: input.knownGaps, preSubmissionValidation: missing.length === 0 && input.blockers.length === 0 ? 'READY_FOR_APPROVAL_REVIEW' : 'BLOCKED_BY_MISSING_INPUT', approvalRequired: true, externalSubmissionPerformed: false }
}
export function fundingGateDecision(input: FundingWorkflowInput) { return { allowed: false, outcome: 'POLICY_REQUIRE_HUMAN', reason: input.blockers.length || input.documents.some((d) => d.status !== 'PRESENT') ? 'Missing or incomplete evidence' : 'Application submission requires explicit approval', externalSubmissionPerformed: false } as const }
