import type { HermesUiActionType } from './hermesUiActions';

export type HermesAccessStatus = 'connected' | 'partial' | 'blocked' | 'not_configured' | 'approval_gated' | 'unknown';
export type HermesExecutionRisk = 'none' | 'low' | 'medium' | 'high' | 'prohibited';

export interface HermesCapabilityArea {
  areaKey: string; displayName: string;
  canRead: boolean; canSummarize: boolean; canOpen: boolean; canDraft: boolean; canExecute: boolean;
  executionRisk: HermesExecutionRisk; approvalRequired: boolean;
  sourceAdapter: string; sourceTables?: string[]; reportPaths?: string[];
  uiRoute?: string; actionType?: HermesUiActionType;
  status: HermesAccessStatus; blocker?: string; nextSafeAction: string;
}

export const hermesCapabilityRegistry: HermesCapabilityArea[] = [
  { areaKey: 'approvals', displayName: 'Approvals / Ray Review', canRead: true, canSummarize: true, canOpen: true, canDraft: true, canExecute: false, executionRisk: 'high', approvalRequired: true, sourceAdapter: 'Supabase read + local Ray Review snapshot', sourceTables: ['task_requests', 'approvals'], uiRoute: '#rayreview', actionType: 'open_approval', status: 'connected', nextSafeAction: 'Open Ray Review and inspect pending items.' },
  { areaKey: 'reports', displayName: 'Reports', canRead: true, canSummarize: true, canOpen: true, canDraft: false, canExecute: false, executionRisk: 'none', approvalRequired: false, sourceAdapter: 'local report registry', reportPaths: ['reports/manual_publish'], uiRoute: '#reports', actionType: 'open_report', status: 'connected', nextSafeAction: 'Open the report library.' },
  { areaKey: 'clients', displayName: 'Clients', canRead: true, canSummarize: true, canOpen: true, canDraft: false, canExecute: false, executionRisk: 'high', approvalRequired: false, sourceAdapter: 'Supabase client adapter', sourceTables: ['client_profiles'], uiRoute: '#clients', status: 'blocked', blocker: 'Authenticated client_profiles access must be verified; production reported access denied.', nextSafeAction: 'Retry a read-only client_profiles query with the approved admin session.' },
  { areaKey: 'opportunities', displayName: 'Business Opportunities', canRead: true, canSummarize: true, canOpen: true, canDraft: true, canExecute: false, executionRisk: 'medium', approvalRequired: true, sourceAdapter: 'Supabase + static opportunity context', sourceTables: ['business_opportunities', 'monetization_opportunities'], uiRoute: '#opportunity', status: 'partial', blocker: 'Live and static items require item-level provenance.', nextSafeAction: 'Open opportunities and verify the selected item against its live row.' },
  { areaKey: 'system_health', displayName: 'System Health', canRead: true, canSummarize: true, canOpen: true, canDraft: false, canExecute: false, executionRisk: 'none', approvalRequired: false, sourceAdapter: 'system health registry + reports', reportPaths: ['reports/manual_publish'], uiRoute: '#system', actionType: 'view_source', status: 'partial', blocker: 'Local report evidence is not a fresh production probe.', nextSafeAction: 'Run authenticated read-only Supabase and deployment verification.' },
  { areaKey: 'research_money', displayName: 'Research to Money Pipeline', canRead: true, canSummarize: true, canOpen: true, canDraft: true, canExecute: false, executionRisk: 'medium', approvalRequired: true, sourceAdapter: 'research reports + Supabase', sourceTables: ['research_sources', 'research_runs'], uiRoute: '#research', status: 'partial', blocker: 'Current scheduler and connector state require live verification.', nextSafeAction: 'Open research and compare the newest run with its report.' },
  { areaKey: 'creative', displayName: 'Creative Studio', canRead: true, canSummarize: true, canOpen: true, canDraft: true, canExecute: false, executionRisk: 'medium', approvalRequired: true, sourceAdapter: 'page context + local modules', uiRoute: '#creative', status: 'partial', blocker: 'No dedicated Hermes source adapter.', nextSafeAction: 'Add a read-only Creative Studio inventory adapter.' },
  { areaKey: 'revenue', displayName: 'Monetization / Revenue Dashboard', canRead: true, canSummarize: true, canOpen: true, canDraft: true, canExecute: false, executionRisk: 'high', approvalRequired: true, sourceAdapter: 'revenue reports + opportunity context', uiRoute: '#monetization', status: 'partial', blocker: 'Confirmed live revenue requires authenticated payment verification.', nextSafeAction: 'Open Revenue Dashboard and verify payment evidence read-only.' },
  { areaKey: 'advisor_inbox', displayName: 'Hermes Advisor Inbox', canRead: true, canSummarize: true, canOpen: true, canDraft: true, canExecute: false, executionRisk: 'low', approvalRequired: false, sourceAdapter: 'advisor inbox report', reportPaths: ['reports/manual_publish/hermes_advisor_inbox_latest.md'], uiRoute: '#hermes', status: 'connected', nextSafeAction: 'Open Hermes Workroom.' },
  { areaKey: 'scheduler', displayName: 'Scheduler / Automation', canRead: true, canSummarize: true, canOpen: true, canDraft: true, canExecute: false, executionRisk: 'high', approvalRequired: true, sourceAdapter: 'scheduler reports', uiRoute: '#automation', status: 'approval_gated', blocker: 'Creating or activating schedules requires explicit approval.', nextSafeAction: 'Prepare a draft schedule for Ray Review.' },
  { areaKey: 'youtube', displayName: 'YouTube Research', canRead: true, canSummarize: true, canOpen: true, canDraft: true, canExecute: false, executionRisk: 'medium', approvalRequired: true, sourceAdapter: 'research reports + approved transcript files', uiRoute: '#research', status: 'partial', blocker: 'Some transcript/source files are not configured or verified.', nextSafeAction: 'Open Research and verify approved transcript availability.' },
  { areaKey: 'credit_funding', displayName: 'Credit & Funding Readiness', canRead: true, canSummarize: true, canOpen: true, canDraft: true, canExecute: false, executionRisk: 'high', approvalRequired: true, sourceAdapter: 'opportunity and client context', uiRoute: '#opportunity', status: 'partial', blocker: 'Client evidence is blocked until client_profiles access succeeds.', nextSafeAction: 'Use non-client offer context or restore approved client read access.' },
  { areaKey: 'specialists', displayName: 'Specialist Agents', canRead: true, canSummarize: true, canOpen: true, canDraft: true, canExecute: false, executionRisk: 'medium', approvalRequired: true, sourceAdapter: 'specialist registry', uiRoute: '#hermes', actionType: 'prepare_specialist_handoff', status: 'partial', blocker: 'No verified live specialist agents are registered.', nextSafeAction: 'Prepare a draft specialist definition for Ray Review.' },
  { areaKey: 'page_context', displayName: 'Page Context / UI Context', canRead: true, canSummarize: true, canOpen: false, canDraft: false, canExecute: false, executionRisk: 'none', approvalRequired: false, sourceAdapter: 'current page metadata', status: 'connected', nextSafeAction: 'Keep page metadata distinct from verified live data.' },
  { areaKey: 'trading', displayName: 'Trading / Oanda / Vibe', canRead: true, canSummarize: true, canOpen: true, canDraft: false, canExecute: false, executionRisk: 'prohibited', approvalRequired: true, sourceAdapter: 'trading proof reports', uiRoute: '#trading', status: 'blocked', blocker: 'Live/funded trading is disabled; Oanda practice verification is incomplete.', nextSafeAction: 'Use paper/practice evidence only.' },
  { areaKey: 'email', displayName: 'Email / Resend', canRead: true, canSummarize: true, canOpen: false, canDraft: true, canExecute: false, executionRisk: 'high', approvalRequired: true, sourceAdapter: 'communication reports', status: 'not_configured', blocker: 'Verified sender/key configuration is incomplete.', nextSafeAction: 'Fix configuration, then prepare a test-send approval.' },
  { areaKey: 'stripe', displayName: 'Stripe / Checkout', canRead: true, canSummarize: true, canOpen: false, canDraft: true, canExecute: false, executionRisk: 'high', approvalRequired: true, sourceAdapter: 'payment reports', status: 'approval_gated', blocker: 'Checkout/payment confirmation requires explicit approval and test-mode proof.', nextSafeAction: 'Open Ray Review for the test payment decision.' },
  { areaKey: 'supabase', displayName: 'Supabase', canRead: true, canSummarize: true, canOpen: false, canDraft: false, canExecute: false, executionRisk: 'high', approvalRequired: false, sourceAdapter: 'authenticated read adapters', status: 'partial', blocker: 'Access varies by table and authenticated session.', nextSafeAction: 'Run table-specific read-only verification.' },
  { areaKey: 'deployment', displayName: 'Netlify / Deployment', canRead: false, canSummarize: true, canOpen: false, canDraft: false, canExecute: false, executionRisk: 'high', approvalRequired: true, sourceAdapter: 'local deployment reports', status: 'unknown', blocker: 'No authenticated live deployment adapter in Hermes chat.', nextSafeAction: 'Verify the deployed commit read-only in Netlify.' },
  { areaKey: 'knowledge', displayName: 'Knowledge Base / Memory', canRead: true, canSummarize: true, canOpen: false, canDraft: true, canExecute: false, executionRisk: 'medium', approvalRequired: true, sourceAdapter: 'scoped conversation and local context stores', status: 'partial', blocker: 'Durable writes and source freshness are separately governed.', nextSafeAction: 'Use scoped memory and request audit details for provenance.' },
];

export function renderHermesAccessMapCeo(): string {
  return 'Hermes is connected to reports, approvals, system health, page context, the specialist inventory, and business opportunities. Clients are blocked until the client_profiles read succeeds, while YouTube, Stripe, Resend, deployment, and several live workflows still need verification or approval. The next move is to open the access map and repair blocked sources one by one.';
}
