/**
 * Nexus OS v2 — Process Registry
 * Prompt 2: Phase C
 *
 * Central registry of all Nexus processes with their status, mode, and metadata.
 * This is the single source of truth for what processes exist and how they run.
 */

import { ActivationMode } from './nexusActivationModes';

export type ProcessStatus = 'idle' | 'ready' | 'running' | 'completed' | 'failed' | 'interrupted' | 'blocked';

export interface ProcessDefinition {
  process_id: string;
  department: string;
  name: string;
  description: string;
  activation_mode: ActivationMode;
  file_or_command: string;
  input_source: string;
  output_files: string[];
  supabase_tables: string[];
  ui_visibility: string;
  alpha_visibility: string;
  nexus_hermes_visibility: string;
  external_action: boolean;
  ray_review_required: boolean;
  score: number;
  next_action: string;
  recovery_prompt: string;
}

export const NEXUS_PROCESS_REGISTRY: ProcessDefinition[] = [
  {
    process_id: 'got_funding_lead_capture',
    department: 'marketing',
    name: 'Got Funding Lead Capture',
    description: 'Netlify form submission for Got Funding landing page',
    activation_mode: 'APPROVED_LIVE',
    file_or_command: 'netlify_functions/alpha-search.mjs',
    input_source: 'got_funding_form',
    output_files: ['netlify_submissions'],
    supabase_tables: [],
    ui_visibility: 'command_center',
    alpha_visibility: 'full',
    nexus_hermes_visibility: 'full',
    external_action: false,
    ray_review_required: false,
    score: 85,
    next_action: 'monitor_form_submissions',
    recovery_prompt: 'Check Netlify form submission status for Got Funding',
  },
  {
    process_id: 'supabase_live_verification',
    department: 'system_health',
    name: 'Supabase Live Verification',
    description: 'Verify Supabase connectivity, tables, and RLS',
    activation_mode: 'SANDBOX_TEST',
    file_or_command: 'scripts/verify_nexus_supabase_live_status.py',
    input_source: 'env_keys',
    output_files: ['reports/runtime/nexus_live_source_status.json'],
    supabase_tables: ['admin_users', 'approvals', 'task_requests', 'nexus_events', 'system_health', 'agent_jobs'],
    ui_visibility: 'system_health',
    alpha_visibility: 'status',
    nexus_hermes_visibility: 'status',
    external_action: false,
    ray_review_required: false,
    score: 60,
    next_action: 'run_verification_script',
    recovery_prompt: 'Re-run Supabase verification: python3 scripts/verify_nexus_supabase_live_status.py',
  },
  {
    process_id: 'system_health_check',
    department: 'system_health',
    name: 'System Health Check',
    description: 'Run system health checks across all connectors and services',
    activation_mode: 'OBSERVE',
    file_or_command: 'src/lib/systemHealthAdapter.ts',
    input_source: 'multiple',
    output_files: ['reports/runtime/nexus_system_health_latest.json'],
    supabase_tables: ['system_health'],
    ui_visibility: 'system_health_tab',
    alpha_visibility: 'status',
    nexus_hermes_visibility: 'status',
    external_action: false,
    ray_review_required: false,
    score: 50,
    next_action: 'connect_to_live_data',
    recovery_prompt: 'Check system health adapter and reconnect to live data sources',
  },
  {
    process_id: 'ray_review_queue',
    department: 'ray_review',
    name: 'Ray Review Queue',
    description: 'Manage Ray review/approval items across all departments',
    activation_mode: 'OBSERVE',
    file_or_command: 'src/lib/rayReviewQueue.ts',
    input_source: 'supabase_approvals',
    output_files: [],
    supabase_tables: ['approvals', 'task_requests'],
    ui_visibility: 'ray_review_tab',
    alpha_visibility: 'full',
    nexus_hermes_visibility: 'full',
    external_action: false,
    ray_review_required: false,
    score: 50,
    next_action: 'connect_to_live_approvals',
    recovery_prompt: 'Check Ray Review queue and reconnect to live approval data',
  },
  {
    process_id: 'command_center_dashboard',
    department: 'command_center',
    name: 'Command Center Dashboard',
    description: 'Central operating dashboard with live status cards',
    activation_mode: 'OBSERVE',
    file_or_command: 'src/components/command-center/MissionControl.tsx',
    input_source: 'multiple',
    output_files: [],
    supabase_tables: [],
    ui_visibility: 'command_center_tab',
    alpha_visibility: 'status',
    nexus_hermes_visibility: 'status',
    external_action: false,
    ray_review_required: false,
    score: 50,
    next_action: 'replace_mock_data_with_live',
    recovery_prompt: 'Reconnect Command Center to live data sources',
  },
  {
    process_id: 'client_portal',
    department: 'client_portal',
    name: 'Client Portal',
    description: 'Client-facing portal with guided journey',
    activation_mode: 'OBSERVE',
    file_or_command: 'src/components/client/ClientPortalShell.jsx',
    input_source: 'supabase_client_profiles',
    output_files: [],
    supabase_tables: ['client_profiles', 'client_tasks', 'readiness_scores'],
    ui_visibility: 'client_portal',
    alpha_visibility: 'client_context',
    nexus_hermes_visibility: 'client_route',
    external_action: false,
    ray_review_required: false,
    score: 25,
    next_action: 'build_premium_shell',
    recovery_prompt: 'Rebuild client portal shell with premium design',
  },
  {
    process_id: 'alpha_strategy_brain',
    department: 'alpha_strategy',
    name: 'Alpha Strategy Brain',
    description: 'Strategy analysis, opportunity scoring, research intake',
    activation_mode: 'SANDBOX_TEST',
    file_or_command: 'src/hermes/alpha/alphaBrain.ts',
    input_source: 'research_intake',
    output_files: ['reports/alpha/'],
    supabase_tables: [],
    ui_visibility: 'alpha_workspace',
    alpha_visibility: 'full',
    nexus_hermes_visibility: 'full',
    external_action: false,
    ray_review_required: false,
    score: 55,
    next_action: 'connect_to_live_research',
    recovery_prompt: 'Reconnect Alpha to live research data',
  },
  {
    process_id: 'alpha_url_review',
    department: 'alpha_strategy',
    name: 'Alpha URL Review',
    description: 'Review URLs for content, opportunity, and quality',
    activation_mode: 'SANDBOX_TEST',
    file_or_command: 'netlify/functions/alpha-url-review.mjs',
    input_source: 'url_input',
    output_files: ['reports/alpha/'],
    supabase_tables: [],
    ui_visibility: 'alpha_workspace',
    alpha_visibility: 'full',
    nexus_hermes_visibility: 'url_route',
    external_action: false,
    ray_review_required: false,
    score: 60,
    next_action: 'test_with_real_url',
    recovery_prompt: 'Test Alpha URL review with a real URL',
  },
  {
    process_id: 'alpha_research_intake',
    department: 'alpha_strategy',
    name: 'Alpha Research Intake',
    description: 'Process independent research items (URLs, repos, ideas)',
    activation_mode: 'DRY_RUN',
    file_or_command: 'src/hermes/alpha/alphaResearchFileAdapter.ts',
    input_source: 'research_inbox',
    output_files: ['hermes_alpha/research_inbox/'],
    supabase_tables: ['research_sources'],
    ui_visibility: 'alpha_workspace',
    alpha_visibility: 'full',
    nexus_hermes_visibility: 'research_route',
    external_action: false,
    ray_review_required: false,
    score: 40,
    next_action: 'build_decision_packet_generator',
    recovery_prompt: 'Build Alpha decision packet generator',
  },
  {
    process_id: 'hermes_work_router',
    department: 'nexus_hermes',
    name: 'Hermes Work Router',
    description: 'Classify prompts and route to correct department/process',
    activation_mode: 'SANDBOX_TEST',
    file_or_command: 'src/lib/hermesIntentClassifier.ts',
    input_source: 'user_prompt',
    output_files: [],
    supabase_tables: ['task_requests'],
    ui_visibility: 'hermes_workroom',
    alpha_visibility: 'routing',
    nexus_hermes_visibility: 'full',
    external_action: false,
    ray_review_required: false,
    score: 55,
    next_action: 'build_work_order_creator',
    recovery_prompt: 'Build Hermes work order creator and department dispatcher',
  },
  {
    process_id: 'youtube_researcher',
    department: 'youtube_research',
    name: 'YouTube Researcher',
    description: 'Research YouTube channels and videos for opportunities',
    activation_mode: 'DRY_RUN',
    file_or_command: 'scripts/research/',
    input_source: 'youtube_api',
    output_files: ['data/cache/youtube/', 'reports/manual_publish/'],
    supabase_tables: ['research_sources'],
    ui_visibility: 'research_panel',
    alpha_visibility: 'research_inbox',
    nexus_hermes_visibility: 'research_route',
    external_action: false,
    ray_review_required: false,
    score: 55,
    next_action: 'connect_to_live_api',
    recovery_prompt: 'Connect YouTube researcher to live API',
  },
  {
    process_id: 'notebooklm_importer',
    department: 'notebooklm',
    name: 'NotebookLM Importer',
    description: 'Import and parse NotebookLM export bundles',
    activation_mode: 'OBSERVE',
    file_or_command: 'data/exports/notebooklm/',
    input_source: 'notebooklm_exports',
    output_files: ['reports/research/'],
    supabase_tables: [],
    ui_visibility: 'research_panel',
    alpha_visibility: 'research_inbox',
    nexus_hermes_visibility: 'research_route',
    external_action: false,
    ray_review_required: false,
    score: 40,
    next_action: 'build_import_parser',
    recovery_prompt: 'Build NotebookLM import parser',
  },
  {
    process_id: 'creative_engine',
    department: 'creative_studio',
    name: 'Creative Learning Engine',
    description: 'Generate quality marketing/video content packages',
    activation_mode: 'DRY_RUN',
    file_or_command: 'src/hermes/nexus/marketingAssetStudio.ts',
    input_source: 'creative_brief',
    output_files: ['reports/creative/'],
    supabase_tables: ['creative_campaigns', 'creative_briefs'],
    ui_visibility: 'creative_studio',
    alpha_visibility: 'creative',
    nexus_hermes_visibility: 'creative_route',
    external_action: false,
    ray_review_required: true,
    score: 45,
    next_action: 'build_quality_score_model',
    recovery_prompt: 'Build creative quality score model',
  },
  {
    process_id: 'app_department',
    department: 'app',
    name: 'App Department',
    description: 'Route app ideas to requirements, specs, and prototypes',
    activation_mode: 'DRY_RUN',
    file_or_command: 'src/lib/nexusProjects.ts',
    input_source: 'app_idea',
    output_files: ['reports/app_department/'],
    supabase_tables: [],
    ui_visibility: 'app_workspace',
    alpha_visibility: 'app_ideas',
    nexus_hermes_visibility: 'app_route',
    external_action: false,
    ray_review_required: true,
    score: 30,
    next_action: 'build_work_order_template',
    recovery_prompt: 'Build App Department work order template',
  },
  {
    process_id: 'trading_lab',
    department: 'trading',
    name: 'Trading Lab',
    description: 'Trading research, strategy comparison, demo trading',
    activation_mode: 'SANDBOX_TEST',
    file_or_command: 'scripts/trading/',
    input_source: 'trading_research',
    output_files: ['reports/trading/'],
    supabase_tables: ['demo_trades'],
    ui_visibility: 'trading_lab',
    alpha_visibility: 'trading',
    nexus_hermes_visibility: 'trading_route',
    external_action: false,
    ray_review_required: false,
    score: 40,
    next_action: 'build_strategy_tournament',
    recovery_prompt: 'Build strategy tournament model',
  },
  {
    process_id: 'email_sandbox',
    department: 'email',
    name: 'Email Sandbox Sender',
    description: 'Send test/sandbox emails via Resend',
    activation_mode: 'DRY_RUN',
    file_or_command: 'scripts/communication/',
    input_source: 'email_template',
    output_files: [],
    supabase_tables: [],
    ui_visibility: 'email_panel',
    alpha_visibility: 'email_route',
    nexus_hermes_visibility: 'email_route',
    external_action: false,
    ray_review_required: false,
    score: 40,
    next_action: 'test_with_resend',
    recovery_prompt: 'Test email sending with Resend API',
  },
  {
    process_id: 'social_draft',
    department: 'social_video',
    name: 'Social/Video Draft Package',
    description: 'Create draft social media and video content packages',
    activation_mode: 'DRY_RUN',
    file_or_command: 'scripts/social/',
    input_source: 'content_brief',
    output_files: ['reports/social/'],
    supabase_tables: ['social_drafts'],
    ui_visibility: 'marketing_panel',
    alpha_visibility: 'social_route',
    nexus_hermes_visibility: 'social_route',
    external_action: false,
    ray_review_required: true,
    score: 35,
    next_action: 'build_draft_package_model',
    recovery_prompt: 'Build social draft package model',
  },
  {
    process_id: 'report_generation',
    department: 'system_health',
    name: 'Report Generation',
    description: 'Generate markdown and JSON reports from system state',
    activation_mode: 'DRY_RUN',
    file_or_command: 'scripts/reports/',
    input_source: 'system_state',
    output_files: ['reports/runtime/', 'reports/manual_publish/'],
    supabase_tables: [],
    ui_visibility: 'reports_center',
    alpha_visibility: 'report_context',
    nexus_hermes_visibility: 'report_route',
    external_action: false,
    ray_review_required: false,
    score: 65,
    next_action: 'connect_to_live_state',
    recovery_prompt: 'Connect report generation to live system state',
  },
  {
    process_id: 'self_audit_monitor',
    department: 'system_health',
    name: 'Self-Audit Monitor',
    description: 'Daily monitoring, auditing, and reporting loop',
    activation_mode: 'DRY_RUN',
    file_or_command: 'scripts/run_nexus_daily_monitor.py',
    input_source: 'system_state',
    output_files: ['reports/runtime/nexus_daily_monitor_latest.md', 'reports/runtime/nexus_daily_monitor_latest.json'],
    supabase_tables: [],
    ui_visibility: 'system_health_tab',
    alpha_visibility: 'status',
    nexus_hermes_visibility: 'status',
    external_action: false,
    ray_review_required: false,
    score: 50,
    next_action: 'build_daily_monitor_script',
    recovery_prompt: 'Build and run daily monitor script',
  },
  {
    process_id: 'telegram_readiness',
    department: 'telegram',
    name: 'Telegram Readiness',
    description: 'Prepare Telegram connection for Hermes and Alpha',
    activation_mode: 'OBSERVE',
    file_or_command: 'reports/telegram/',
    input_source: 'system_state',
    output_files: ['reports/telegram/'],
    supabase_tables: [],
    ui_visibility: 'telegram_panel',
    alpha_visibility: 'telegram_route',
    nexus_hermes_visibility: 'telegram_route',
    external_action: false,
    ray_review_required: false,
    score: 30,
    next_action: 'audit_and_prepare',
    recovery_prompt: 'Audit Telegram readiness and prepare connection plan',
  },
];

export function getProcessById(processId: string): ProcessDefinition | undefined {
  return NEXUS_PROCESS_REGISTRY.find(p => p.process_id === processId);
}

export function getProcessesByDepartment(department: string): ProcessDefinition[] {
  return NEXUS_PROCESS_REGISTRY.filter(p => p.department === department);
}

export function getProcessesByMode(mode: ActivationMode): ProcessDefinition[] {
  return NEXUS_PROCESS_REGISTRY.filter(p => p.activation_mode === mode);
}

export function getProcessSummary(): { total: number; byMode: Record<string, number>; byDepartment: Record<string, number> } {
  const byMode: Record<string, number> = {};
  const byDepartment: Record<string, number> = {};
  for (const p of NEXUS_PROCESS_REGISTRY) {
    byMode[p.activation_mode] = (byMode[p.activation_mode] || 0) + 1;
    byDepartment[p.department] = (byDepartment[p.department] || 0) + 1;
  }
  return { total: NEXUS_PROCESS_REGISTRY.length, byMode, byDepartment };
}
