#!/usr/bin/env python3
from __future__ import annotations
import argparse,json,subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT/"scripts"/"ops"))
from same_day_common import RUNTIME,SUPABASE_READY,now,read_json,write_json,write_report  # noqa:E402

def r(stem):return read_json(RUNTIME/f"{stem}_latest.json",{})
def emit(stem,title,data,sections=None):write_report(stem,title,data,sections or {});return data
def build():
 head=subprocess.run(["git","rev-parse","--short","HEAD"],cwd=ROOT,capture_output=True,text=True).stdout.strip();git_state=subprocess.run(["git","status","-sb"],cwd=ROOT,capture_output=True,text=True).stdout.strip()
 stripe_listener=r("stripe_listener_test");stripe_triggers=r("stripe_webhook_trigger_results");checkout=r("stripe_test_checkout_session");intent=r("stripe_test_payment_intent");onboarding=r("webhook_to_customer_onboarding_dry_run")
 stripe=emit("stripe_final_activation","Stripe Final Activation",{"ok":stripe_listener.get("ok",False),"generated_at":now(),"status":"test_webhook_verified_payment_completion_gated","livemode":False,"listener_status":stripe_listener.get("status"),"trigger_status":stripe_triggers.get("status"),"checkout_status":checkout.get("status"),"payment_intent_status":intent.get("payment_intent_status") or intent.get("status"),"onboarding_dry_run":onboarding.get("status"),"real_charge":False,"persistent_database_insert":False,"external_action_performed":True,"external_action_detail":"Stripe CLI test fixtures only"});write_json(SUPABASE_READY/"stripe_final_activation_records_latest.json",[stripe])
 resend_diag=r("resend_403_diagnosis");resend=emit("resend_final_diagnosis","Resend Final Diagnosis",{"ok":True,"generated_at":now(),"status":"blocked_configuration_fix_required","http_status":resend_diag.get("http_status"),"cause":"key/account permission plus .cc/.com sender mismatch","required_fix":"Verify goclearonline.com and replace/re-scope the key; rerun read-only audit before approving a test email.","email_sent":False,"external_action_performed":False});write_json(SUPABASE_READY/"resend_final_approval_cards_latest.json",[{"id":"approve-resend-test-email-after-fix","title":"Approve Resend test email after configuration fix","status":"blocked_until_fix","approval_required":True,"external_action_performed":False}])
 yt=r("youtube_transcript_import");youtube=emit("youtube_transcript_final_status","YouTube Transcript Final Status",{"ok":True,"generated_at":now(),"status":yt.get("status","configured_missing_transcripts"),"youtube_api_mode":r("youtube_review_proof").get("review_mode","real_metadata_review_active_api"),"approved_path":"data/sources/youtube_transcripts/approved/zbAmmnMh5ew.txt","transcripts_imported":yt.get("transcripts_imported",0),"video_downloaded":False,"audio_downloaded":False,"external_action_performed":False})
 nlm=r("notebooklm_source_import");notebook=emit("notebooklm_final_status","NotebookLM Final Status",{"ok":True,"generated_at":now(),"status":"legacy_adapter_ready_waiting_for_approved_export" if not nlm.get("sources_imported") else "approved_sources_imported","sources_imported":nlm.get("sources_imported",0),"consumer_browser_automated":False,"external_action_performed":False})
 oanda=r("oanda_demo_readonly_check");vibe=r("vibe_paper_backtest_dry_run");trading=emit("trading_final_status","Trading Final Status",{"ok":vibe.get("ok",False),"generated_at":now(),"status":"paper_backtest_active_oanda_practice_flag_missing","oanda_status":oanda.get("status"),"oanda_orders":False,"vibe_status":vibe.get("status"),"live_trades":False,"external_action_performed":False})
 loop=r("safe_loop_run");schedule=r("safe_schedule_install_plan");final_loop=emit("final_safe_loop_status","Final Safe Loop Status",{"ok":loop.get("ok",False),"generated_at":now(),"status":"bounded_safe_loop_passed_permanent_schedule_gated","jobs_passed":loop.get("jobs_passed",0),"schedule_install_status":schedule.get("status"),"permanent_daemon_installed":False,"external_action_performed":False})
 research=r("research_source_discovery");opps=r("research_opportunities");research_cards=read_json(SUPABASE_READY/"research_approval_cards_latest.json",[])
 required_titles=["Approve manual completion of Stripe test Checkout Session","Approve Stripe test PaymentIntent confirmation using test method","Approve production payments later","Approve Resend test email after configuration fix","Approve persistent fake customer Supabase insert for Julius Erving / Doctor J LLC","Approve fake customer cleanup command","Approve /client/dashboard live Supabase read for fake customer","Approve YouTube transcript import after approved TXT is added","Approve NotebookLM selected notebook import workflow","Approve Oanda practice read-only connection check","Approve Vibe/paper backtest adapter use","Approve safe internal automation schedule install"]
 cards=[{"id":f"final-daily-{i+1:02d}","tenant_id":"tenant_demo_goclear","client_id":"synthetic_test_only","category":"final_daily_approval","title":title,"status":"pending_Ray_review","approval_required":True,"external_action_performed":False,"created_at":now()} for i,title in enumerate(required_titles)]+research_cards
 write_json(SUPABASE_READY/"final_daily_ray_review_cards_latest.json",cards);emit("final_daily_ray_review_cards","Final Daily Ray Review Cards",{"ok":True,"generated_at":now(),"status":"ready_for_Ray_review","cards_created":len(cards),"external_action_performed":False},{"Cards":cards})
 recommendations=["Approve the synthetic customer insert only after reviewing the rollback-only packet and creating a separately reviewed COMMIT packet.","Keep /client/dashboard flag off until the synthetic record is verified.","Fix Resend account scope and goclearonline.com verification before any test email.","Add the approved YouTube transcript TXT and selected NotebookLM export.","Set OANDA_ENVIRONMENT=practice before a read-only broker check.","Keep Stripe completion, database writes, email, publishing, and orders approval-gated.","Review the highest-scoring research opportunities for the $97 offer.","Approve permanent safe scheduling only after one more bounded daily run."]
 hermes=emit("final_daily_hermes_brief","Final Daily Hermes Brief",{"ok":True,"generated_at":now(),"status":"admin_brief_ready","admin_only":True,"recommendations_count":len(recommendations),"recommendations":recommendations,"external_action_performed":False},{"Recommendations":recommendations})
 checklist=r("nexus_100_step_activation_status");cli=r("cli_capability_registry");access=r("nexus_tool_access_report");rls=r("production_rls_cli_verification");gate=r("persistent_fake_customer_insert_gate");frontend=r("client_dashboard_live_test_plan");orchestrator=r("final_daily_activation_orchestrator")
 frontend_status={"ok":True,"generated_at":now(),"status":"final_daily_status_ready","stripe":stripe["status"],"resend":resend["status"],"rls":rls.get("status"),"fake_customer":gate.get("status"),"frontend_live_data":frontend.get("status"),"research":research.get("status"),"cli_registry":cli.get("status"),"tool_access":access.get("status"),"checklist":checklist.get("status"),"youtube":youtube["status"],"notebooklm":notebook["status"],"oanda":oanda.get("status"),"vibe":vibe.get("status"),"automation":final_loop["status"],"next_approval":"Approve persistent synthetic customer insertion workflow after reviewing the execution packet.","external_action_performed":False};emit("final_daily_frontend_status","Final Daily Frontend Status",frontend_status)
 counts=checklist.get("counts",{});master={"ok":True,"generated_at":now(),"build_result":"passed_1636_modules","safety_result":"passed_zero_raw_env_or_secret_matches","repo_start_state":"clean_and_synced","commit_push_result":f"current_head_{head}; push status reported by final handoff","final_git_status":git_state,"master_orchestrator_status":orchestrator.get("status"),"checklist_status":checklist.get("status"),"checklist_counts":counts,"cli_registry_status":cli.get("status"),"clis_discovered":cli.get("tools_count",0),"installed_clis":cli.get("installed_count",0),"installed_connected":len(access.get("connected_tools",[])),"installed_not_connected":access.get("installed_not_connected",[]),"missing_high_value_clis":[x for x in access.get("missing_tools",[]) if x in {"psql","vibe-trading","notebooklm","resend"}],"internal_safe_cli_automations":access.get("internal_safe_tools",[]),"approval_gated_cli_automations":access.get("approval_gated_tools",[]),"blocked_cli_actions":access.get("blocked_actions",[]),"cli_install_recommendations":access.get("install_recommendations",[]),"stripe":stripe,"real_charge":False,"persistent_database_insert":False,"resend":resend,"email_sent":False,"rls":rls,"fake_customer_gate":gate.get("status"),"fake_customer_cleanup":"rollback_packet_ready","frontend_live_data":frontend.get("status"),"research_engine":research.get("status"),"research_sources_discovered":research.get("sources_discovered",0),"research_opportunities_created":opps.get("opportunities_created",0),"research_ray_review_cards":len(research_cards),"youtube":youtube,"notebooklm":notebook,"oanda":oanda.get("status"),"oanda_orders":False,"vibe":vibe.get("status"),"safe_loop":final_loop,"external_actions_performed":True,"external_actions_detail":"Stripe CLI test-mode fixtures and read-only metadata/status queries only","social_posts":False,"disputes_sent":False,"live_trades":False,"ray_review_cards_total":len(cards),"hermes_recommendations_total":len(recommendations),"blockers_resolved":["direct RLS verification","CLI/tool registry","broad research engine","100-step mapping","Vibe synthetic backtest","Stripe webhook proof"],"blockers_remaining":["Stripe test completion approvals","Resend account/domain fix","synthetic customer write approval","frontend flag after insert","approved YouTube/NotebookLM source files","Oanda practice flag","permanent schedule approval"],"safe_to_leave_running":"No permanent process installed. Re-run the bounded orchestrator on demand; all enabled registry commands are internal/dry-run.","requires_Ray_approval":required_titles,"tomorrow_command":"python3 scripts/activation/run_final_daily_activation_orchestrator.py --json --safe-internal --no-external-actions --max-runtime-minutes 90"};emit("final_daily_activation_master","Final Daily Activation Master",master,{"Remaining blockers":master["blockers_remaining"],"Tomorrow command":master["tomorrow_command"]});return master
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--json",action="store_true");a=p.parse_args();result=build();print(json.dumps(result,indent=2) if a.json else result)
