#!/usr/bin/env python3
from __future__ import annotations
import argparse,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT/"scripts"/"ops"))
from same_day_common import RUNTIME,SUPABASE_READY,now,read_json,write_json,write_report  # noqa:E402
def r(stem):return read_json(RUNTIME/f"{stem}_latest.json",{})
def build():
 write_report("oanda_vibe_notebooklm_baseline","Oanda Vibe NotebookLM Baseline",{"ok":True,"generated_at":now(),"status":"focused_connector_activation_started_from_clean_synced_main","build_start":"passed_1636_modules","secrets_printed":False,"live_trading_enabled":False,"external_action_performed":False})
 verify=r("oanda_demo_account_verification");account=r("oanda_demo_account_check");pricing=r("oanda_demo_pricing_check");instruments=r("oanda_demo_instruments_check");smoke=r("oanda_demo_trade_smoke_test");closeout=r("oanda_demo_trade_closeout");vibe=r("vibe_paper_backtest_dry_run");bridge=r("vibe_oanda_demo_bridge");bridge_dry=r("vibe_oanda_demo_bridge_dry_run");strategy=r("vibe_oanda_demo_strategy_smoke_test");cli=r("notebooklm_cli_discovery");access=r("notebooklm_access_mode_classification");listing=r("notebooklm_notebook_list");selected=r("notebooklm_selected_notebook_registry");sync=r("notebooklm_selected_notebook_sync");schedule=r("automation_schedule_registry");tool=r("nexus_tool_access_registry");research=r("research_source_discovery");opps=r("research_opportunities")
 cards=[
  {"id":"approve-oanda-recurring-demo-orders","title":"Approve recurring Oanda demo order execution","status":"pending_Ray_review","approval_required":True},
  {"id":"approve-vibe-demo-strategy-beyond-smoke","title":"Approve Vibe/Oanda demo strategy execution beyond smoke test","status":"pending_Ray_review","approval_required":True},
  {"id":"approve-notebooklm-selected-export","title":"Approve selected NotebookLM export into the watched folder","status":"pending_Ray_review","approval_required":True},
  {"id":"review-notebooklm-cli-reinstall","title":"Review whether to reinstall the unofficial nlm CLI in an isolated environment","status":"pending_security_review","approval_required":True},
  {"id":"approve-connector-schedule-install","title":"Approve Oanda/Vibe/NotebookLM safe schedule installation","status":"pending_Ray_review","approval_required":True},
  {"id":"keep-live-and-browser-blocks","title":"Keep Oanda live trading and unofficial NotebookLM browser automation blocked","status":"policy_active","approval_required":True},
 ]
 for card in cards:card.update({"tenant_id":"tenant_demo_goclear","client_id":"not_applicable","category":"connector_activation_approval","external_action_performed":False,"created_at":now()})
 write_json(SUPABASE_READY/"oanda_vibe_notebooklm_ray_review_cards_latest.json",cards);write_report("oanda_vibe_notebooklm_ray_review_cards","Oanda Vibe NotebookLM Ray Review Cards",{"ok":True,"generated_at":now(),"status":"ready_for_Ray_review","cards_created":len(cards),"external_action_performed":False},{"Cards":cards})
 recs=["Oanda practice access is verified; keep the fxtrade host blocked.","Both approved one-unit demo smoke trades closed and the account returned to zero open positions.","Use the recovered Vibe adapter for paper/backtest and keep recurring demo execution approval-gated.","The historical nlm CLI binary is absent; the legacy adapter is the current callable connector.","Use approved watched exports until Ray separately approves security review/reinstallation of the unofficial CLI.","Assign exported notebook names to one of the nine configured research routes.","Install only the safe schedule after reviewing its commands and rollback path."]
 write_report("oanda_vibe_notebooklm_hermes_brief","Oanda Vibe NotebookLM Hermes Brief",{"ok":True,"generated_at":now(),"status":"admin_brief_ready","admin_only":True,"recommendations_count":len(recs),"recommendations":recs,"external_action_performed":False},{"Recommendations":recs})
 lanes=selected.get("research_lanes_connected",[]);watched=selected.get("watched_export_lanes",[]);frontend={"ok":True,"generated_at":now(),"status":"connector_status_ready","oanda_demo_endpoint_verified":verify.get("ok",False),"oanda_account_check":account.get("status"),"oanda_pricing_check":pricing.get("status"),"oanda_instruments_check":instruments.get("status"),"oanda_demo_smoke":smoke.get("status"),"oanda_closeout":closeout.get("status"),"vibe_paper":vibe.get("status"),"vibe_oanda_bridge":bridge.get("status"),"vibe_strategy_smoke":strategy.get("status"),"notebooklm_cli_found":cli.get("cli_found",False),"notebooklm_selected_workflow_available":access.get("legacy_adapter_found",False),"notebooklm_access_mode":access.get("access_mode"),"notebooks_found":listing.get("notebooks_found_count",0),"selected_notebooks":selected.get("selected_notebooks_count",0),"research_lanes_connected":lanes,"watched_export_routes":watched,"notebooklm_sync":sync.get("status"),"live_oanda_blocked":True,"unofficial_notebooklm_automation_gated":True,"external_action_performed":False};write_report("oanda_vibe_notebooklm_frontend_status","Oanda Vibe NotebookLM Frontend Status",frontend)
 research_update={"ok":True,"generated_at":now(),"status":"connector_research_lanes_updated","requested_lanes":["notebooklm_official_api","notebooklm_local_cli","notebooklm_selected_notebooks","notebooklm_legacy_adapter","notebooklm_watched_exports","oanda_demo_market_data","oanda_demo_strategy_results","vibe_oanda_demo_bridge","trading_demo_outcomes"],"sources_discovered":research.get("sources_discovered",0),"opportunities_created":opps.get("opportunities_created",0),"external_action_performed":False};write_report("oanda_vibe_notebooklm_research_update","Oanda Vibe NotebookLM Research Update",research_update)
 schedule_report={"ok":schedule.get("ok",False),"generated_at":now(),"status":"connector_schedules_registered_not_installed","scheduled_automation_count":schedule.get("scheduled_automation_count",0),"loop_safe_jobs":len(schedule.get("loop_safe_executed",[])),"safety_violations":schedule.get("safety_violations",[]),"permanent_schedule_installed":False,"approval_required":True,"external_action_performed":False};write_report("oanda_vibe_notebooklm_schedule","Oanda Vibe NotebookLM Schedule",schedule_report)
 external=["Oanda practice account summary read","Oanda practice instruments read","Oanda practice AUD_USD pricing read","Oanda one-unit demo smoke order and immediate close","Vibe bridge one-unit Oanda demo strategy smoke and immediate close"]
 master={"ok":True,"generated_at":now(),"build_result":"passed","safety_result":"passed_no_raw_credentials","oanda_credentials_detected":verify.get("credentials_detected",False),"oanda_demo_endpoint_verified":verify.get("ok",False),"oanda_account_check_passed":account.get("ok",False),"oanda_pricing_check_passed":pricing.get("ok",False),"oanda_instruments_check_passed":instruments.get("ok",False),"oanda_demo_smoke_trade_placed":smoke.get("demo_order_placed",False),"oanda_demo_smoke_trade_closed":smoke.get("closed",False),"oanda_live_endpoint_used":False,"oanda_live_or_funded_trade":False,"vibe_cli_found":False,"vibe_recovered_adapter_usable":vibe.get("ok",False),"vibe_paper_backtest":vibe.get("summary",{}),"vibe_oanda_demo_bridge":bridge.get("status"),"vibe_oanda_demo_strategy_smoke":strategy.get("status"),"notebooklm_cli_found":cli.get("cli_found",False),"legacy_notebooklm_connector_found":cli.get("legacy_adapter_found",False),"notebooklm_selected_access_mode":access.get("access_mode"),"notebooks_listed":listing.get("notebooks_listed",False),"notebooks_found_count":listing.get("notebooks_found_count",0),"selected_notebooks_count":selected.get("selected_notebooks_count",0),"research_lanes_connected":lanes,"watched_export_routes":watched,"notebook_sync_status":sync.get("status"),"manual_export_still_required":access.get("manual_export_required",True),"schedule_status":schedule_report.get("status"),"cli_registry_updated":True,"tool_access_violations":len(tool.get("safety_violations",[])),"research_engine_updated":True,"frontend_status_updated":True,"ray_review_cards_created":len(cards),"hermes_recommendations_created":len(recs),"real_money_actions":False,"external_actions_performed":True,"external_actions":external,"blockers_resolved":["Oanda practice verification","Oanda account/pricing/instrument reads","Oanda demo smoke and closeout","Vibe/Oanda bridge dry-run and smoke","NotebookLM access mode classification","NotebookLM watched-folder selected workflow"],"blockers_remaining":["Historical unofficial nlm CLI binary is missing, so live notebook listing is unavailable","No NotebookLM export is present, so selected notebook count is zero","Permanent connector schedules remain approval-gated","Recurring demo strategy execution remains approval-gated"],"exact_next_command":"python3 scripts/activation/sync_selected_notebooklm_notebooks.py --json"};write_report("oanda_vibe_notebooklm_master","Oanda Vibe NotebookLM Master",master,{"External actions":external,"Remaining blockers":master["blockers_remaining"]});return master
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--json",action="store_true");a=p.parse_args();result=build();print(json.dumps(result,indent=2) if a.json else result)
