#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from youtube_engine_common import ROOT,SUPABASE_READY,now,read_json,write_report
R=ROOT/"reports/runtime"
def load(n):return read_json(R/f"{n}_latest.json",{})
def build():
 api=load("youtube_api_connector_audit");api_run=load("youtube_api_metadata_intake");probe=load("youtube_ytdlp_probe");trans=load("youtube_transcript_import");nb=load("notebooklm_access_audit");nbx=load("youtube_notebooklm_export_bundle");nbi=load("notebooklm_source_import");score=load("youtube_research_scoring");out=load("youtube_research_outputs");review=load("youtube_review_proof");sched=load("automation_schedule_registry");local=load("youtube_local_tool_audit")
 frontend={"ok":True,"generated_at":now(),"youtube":{"api_key_present":api.get("api_key_present",False),"quota_policy_status":"active","ytdlp_installed":local.get("local_ytdlp_available",False),"ytdlp_probe_status":probe.get("status"),"transcript_import_status":trans.get("status"),"notebooklm_access":nb.get("status"),"notebooklm_export":nbx.get("status"),"notebooklm_import":nbi.get("status"),"current_mode":review.get("review_mode"),"approved_targets":review.get("channels_configured",0),"reviewed_items":review.get("reviewed_items_count",0),"opportunities":out.get("business_opportunities",0),"ray_review_cards":out.get("approval_cards",0),"next_required_approval":review.get("next_required_action")},"external_action_performed":False};write_report("youtube_frontend_visibility","YouTube Frontend Visibility",frontend)
 auto={"ok":True,"generated_at":now(),"scheduled_automation_count":sched.get("scheduled_automation_count",0),"enabled_internal_automations":sched.get("enabled_internal_automations",0),"approval_gated_automations":sched.get("approval_gated_automations",0),"blocked_external_automations":sched.get("blocked_external_automations",0),"next_recommended_run":sched.get("next_recommended_run"),"bounded_loop_status":"integrated_not_running","youtube_schedule_status":"quota/cache internal enabled; yt-dlp manual approval","supabase_schedule_status":"dry-run enabled; live insert blocked","ray_review_schedule_status":"every 4 hours","hermes_schedule_status":"every 4 hours","external_action_performed":False};write_report("frontend_automation_schedule_visibility","Frontend Automation Schedule Visibility",auto)
 loop={"ok":True,"generated_at":now(),"status":"integrated","safe_cycle_command":"python3 scripts/activation/run_automation_schedule_registry.py --json --run-loop-safe","api_cache_respected":True,"ytdlp_probe_auto_run":False,"transcript_import_approved_local_only":True,"public_posting":False,"external_action_performed":False};write_report("youtube_loop_integration","YouTube Loop Integration",loop);write_report("automation_loop_integration","Automation Loop Integration",{**loop,"schedule_registry":"configs/automation_schedule_registry.json"})
 master={"ok":True,"generated_at":now(),"yt_dlp_installed":local.get("local_ytdlp_available"),"youtube_api_key_present":api.get("api_key_present"),"connector_ran":"youtube_api" if api_run.get("metadata_records_created") else "youtube_ytdlp_local_probe" if probe.get("metadata_records_created") else "none","api_metadata_intake_ran":bool(api_run.get("approved_targets_checked")),"ytdlp_probe_ran":bool(probe.get("targets_checked")),"videos_downloaded":False,"audio_downloaded":False,"subtitles_available":probe.get("subtitles_available_count",0),"transcripts_imported":trans.get("transcripts_imported",0),"real_metadata_review":review.get("review_mode") in {"real_metadata_review_active_api","real_metadata_review_active_ytdlp_local"},"real_transcript_review":review.get("review_mode")=="real_transcript_review_active","current_mode":review.get("review_mode"),"approved_targets":review.get("channels_configured",0),"targets_checked":probe.get("targets_checked",0)+api_run.get("approved_targets_checked",0),"metadata_records":api_run.get("metadata_records_created",0)+probe.get("metadata_records_created",0),"review_items":review.get("reviewed_items_count",0),"opportunities":out.get("business_opportunities",0),"content_ideas":out.get("content_drafts",0),"ray_review_cards":out.get("approval_cards",0),"hermes_recommendations":out.get("hermes_recommendations",0),"automation_schedules_created":sched.get("scheduled_automation_count",0),"enabled_internal_automations":sched.get("enabled_internal_automations",0),"approval_gated_automations":sched.get("approval_gated_automations",0),"blocked_external_automations":sched.get("blocked_external_automations",0),"youtube_schedule_status":auto["youtube_schedule_status"],"supabase_schedule_status":auto["supabase_schedule_status"],"ray_review_schedule_status":auto["ray_review_schedule_status"],"hermes_schedule_status":auto["hermes_schedule_status"],"continuous_loop_schedule_status":"integrated_not_running","ray_approval_required":["subtitle/source-text import","external publishing","live Supabase inserts"],"external_action_performed":False};write_report("youtube_research_engine_activation","YouTube Research Engine Activation",master);return master
def main():
 p=argparse.ArgumentParser();p.add_argument("--json",action="store_true");a=p.parse_args();r=build();print(json.dumps(r,indent=2) if a.json else r);return 0
if __name__=="__main__":raise SystemExit(main())
