import type { AiBrainProfile, BrainMemoryType } from './brainTypes';
import type { IntelligenceDataClass, IntelligenceRecordType } from '../intelligence/intelligenceTypes';

const publicData: IntelligenceDataClass[] = ['PUBLIC', 'INTERNAL'];
const executiveData: IntelligenceDataClass[] = ['INTERNAL', 'EXECUTIVE', 'CLIENT_AGGREGATE', 'FINANCIAL', 'SOURCE_CODE'];
const clientData: IntelligenceDataClass[] = ['PUBLIC', 'CLIENT_AGGREGATE', 'CLIENT_PII', 'FINANCIAL'];

const allRecordTypes: IntelligenceRecordType[] = [
  'SOURCE',
  'EVIDENCE',
  'CLAIM',
  'OBSERVATION',
  'APPROVED_KNOWLEDGE',
  'POLICY',
  'RECOMMENDATION',
  'MEMORY',
  'CONTEXT',
  'MODEL_OUTPUT',
];

const hermesMemory: BrainMemoryType[] = ['CONVERSATION_MEMORY', 'SELECTION_MEMORY', 'ADVISORY_MEMORY', 'TASK_MEMORY', 'EXECUTIVE_DECISION_MEMORY'];
const alphaMemory: BrainMemoryType[] = ['CONVERSATION_MEMORY', 'RESEARCH_MEMORY', 'SELECTION_MEMORY'];
const clientMemory: BrainMemoryType[] = ['CONVERSATION_MEMORY', 'CLIENT_JOURNEY_MEMORY', 'SELECTION_MEMORY'];

function departmentTemplate(brainId: string, name: string, departmentId: string, allowedDomains: string[], allowedCapabilities: string[]): AiBrainProfile {
  return {
    brainId,
    name,
    role: 'DEPARTMENT_AI',
    description: `${name} template for future bounded specialist assistance. It is not an autonomous active worker.`,
    departmentId,
    allowedKnowledgeDomains: allowedDomains,
    prohibitedKnowledgeDomains: ['credentials', 'production_control', 'cross_tenant_client_data'],
    allowedDataClasses: ['PUBLIC', 'INTERNAL'],
    prohibitedDataClasses: ['CLIENT_PII', 'CREDENTIAL', 'PRODUCTION_CONTROL'],
    allowedRecordTypes: ['SOURCE', 'EVIDENCE', 'OBSERVATION', 'APPROVED_KNOWLEDGE', 'POLICY', 'RECOMMENDATION', 'MEMORY', 'CONTEXT'],
    prohibitedRecordTypes: ['MODEL_OUTPUT'],
    allowedMemoryTypes: ['DEPARTMENT_WORK_MEMORY', 'SELECTION_MEMORY'],
    allowedCapabilities,
    mayUseWeb: false,
    mayUseSupabase: false,
    mayAccessClientPii: false,
    mayAccessPrivateSourceCode: false,
    mayCreateClaims: true,
    mayApproveKnowledge: false,
    mayCreateWork: false,
    mayExecuteWork: false,
    requiredApprovalLevel: 'RAY_REVIEW',
    contextBuilderId: 'department_template_context',
    retrievalPolicyId: 'department_template_retrieval',
    memoryPolicyId: 'department_template_memory',
    systemPolicyId: 'department_template_system_policy',
    tenantIsolationRequired: true,
    evidenceRequired: true,
    citationsRequired: true,
    status: 'PLANNED',
  };
}

export const brainProfiles: AiBrainProfile[] = [
  {
    brainId: 'nexus_hermes',
    name: 'Nexus Hermes',
    role: 'HERMES',
    description: 'Private internal Executive Coordinator and CEO advisor.',
    departmentId: 'executive',
    allowedKnowledgeDomains: ['executive', 'operations', 'capabilities', 'knowledge', 'customers', 'revenue', 'research', 'security', 'deployment'],
    prohibitedKnowledgeDomains: ['unapproved_alpha_fact', 'credentials'],
    allowedDataClasses: executiveData,
    prohibitedDataClasses: ['CREDENTIAL'],
    allowedRecordTypes: allRecordTypes.filter((type) => type !== 'MODEL_OUTPUT'),
    prohibitedRecordTypes: ['MODEL_OUTPUT'],
    allowedMemoryTypes: hermesMemory,
    allowedCapabilities: ['executive_command_center', 'hermes_executive_advisor', 'capability_os_registry', 'brain_context_assembly', 'knowledge_health'],
    mayUseWeb: false,
    mayUseSupabase: true,
    mayAccessClientPii: false,
    mayAccessPrivateSourceCode: true,
    mayCreateClaims: true,
    mayApproveKnowledge: false,
    mayCreateWork: true,
    mayExecuteWork: false,
    requiredApprovalLevel: 'RAY_REVIEW',
    contextBuilderId: 'hermes_executive_context',
    retrievalPolicyId: 'hermes_retrieval_policy',
    memoryPolicyId: 'hermes_memory_policy',
    systemPolicyId: 'hermes_system_policy',
    tenantIsolationRequired: true,
    evidenceRequired: true,
    citationsRequired: true,
    status: 'ACTIVE',
  },
  {
    brainId: 'alpha_research',
    name: 'Alpha',
    role: 'ALPHA',
    description: 'Independent research and outside-opinion brain.',
    departmentId: 'research',
    allowedKnowledgeDomains: ['public_research', 'repo_intelligence', 'competitive_patterns', 'market', 'monetization'],
    prohibitedKnowledgeDomains: ['client_records', 'credentials', 'production_control', 'executive_private_memory'],
    allowedDataClasses: publicData,
    prohibitedDataClasses: ['CLIENT_PII', 'FINANCIAL', 'CREDENTIAL', 'PRODUCTION_CONTROL', 'SOURCE_CODE'],
    allowedRecordTypes: ['SOURCE', 'EVIDENCE', 'CLAIM', 'OBSERVATION', 'RECOMMENDATION', 'MEMORY', 'CONTEXT'],
    prohibitedRecordTypes: ['APPROVED_KNOWLEDGE', 'POLICY', 'MODEL_OUTPUT'],
    allowedMemoryTypes: alphaMemory,
    allowedCapabilities: ['alpha_independent_research', 'repo_intelligence_registry', 'github_mcp_reader'],
    mayUseWeb: true,
    mayUseSupabase: false,
    mayAccessClientPii: false,
    mayAccessPrivateSourceCode: false,
    mayCreateClaims: true,
    mayApproveKnowledge: false,
    mayCreateWork: false,
    mayExecuteWork: false,
    requiredApprovalLevel: 'RAY_REVIEW',
    contextBuilderId: 'alpha_research_context',
    retrievalPolicyId: 'alpha_public_research_policy',
    memoryPolicyId: 'alpha_research_memory_policy',
    systemPolicyId: 'alpha_no_supabase_policy',
    tenantIsolationRequired: false,
    evidenceRequired: true,
    citationsRequired: true,
    status: 'PARTIAL',
  },
  {
    brainId: 'client_ai',
    name: 'Client-Facing AI',
    role: 'CLIENT_AI',
    description: 'Tenant-safe client guidance and workflow assistance.',
    departmentId: 'customer_support',
    allowedKnowledgeDomains: ['client_safe_guidance', 'documents', 'credit_readiness', 'business_readiness', 'review_status'],
    prohibitedKnowledgeDomains: ['executive', 'internal_security', 'repo_intelligence', 'alpha_raw_research'],
    allowedDataClasses: clientData,
    prohibitedDataClasses: ['EXECUTIVE', 'CREDENTIAL', 'SOURCE_CODE', 'PRODUCTION_CONTROL'],
    allowedRecordTypes: ['EVIDENCE', 'OBSERVATION', 'APPROVED_KNOWLEDGE', 'POLICY', 'RECOMMENDATION', 'MEMORY', 'CONTEXT'],
    prohibitedRecordTypes: ['CLAIM', 'MODEL_OUTPUT'],
    allowedMemoryTypes: clientMemory,
    allowedCapabilities: ['client_authentication', 'document_upload', 'client_review_request', 'client_admin_route_guards'],
    mayUseWeb: false,
    mayUseSupabase: true,
    mayAccessClientPii: true,
    mayAccessPrivateSourceCode: false,
    mayCreateClaims: false,
    mayApproveKnowledge: false,
    mayCreateWork: false,
    mayExecuteWork: false,
    requiredApprovalLevel: 'ADMIN',
    contextBuilderId: 'client_ai_tenant_context',
    retrievalPolicyId: 'client_tenant_safe_policy',
    memoryPolicyId: 'client_journey_memory_policy',
    systemPolicyId: 'client_safe_language_policy',
    tenantIsolationRequired: true,
    evidenceRequired: true,
    citationsRequired: false,
    status: 'ACTIVE',
  },
  departmentTemplate('engineering_brain_template', 'Engineering Brain', 'engineering', ['engineering', 'deployment', 'capabilities'], ['typescript_verification', 'production_build', 'route_verification']),
  departmentTemplate('research_brain_template', 'Research Brain', 'research', ['public_research', 'repo_intelligence'], ['repo_intelligence_registry']),
  departmentTemplate('credit_funding_brain_template', 'Credit and Funding Brain', 'credit_funding', ['credit_readiness', 'business_readiness', 'documents'], ['document_upload', 'strategy_matching']),
  departmentTemplate('marketing_brain_template', 'Marketing Brain', 'marketing', ['marketing', 'customer_safe_guidance'], ['revenue_recommendations']),
  departmentTemplate('creative_brain_template', 'Creative Brain', 'creative', ['creative', 'marketing'], []),
  departmentTemplate('customer_support_brain_template', 'Customer Support Brain', 'customer_support', ['customers', 'documents', 'review_status'], ['client_review_request']),
  departmentTemplate('finance_brain_template', 'Finance Brain', 'finance', ['revenue', 'payments'], ['stripe_test_checkout', 'order_creation', 'fulfillment']),
  departmentTemplate('knowledge_brain_template', 'Knowledge Brain', 'knowledge', ['knowledge', 'policy', 'evidence'], ['intelligence_registry', 'knowledge_review']),
  departmentTemplate('trading_research_brain_template', 'Trading Research Brain', 'trading', ['public_research', 'trading_research'], ['trading_research', 'backtesting']),
];

export function getBrainProfiles(): AiBrainProfile[] {
  return brainProfiles;
}

export function getBrainProfile(brainId: string): AiBrainProfile | undefined {
  return brainProfiles.find((profile) => profile.brainId === brainId);
}
