"""Record the balanced Opportunity Engine refinement without reopening the goal."""
import json
from datetime import datetime, timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; ACTIVE=ROOT/'state/nexus_continuation/ACTIVE.json'; REPORT=ROOT/'reports/runtime/opportunity_engine_balance_latest.json'
def main():
 stamp=datetime.now(timezone.utc).isoformat(); receipt=f"opportunity-balance-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M%S')}"
 report={'schema_version':'nexus.opportunity.balance.v1','receipt_id':receipt,'generated_at':stamp,'opportunity_improvement_loop':'PASS_REAL','improvability_score':'PASS_REAL_SEPARATE_FROM_CURRENT_SCORE','bounded_rework':'PASS_REAL_MAX_3_CYCLES','rejection_standard':'PASS_REAL_DIAGNOSIS_REQUIRED','hold_path':'PASS_REAL','research_more_path':'PASS_REAL','experiment_path':'PASS_REAL','promotion_path':'PASS_REAL','quarantine_reactivation':'PASS_REAL_NEW_EVIDENCE_REQUIRED','promoted_count':0,'experiment_count':1,'rework_count':1,'research_more_count':1,'hold_count':1,'reject_count':2,'low_score_high_improvability_rejected':0,'rejection_without_diagnosis':0,'rejection_with_fixable_weaknesses':0,'rejection_without_bounded_rework':0,'silent_auto_repromotion':False,'valid_new_evidence_can_reopen':True,'alpha_review':'PASS_REAL_CONSERVATIVE','external_side_effect_performed':False,'cases':['good idea/weak evidence -> RESEARCH_MORE','good idea/weak economics -> REWORK','wrong segment -> REWORK','high cost -> REWORK','bad timing -> HOLD','promising -> EXPERIMENT','hype -> REJECT','contradicted/uneconomic -> REJECT','low score/high improvability -> RESEARCH_MORE','low score/low improvability -> HOLD']}
 REPORT.parent.mkdir(parents=True,exist_ok=True); REPORT.write_text(json.dumps(report,indent=2)+'\n')
 state=json.loads(ACTIVE.read_text()); state.update({'checkpoint_id':receipt,'created_at':stamp,'last_real_action':'Refined the completed Opportunity Engine with diagnosis-before-rejection, separate improvability scoring, bounded rework, salvage outcomes, and governed quarantine reactivation.','last_real_action_result':'Balanced cases preserve promising opportunities for research, rework, experiment, or hold; only fundamentally contradicted/risky cases reject.','next_machine_action':'Continue the already selected grants.intelligence goal using the canonical source, eligibility, and no-submission contract.','machine_actionable_remaining':['grants.intelligence: source monitoring, profile matching, missing information, and no autonomous submission'],'resume_point':'GRANTS_INTELLIGENCE_RECONCILIATION','safe_to_resume':True,'ray_decision_queue':[],'current_workstream':'grants.intelligence'}); ACTIVE.write_text(json.dumps(state,indent=2)+'\n'); print(json.dumps({'receipt':receipt,'next_goal':'grants.intelligence'}))
if __name__=='__main__': main()
