"""Durable, bounded WP8.3 mobile-detailing business loop.

This is an execution coordinator, not a second agent brain.  Research inputs
are explicit source-backed observations, arithmetic is deterministic Python,
and every state transition is appended to the governed Nexus store.
"""
from __future__ import annotations
import hashlib, json
from datetime import datetime, timezone
from typing import Any, Dict, List
from nexus_agent_platform.governed import persistence
from .contracts import (assign_work_order, build_goal, build_loop_state,
                        build_work_order, complete_work_order, enforce_budgets,
                        specialist_contract, transition_work_order)

def _now(): return datetime.now(timezone.utc).isoformat()
def _fp(value): return hashlib.sha256(json.dumps(value, sort_keys=True, default=str).encode()).hexdigest()[:20]

SOURCES = [
 {"source":"Sunshine Detailing plans","url":"https://sunshinedetailingaz.com/plans","kind":"competitor_pricing","claims":["Phoenix-area mobile recurring plans are publicly advertised","weekly and biweekly plan prices are published"],"currentness":"observed_2026-09-01","confidence":"SUPPORTED_PROXY"},
 {"source":"Revival Detailing Phoenix","url":"https://revivaldetailing.com/phoenix","kind":"competitor_pricing","claims":["Phoenix mobile package prices and an annual membership are published","Arizona heat/UV is used in service positioning"],"currentness":"observed_2026-09-01","confidence":"SUPPORTED"},
 {"source":"Valley Shine Mobile","url":"https://valleyshinemobile.com/services","kind":"competitor_pricing","claims":["Phoenix mobile package prices, monthly membership, and fleet option are published"],"currentness":"observed_2026-09-01","confidence":"SUPPORTED"},
 {"source":"Washos Maricopa","url":"https://www.washos.com/locations/counties/maricopa/phoenix/","kind":"market_constraints","claims":["Phoenix mobile service and membership offerings are publicly described","provider describes supplying water/power and desert conditions"],"currentness":"observed_2026-09-01","confidence":"SUPPORTED"},
 {"source":"ADOT Vehicle Wash Manual","url":"https://azdot.gov/sites/default/files/media/2020/01/Vehicle-Wash-Manual.pdf","kind":"regulatory_constraint","claims":["wash-water disposal requires compliant sewer or designed onsite handling; local authorization may apply"],"currentness":"published_guidance","confidence":"SUPPORTED"},
]

def economic_model():
    scenarios = {"CONSERVATIVE": (120,2,20,25,30,8,800,600), "BASE": (165,3,22,30,35,10,1200,900), "UPSIDE": (210,4,24,38,40,12,1800,1400)}
    out={}
    for name,(ticket,jobs,days,var,labor,travel,fixed,marketing) in scenarios.items():
        monthly_jobs=jobs*days; revenue=ticket*monthly_jobs; costs=(var+labor+travel)*monthly_jobs+fixed+marketing
        gross_profit=revenue-(var*monthly_jobs); contribution=revenue-((var+labor+travel)*monthly_jobs)
        break_even=max(1, int((fixed+marketing)/(ticket-var-labor-travel))+1)
        out[name]={"average_ticket":ticket,"jobs_per_day":jobs,"working_days":days,"monthly_jobs":monthly_jobs,"monthly_revenue":revenue,"gross_profit":gross_profit,"gross_margin":round(gross_profit/revenue,4),"contribution_margin":round(contribution/revenue,4),"break_even_jobs_per_month":break_even,"estimated_cac_payback_months":"UNPROVEN","total_modeled_costs":costs}
    memberships=[{"name":"monthly maintenance","price":99,"visits_per_month":1,"jobs_per_customer":1,"capacity_note":"fits one monthly slot; route density required"},{"name":"biweekly maintenance","price":179,"visits_per_month":2,"jobs_per_customer":2,"capacity_note":"higher retention potential but consumes two capacity slots"},{"name":"multi-vehicle household","price":299,"visits_per_month":2,"jobs_per_customer":2,"capacity_note":"higher ticket; vehicle count and service scope must be validated"},{"name":"fleet/business package","price":250,"visits_per_month":2,"jobs_per_customer":2,"capacity_note":"requires route density and service-level validation"}]
    return {"scenarios":out,"memberships":memberships,"assumptions":{"source_backed_inputs":["published competitor prices and membership structures"],"model_assumptions":["scenario tickets, capacity, cost inputs are explicit test assumptions"],"user_test_assumptions":["Phoenix-area validation is the scoped test market"]}}

def _append(collection, row): persistence.append_record(collection,row); return row
def _receipt(loop_id, stage, refs, status="PASS"):
    row={"receipt_id":persistence.new_id("bizrcpt"),"loop_id":loop_id,"stage":stage,"status":status,"evidence_refs":refs,"result_fingerprint":_fp({"stage":stage,"refs":refs}),"created_at":_now()}
    return _append("business_receipts",row)
def _save_order(order): return _append("work_orders",order)

def run_mobile_detailing_loop() -> Dict[str,Any]:
    now=_now(); idea_id=persistence.new_id("idea"); goal_id="goal_revenue_opportunities"; loop_id=persistence.new_id("loop")
    idea={"idea_id":idea_id,"title":"Mobile detailing business","description":"Phoenix-area mobile vehicle detailing with one-time, recurring, household, and fleet hypotheses.","source":"Ray business idea / WP8.3","created_at":now,"status":"IDEA_CANDIDATE","research_state":"NOT_STARTED","economic_state":"NOT_STARTED","decision_state":"PENDING","related_work_orders":[],"related_opportunity_id":None}
    _append("business_ideas",idea)
    _append("goals",build_goal(goal_id,owner="NEXUS",title="Identify and validate economically attractive revenue opportunities",target_metric="validated_opportunity",time_horizon="WP8.3"))
    loop=build_loop_state(loop_id,goal_id=goal_id,owner="NEXUS"); loop.update({"loop_type":"MOBILE_DETAILING_BUSINESS","state":"RESEARCH","current_step":"RESEARCH","next_step":"ECONOMIC_TEST","inputs":{"idea_id":idea_id},"updated_at":now}); _append("loop_state",loop)
    alpha=build_work_order(goal_id=goal_id,work_type="research",owner_specialist="ALPHA",loop_id=loop_id,inputs={"idea_id":idea_id,"question":"commercial viability of a mobile detailing business","research_scope":["demand proxies","competitors","pricing","membership","operations","risks"]},cost_budget={"max_usd":0},retry_budget={"max_attempts":2})
    alpha=assign_work_order(alpha,required_capabilities=("web","python")); _save_order(alpha)
    research={"research_id":persistence.new_id("research"),"idea_id":idea_id,"work_order_id":alpha["work_order_id"],"specialist_id":"ALPHA","sources":SOURCES,"topics":{"current_demand":"SUPPORTED_PROXY: active competitor offerings; direct demand/CAC not established","competitors":"SUPPORTED: multiple Phoenix-area providers and packages","pricing":"SUPPORTED: published prices across sources; not a market-wide price survey","membership":"SUPPORTED: recurring plans/memberships/fleet structures exist; retention and capacity unproven","customer_segments":["individual vehicle owners","multi-vehicle households","fleets/businesses"],"operating_requirements":["mobile equipment, water/power logistics, route density, compliant wash-water handling"],"acquisition_channels":["local search, referrals, partnerships; performance not established"],"key_risks":["customer acquisition cost, route density, heat/water constraints, labor capacity, retention"]},"evidence_quality":"PASS","local_market_status":"SUPPORTED_PROXY_NOT_DIRECT_DEMAND","created_at":_now()}
    _append("business_research",research); econ=economic_model(); econ_row={"economic_id":persistence.new_id("econ"),"idea_id":idea_id,"model":econ,"source":"deterministic_python","created_at":_now()}; _append("metrics",econ_row)
    challenge={"status":"PASS","falsifiers":["CAC exceeds contribution margin","route density cannot support travel time","membership frequency exceeds capacity","wash-water compliance cost materially changes unit economics"],"missing_evidence":["direct local demand, CAC, retention, conversion, operational time study"],"dangerous_bottleneck":"capacity/route density under recurring frequency","created_at":_now()}; _append("business_research",{"research_id":persistence.new_id("challenge"),"idea_id":idea_id,"type":"ALPHA_CHALLENGE","result":challenge})
    alpha_result={"status":"PASS","artifact":"research_and_economic_package","research_id":research["research_id"],"evidence_refs":[x["url"] for x in SOURCES],"metrics_ref":econ_row["economic_id"]}; alpha=complete_work_order(alpha,alpha_result,receipt_ref="pending"); alpha["receipt_refs"]=[_receipt(loop_id,"ALPHA_RESEARCH",[research["research_id"],econ_row["economic_id"]])["receipt_id"]]; _save_order(alpha)
    decision={"decision_id":persistence.new_id("decision"),"idea_id":idea_id,"recommendation":"ACCEPT_FOR_VALIDATION","confidence":"MODERATE","rationale":"Paid category and recurring structures are source-supported; direct demand, CAC, retention, and route economics remain unproven.","package":{"what_we_found":"published Phoenix-area competitor pricing/membership evidence and a viable modeled base case","what_we_do_not_know":"direct demand, acquisition economics, retention, operational throughput","economics":econ,"major_assumptions":econ["assumptions"],"risks":challenge["falsifiers"],"membership_assessment":"worth bounded validation; not proven profitable"},"created_at":_now()}; _append("opportunities",{"opportunity_id":persistence.new_id("opp"),"title":"Mobile detailing business","status":"PILOT_PROPOSED","category":"service businesses","source_idea_id":idea_id,"decision":decision,"evidence_refs":[x["url"] for x in SOURCES]}); opp=persistence.latest_record("opportunities"); idea["status"]="OPPORTUNITY_ACCEPT_FOR_VALIDATION"; idea["research_state"]="COMPLETE"; idea["economic_state"]="MODELED"; idea["decision_state"]="PROVISIONAL_VALIDATION_DECISION"; idea["related_opportunity_id"]=opp["opportunity_id"]; _append("business_ideas",idea); _append("audit",{"type":"provisional_executive_decision","idea_id":idea_id,"decision":"ACCEPT_FOR_VALIDATION","external_action_performed":False});
    growth=build_work_order(goal_id=goal_id,work_type="growth_analysis",owner_specialist="GROWTH",loop_id=loop_id,inputs={"opportunity_id":opp["opportunity_id"],"handoff_from":alpha["work_order_id"]}); growth=assign_work_order(growth,required_capabilities=("analytics",)); growth_result={"status":"PASS","offer":{"entry":"mobile interior/exterior detail validation offer","core":"scheduled full detail","upsell":"multi-vehicle/fleet package","membership":"monthly maintenance hypothesis"},"funnel":["TRAFFIC","LEAD","QUALIFICATION","BOOKING","SERVICE","FOLLOW_UP","MEMBERSHIP_REPEAT"],"validation_campaign":{"mode":"draft_only","actions":["landing-page concept","manual interest measurement plan"],"prohibited":["ad spend","publishing","outreach","payments"]},"metrics":["lead rate","booking rate","average ticket","membership interest","CAC","gross margin"]}; _append("business_research",{"research_id":persistence.new_id("growth"),"idea_id":idea_id,"type":"GROWTH_RESULT","result":growth_result}); growth=complete_work_order(growth,growth_result,receipt_ref="pending"); growth["receipt_refs"]=[_receipt(loop_id,"GROWTH_VALIDATION",[opp["opportunity_id"]])["receipt_id"]]; _save_order(growth)
    creative=build_work_order(goal_id=goal_id,work_type="creative_brief",owner_specialist="CREATIVE",loop_id=loop_id,inputs={"opportunity_id":opp["opportunity_id"],"brief":"draft landing-page creative brief; no publishing"}); creative=assign_work_order(creative,required_capabilities=("creative_media",)); cresult={"status":"PASS","artifact":"draft_validation_creative_brief","deliverables":["value proposition concept","package comparison","image/content requirements"],"external_action_performed":False}; creative=complete_work_order(creative,cresult,receipt_ref="pending"); creative["receipt_refs"]=[_receipt(loop_id,"CREATIVE_REQUIREMENTS",[opp["opportunity_id"]])["receipt_id"]]; _save_order(creative)
    launch={"launch_candidate_id":persistence.new_id("launch"),"idea_id":idea_id,"opportunity_id":opp["opportunity_id"],"status":"WAITING_REVIEW","offer":growth_result["offer"],"funnel":growth_result["funnel"],"measurement_plan":growth_result["metrics"],"approval_requirements":["Ray approval before any external validation action"],"external_actions_required":["future governed approval for publishing/spend/outreach"],"not_launched":True,"created_at":_now()}; _append("launch_candidates",launch); _append("outcomes",{"entity_type":"business_loop","entity_id":loop_id,"outcome":"INTERNAL_VALIDATION_READY","business_outcome_proven":False,"metrics_ref":econ_row["economic_id"],"created_at":_now()})
    loop.update({"state":"WAITING_REVIEW","current_step":"LAUNCH_CANDIDATE","next_step":"GOVERNED_VALIDATION","status":"WAITING_REVIEW","outputs":{"idea_id":idea_id,"opportunity_id":opp["opportunity_id"],"launch_candidate_id":launch["launch_candidate_id"]},"receipt_refs":[r["receipt_id"] for r in persistence.read_records("business_receipts") if r.get("loop_id")==loop_id],"updated_at":_now()}); _append("loop_state",loop)
    return {"idea":idea,"goal_id":goal_id,"loop":loop,"research":research,"economics":econ,"challenge":challenge,"decision":decision,"opportunity":opp,"growth":growth_result,"launch":launch,"work_orders":[alpha,growth,creative],"status":"PASS","external_actions":{"ad_spend":False,"publishing":False,"outreach":False,"payments":False,"deployment":False},"cost":{"ai_invocations":0,"tool_calls":5,"research_calls":5,"retries":0}}
