#!/usr/bin/env python3
"""Deterministic first-pass Credit Profile funding-impact analysis."""
from __future__ import annotations
from typing import Any
import re

def _text(*values: Any) -> str:
    return " ".join(str(v or "") for v in values).lower()

def analyze_credit_for_funding_readiness(parse_result: dict[str, Any]) -> dict[str, Any]:
    items: list[dict[str, Any]] = []
    for index, account in enumerate(parse_result.get("accounts") or []):
        haystack = _text(account.get("itemType"), account.get("status"), account.get("paymentStatus"), account.get("negativeCandidateReason"), account.get("notes"))
        util = int(account.get("utilizationPercent") or 0)
        ambiguous = account.get("bureau") in (None, "", "other") or not (account.get("furnisherName") or account.get("accountName"))
        category, reason, issue, impact, next_step = "no_action_suggested", "not_sure", "No immediate funding-impact action detected", "No material impact identified from available fields.", "Keep monitoring."
        docs, evidence, eligible, tier1, tier2 = None, [], False, "none", "none"
        if ambiguous or account.get("confidence") == "low":
            category, reason, issue, impact, next_step = "specialist_exception", "incomplete_information", "Incomplete or ambiguous extracted account information", "Impact cannot be assessed reliably until extraction is confirmed.", "GoClear should compare this item with the source report."
            evidence, tier1, tier2 = ["Current credit report page showing the complete item"], "medium", "medium"
        elif util >= 30 or "utilization" in haystack:
            category, issue, impact, next_step = "utilization_impact", f"Reported utilization is {util}%" if util else "Utilization information needs review", "Higher revolving utilization may weaken lender readiness.", "Review payoff timing, balance reduction, and statement-date options."
            tier1, tier2 = ("high" if util >= 70 else "medium"), "medium"
        elif re.search(r"collection|charge.?off|90 day|60 day|30 day|late", haystack):
            category, reason, issue, impact, next_step = "high_funding_impact", ("paid_or_settled_status_review" if "paid" in haystack or "settled" in haystack else "payment_status_review"), "Major derogatory or payment-status indicator detected", "This reported status may materially affect Tier 1 and Tier 2 readiness.", "Confirm facts and gather records before choosing an action."
            docs, evidence, eligible, tier1, tier2 = "Possible dispute/documentation option only if reporting appears inaccurate, outdated, incomplete, or unverifiable.", ["Statements, payment records, settlement records, or bureau correspondence"], True, "high", "high"
        elif "duplicate" in haystack:
            category, reason, issue, impact, next_step = "report_item_review", "duplicate_possible", "Possible duplicate reporting indicator detected", "Duplicate reporting may overstate obligations or negative history.", "Compare bureau, furnisher, dates, and masked account references."
            docs, evidence, eligible, tier1, tier2 = "Possible dispute/documentation option if entries represent the same obligation.", ["Report pages showing both entries"], True, "medium", "medium"
        items.append({"id": f"account_{account.get('bureau') or 'other'}_{index+1}", "creditorFurnisher": account.get("furnisherName") or account.get("accountName") or "Unknown furnisher", "maskedAccountReference": account.get("accountNumberMasked") or "Not available", "bureau": account.get("bureau") or "other", "category": category, "reason": reason, "issueDetected": issue, "fundingImpact": impact, "suggestedNextStep": next_step, "possibleDocumentationOption": docs, "confidence": account.get("confidence") or "low", "explanation": "Deterministic classification; not factual verification.", "clientEvidenceNeeded": evidence, "specialistReviewRequired": category != "no_action_suggested", "tier1Impact": tier1, "tier2Impact": tier2, "letterEligible": eligible})
    for index, inquiry in enumerate(parse_result.get("inquiries") or []):
        items.append({"id": f"inquiry_{index+1}", "creditorFurnisher": inquiry.get("company") or "Unknown inquiry", "maskedAccountReference": "Not applicable", "bureau": inquiry.get("bureau") or "other", "category": "specialist_exception" if inquiry.get("confidence") == "low" else "inquiry_review", "reason": "unauthorized_inquiry_possible", "issueDetected": "Recent inquiry detected for client review", "fundingImpact": "Recent hard inquiries may affect some funding evaluations.", "suggestedNextStep": "Confirm whether the inquiry is familiar and authorized.", "possibleDocumentationOption": "Possible dispute/documentation option only if unfamiliar or lacking permissible purpose.", "confidence": inquiry.get("confidence") or "low", "explanation": "Detection is not verification that an inquiry was unauthorized.", "clientEvidenceNeeded": ["Client confirmation and any application records"], "specialistReviewRequired": True, "tier1Impact": "medium", "tier2Impact": "low", "letterEligible": True})
    for index, variation in enumerate(parse_result.get("personalInfoVariations") or []):
        items.append({"id": f"personal_{index+1}", "creditorFurnisher": "Personal information", "maskedAccountReference": "Not applicable", "bureau": variation.get("bureau") or "other", "category": "specialist_exception" if variation.get("confidence") == "low" else "personal_info_review", "reason": "personal_information_mismatch", "issueDetected": f"{variation.get('field') or 'Personal information'} variation detected", "fundingImpact": "Identity or address inconsistencies can delay documentation review.", "suggestedNextStep": "Compare the entry with current identity and address documents.", "possibleDocumentationOption": "Possible documentation option if outdated, unfamiliar, or inaccurate.", "confidence": variation.get("confidence") or "low", "explanation": "A parsed variation is not a verified error.", "clientEvidenceNeeded": ["Government ID or proof of address, with sensitive fields redacted"], "specialistReviewRequired": True, "tier1Impact": "low", "tier2Impact": "low", "letterEligible": True})
    by = lambda category: [item for item in items if item["category"] == category]
    blockers = [item for item in items if item["tier1Impact"] in ("high", "medium")]
    status = "insufficient_information" if not parse_result.get("accounts") else "action_needed" if any(i["tier1Impact"] == "high" for i in blockers) else "almost_ready" if blockers else "ready_to_review"
    return {"creditProfileStatus": status, "summary": {"accountsAnalyzed": len(parse_result.get("accounts") or []), "fundingImpactCount": len([i for i in items if i["category"] != "no_action_suggested"]), "creditProfileStatus": status}, "fundingImpactItems": [i for i in items if i["category"] != "no_action_suggested"], "utilizationActions": by("utilization_impact"), "reportItemReviews": by("report_item_review") + by("high_funding_impact"), "inquiryReviews": by("inquiry_review"), "personalInfoReviews": by("personal_info_review"), "evidenceNeeded": [i for i in items if i["clientEvidenceNeeded"]], "specialistExceptions": by("specialist_exception"), "noActionItems": by("no_action_suggested"), "recommendedNextSteps": ["Confirm high-impact recommendations", "Review utilization actions", "Request only needed evidence"], "confidenceSummary": {"overall": parse_result.get("confidence") or "low", "lowConfidenceItems": len([i for i in items if i["confidence"] == "low"]), "warnings": len(parse_result.get("warnings") or [])}, "tier1Impact": {"blockerCount": len(blockers)}, "tier2Impact": {"blockerCount": len([i for i in items if i["tier2Impact"] in ("high", "medium")])}, "needsSpecialistReview": True}
