const content = document.getElementById('content')
const shell = document.getElementById('appShell')
const title = document.getElementById('pageTitle')
const crumb = document.getElementById('crumb')
const toast = document.getElementById('toast')
let area = 'command'
let screen = 'command'
let agent = 'Hermes'
let voiceIndex = 0

const voiceStates = ['IDLE', 'LISTENING', 'LIVE TRANSCRIPT', 'TRANSCRIPT READY', 'EDITING', 'THINKING', 'AGENT RESPONSE']
const agents = {
  Hermes: { role: 'Operator · COO · Chief of Staff', orb: '', tone: '', prompt: 'Ask Hermes what matters next...', response: 'The highest-priority item is the client live-data dependency. I can prepare the governed next step once the evidence is confirmed.' },
  Nova: { role: 'Strategic Adviser · Critic', orb: 'N', tone: 'nova', prompt: 'Ask Nova for a strategic challenge...', response: 'The risk is treating readiness as a checklist rather than a sequence of proof. I would validate the dependency before adding more surface area.' },
  Alpha: { role: 'Research · Evidence · Market Intelligence', orb: 'A', tone: 'alpha', prompt: 'Ask Alpha to research or compare...', response: 'I would separate verified evidence from inference, then attach the strongest sources to the decision before recommending a path.' },
}

function pill(text, tone='') { return `<span class="pill ${tone}">${text}</span>` }
function header(kicker, h, copy='') { return `<div class="hero"><div><div class="eyebrow blue">${kicker}</div><h2>${h}</h2><p>${copy}</p></div></div>` }
function card(titleText, body, cls='') { return `<section class="card ${cls}"><h3>${titleText}</h3>${body}</section>` }
function attention(titleText, sub, tone='') { return `<li class="attention-item"><span class="attention-mark ${tone}"></span><div><div class="item-title">${titleText}</div><div class="item-sub">${sub}</div></div><span class="number">›</span></li>` }
function composer() {
  const data = agents[agent]
  return `<div class="composer" id="composer"><div class="composer-top"><select class="agent-select" id="agentSelect" aria-label="Select agent"><option>Hermes</option><option>Nova</option><option>Alpha</option></select><span class="context-chip">Context: prototype work item ×</span></div><textarea id="composerText" placeholder="${data.prompt}" aria-label="Message ${agent}"></textarea><div class="composer-status" id="composerStatus"></div><div class="composer-actions"><div class="composer-actions-left"><button class="composer-btn" title="Attach file" aria-label="Attach file">⌕</button><button class="composer-btn mic" id="micButton" title="Microphone" aria-label="Microphone">◉</button><span class="small muted" id="voiceState">${voiceStates[voiceIndex]}</span></div><button class="composer-btn primary" id="sendButton">Send ↑</button></div></div>`
}
function agentHead(name=agent) { const a=agents[name]; return `<div class="agent-head"><div class="agent-orb ${a.tone}">${a.orb || 'N'}</div><div><h3>${name}</h3><div class="small muted">${a.role}</div></div></div>` }
function conversation(name) {
  agent = name
  const a=agents[name]
  const contentBlock = name==='Alpha' ? `<div class="source-line"><strong>Evidence attached</strong> · 3 sample sources · FACT / INFERENCE separated</div>` : name==='Nova' ? `<div class="source-line"><strong>Advice only</strong> · No execution path attached</div>` : `<div class="source-line"><strong>Operating context</strong> · Governed next steps remain explicit</div>`
  return `${header(name.toUpperCase(), `${name} conversation`, a.role)}<div class="conversation"><div class="conversation-head">${agentHead(name)}${pill(name==='Hermes'?'Operator path':name==='Nova'?'Advice only':'Research only', name==='Alpha'?'green':'blue')}</div><div class="message agent">${name==='Hermes'?'I have the current work context. What would you like to understand or move forward?':name==='Nova'?'Bring me a decision, plan, or assumption and I will challenge it.':'Bring me a question that needs evidence. I will separate fact, inference, and recommendation.'}${contentBlock}</div><div class="message user">Good evening, ${name}. What deserves attention?</div>${composer()}</div>`
}
function command() {
 return `${header('COMMAND', 'Good afternoon, Ray.', 'A calm brief of what matters, what changed, and where your attention is needed.')}<div class="screen-note">Sample state · values are illustrative only. Connected systems should replace these with canonical truth states.</div><div class="command-grid">${card('Needs You <span class="pill amber">3</span>', `<ul class="list">${attention('Synthetic customer approval','Ray Review · evidence attached')}${attention('Readiness campaign review','Creative artifact · awaiting decision')}${attention('Strategic decision','Nova note · recommendation pending')}</ul>`)}${card('Today', `<div class="priority"><b class="priority-num">1</b><div><div class="item-title">Verify client live-data path</div><div class="item-sub">Sample priority · source: Operating Context</div></div></div><div class="priority"><b class="priority-num">2</b><div><div class="item-title">Complete synthetic validation</div><div class="item-sub">Sample blocker · measurement pending</div></div></div><div class="priority"><b class="priority-num">3</b><div><div class="item-title">Move readiness revenue path forward</div><div class="item-sub">Sample context · not a live metric</div></div></div>`)}${card('Business', `<div class="statline"><span>Revenue truth</span>${pill('UNKNOWN','amber')}</div><div class="statline"><span>Opportunities</span>${pill('Connected','green')}</div><div class="statline"><span>Clients</span>${pill('Not connected','amber')}</div><div class="statline"><span>Growth</span>${pill('Pending','blue')}</div>`)}</div><div class="section-label" style="margin-top:26px">Working now <a>View Work →</a></div><div class="activity-strip"><div class="activity-tile"><strong>Hermes</strong><span>${pill('Running','blue')} Client verification</span></div><div class="activity-tile"><strong>Alpha</strong><span>${pill('Researching','green')} Funding evidence</span></div><div class="activity-tile"><strong>Creative</strong><span>${pill('Complete','green')} Readiness concept</span></div><div class="activity-tile"><strong>Nexus</strong><span>${pill('Scheduled','blue')} Evening cycle</span></div></div>${composer()}`
}
function work() { return `${header('WORK', 'What is Nexus doing?', 'One human-readable queue over work, approvals, receipts, and outputs.')}<div class="filterbar">${['Needs You','Running','Scheduled','Completed','Failed','Approvals','All'].map((x,i)=>`<button class="filter ${i===0?'active':''}">${x}</button>`).join('')}</div><div class="work-layout">${card('Needs You', `<div class="work-row"><div><div class="item-title">Client Live Data Verification</div><div class="item-sub">Hermes · recommendation generated · evidence attached</div></div><div class="right">${pill('Needs You','amber')}<div class="small muted">Updated 18m ago</div></div></div><div class="work-row"><div><div class="item-title">Readiness campaign review</div><div class="item-sub">Creative · artifact ready for review</div></div><div class="right">${pill('Review','violet')}<div class="small muted">Updated today</div></div></div><div class="work-row"><div><div class="item-title">Funding market comparison</div><div class="item-sub">Alpha · source synthesis pending</div></div><div class="right">${pill('Waiting','blue')}<div class="small muted">Updated today</div></div></div>`, 'flush')}${card('Attention summary', `<div class="metric">3</div><p class="small muted">Items need a decision or review. No additional urgency is implied by sample ordering.</p><div class="statline"><span>Running</span><b>2 sample</b></div><div class="statline"><span>Failed</span><b>UNKNOWN</b></div><div class="statline"><span>Receipts</span><b>Available</b></div>`)}</div>` }
function detail() { return `${header('WORK ITEM', 'Client Live Data Verification', 'Sample detail thread · the presentation model does not create a new work store.')}<div class="detail-layout">${card('Work thread', `<div class="timeline-event"><span class="timeline-dot"></span><div><strong>Hermes started work</strong><p>Operating context requested a verification pass.</p></div></div><div class="timeline-event"><span class="timeline-dot"></span><div><strong>Supabase checked</strong><p>Source response attached as a sample receipt.</p></div></div><div class="timeline-event"><span class="timeline-dot"></span><div><strong>Dependency identified</strong><p>Client live-data flag remains the blocking condition.</p></div></div><div class="timeline-event"><span class="timeline-dot"></span><div><strong>Recommendation generated</strong><p>Needs Ray · approval boundary preserved.</p></div></div>`, 'flush')}${card('Next step', `<p class="item-title">Review the evidence and choose a governed next step.</p><div class="statline"><span>Source</span><b>Operating Context</b></div><div class="statline"><span>Risk</span><b>Measurement unknown</b></div><div class="statline"><span>Unlocks</span><b>Readiness validation</b></div><button class="composer-btn primary" style="margin-top:14px">Open Ray Review</button><button class="composer-btn" style="margin:14px 0 0 6px">View Evidence</button>`)}</div>` }
function agentsHub() { return `${header('AGENTS', 'Three roles. One operating system.', 'Choose who to talk to without merging their brains, memory, or authority.')}<div class="grid grid-3"><div class="card agent-card">${agentHead('Hermes')}<p>Operator, COO, and chief of staff. Turns current operating truth into priorities and governed next steps.</p><div class="agent-foot">${pill('Active','blue')}<span class="small muted">Client verification</span></div></div><div class="card agent-card">${agentHead('Nova')}<p>Strategic adviser and critic. Challenges plans, compares alternatives, and gives a second opinion.</p><div class="agent-foot">${pill('Available','violet')}<span class="small muted">Strategy critique</span></div></div><div class="card agent-card">${agentHead('Alpha')}<p>Research and evidence intelligence. Investigates markets, sources claims, and creates research artifacts.</p><div class="agent-foot">${pill('Available','green')}<span class="small muted">Funding research</span></div></div></div><div class="section-label" style="margin-top:28px">Recent outputs</div><div class="grid grid-2"><div class="artifact"><div class="artifact-icon">▤</div><div><strong>Operating priority brief</strong><small>Hermes · sample artifact · source-backed</small></div></div><div class="artifact"><div class="artifact-icon">◒</div><div><strong>Funding market comparison</strong><small>Alpha · sample artifact · research pending</small></div></div></div>` }
function business() { return `${header('BUSINESS', 'How is GoClear doing?', 'Business context grouped around decisions and readiness—not internal workflow stages.')}<div class="grid grid-3"><div class="card"><div class="section-label">Revenue truth</div><div class="metric">UNKNOWN</div><p class="small muted">No fabricated zero. Measurement source pending.</p></div><div class="card"><div class="section-label">Opportunities</div><div class="metric">26</div><p class="small muted">Sample connected value · verify against Opportunity Engine.</p></div><div class="card"><div class="section-label">Clients</div><div class="metric">NOT CONNECTED</div><p class="small muted">Client source is not represented as live in this prototype.</p></div></div><div class="card flush" style="margin-top:16px"><div class="section-label" style="padding:20px 20px 0">Readiness journey <a>Open Business →</a></div><div class="table-row head"><span>Area</span><span>Status</span><span>Next step</span><span>Source</span></div><div class="table-row"><span>Credit & Funding</span><span>${pill('In progress','blue')}</span><span>Review profile</span><span>Client workflow</span></div><div class="table-row"><span>Bankability</span><span>${pill('Pending','amber')}</span><span>Collect evidence</span><span>Readiness</span></div><div class="table-row"><span>Growth</span><span>${pill('UNKNOWN','amber')}</span><span>Connect source</span><span>Growth Ops</span></div></div>` }
function studio() { return `${header('STUDIO', 'What has Nexus produced?', 'Research, creative, campaigns, and reports organized as useful outputs.')}<div class="grid grid-2"><div class="card"><div class="section-label">Research <a>Open Research →</a></div><div class="artifact"><div class="artifact-icon">⌕</div><div><strong>Funding market comparison</strong><small>${pill('Evidence pending','amber')} · Alpha · 3 sample sources</small></div></div><div class="artifact" style="margin-top:10px"><div class="artifact-icon">▤</div><div><strong>Competitor signal brief</strong><small>${pill('Ready','green')} · Alpha · source-backed</small></div></div></div><div class="card"><div class="section-label">Creative <a>Open Creative →</a></div><div class="artifact"><div class="artifact-icon">✦</div><div><strong>Readiness campaign concept</strong><small>${pill('Needs review','violet')} · Creative Intelligence</small></div></div><div class="artifact" style="margin-top:10px"><div class="artifact-icon">▣</div><div><strong>Remotion storyboard</strong><small>${pill('Evaluation only','amber')} · render artifact</small></div></div></div></div><div class="card" style="margin-top:16px"><div class="section-label">Artifact principle</div><p class="item-title">Conversations produce outputs that can be reopened, sourced, reviewed, and handed off.</p><p class="small muted">GPU creative generation is shown as DEFERRED_PROVIDER_CAPACITY when unavailable—not broken.</p></div>` }
function system() { return `${header('SYSTEM', 'Is the Nexus machinery working?', 'Technical truth is available here without dominating the operating experience.')}<div class="grid grid-3"><div class="card"><div class="section-label">Core</div><div class="metric">Healthy</div><p class="small muted">Sample state · Mission Control remains canonical.</p></div><div class="card"><div class="section-label">Capabilities</div><div class="metric">2 deferred</div><p class="small muted">GPU and one integration need explicit explanation.</p></div><div class="card"><div class="section-label">Costs</div><div class="metric">UNKNOWN</div><p class="small muted">No source, no zero.</p></div></div><div class="card" style="margin-top:16px"><div class="section-label">Runtime overview <a>Open diagnostics →</a></div><div class="statline"><span>Voice transport</span>${pill('Healthy','green')}</div><div class="statline"><span>Nova Telegram</span>${pill('Healthy','green')}</div><div class="statline"><span>GPU creative worker</span>${pill('Deferred','amber')}</div><div class="statline"><span>Last Mission Control heartbeat</span><b>Sample · 4m ago</b></div></div>` }
function client(type) {
 const steps=['Welcome','Credit','Foundation','Bankability','Readiness','Next step']; const current=type==='welcome'?0:type==='credit'?1:type==='foundation'?2:type==='funding'?4:type==='upload'?4:type==='recommendations'?5:3
 const journey=`<div class="journey">${steps.map((s,i)=>`<div class="journey-step ${i<=current?'active':''}"><span>${i<current?'✓':i+1}</span><div>${s}</div></div>`).join('')}</div>`
 if(type==='welcome') return `${header('GO CLEAR / WELCOME', 'Let’s get you funding ready.', 'A guided starting point for your next best step.')}<div class="card" style="max-width:700px;margin:auto;text-align:center;padding:42px 25px"><div class="eyebrow blue">STEP 1 OF 5</div><h2 style="font-size:27px">Tell us where you are today.</h2><p class="muted">Your answers help GoClear show what is missing, what can be reviewed, and what to do next.</p><button class="composer-btn primary" style="margin-top:16px">Start My Readiness Review →</button><p class="small muted" style="margin-top:20px">No readiness score is shown until the required source information exists.</p></div>`
 if(type==='upload') return `${header('FUNDING READINESS', 'Add the evidence beside the task.', 'Inline upload keeps the journey moving.')} ${journey}<div class="grid grid-2"><div class="card"><div class="section-label">Bank statements <span class="pill amber">Needed</span></div><p class="item-title">Upload the latest statements for review.</p><p class="small muted">Category: Funding readiness · Tenant-scoped storage · Sample fixture only</p><div class="upload-zone"><strong>Drop a document here</strong><p>PDF, JPG, or PNG · maximum shown by live policy</p><button>Choose file</button></div></div><div class="card"><div class="section-label">Documents <span class="pill blue">Central library</span></div><div class="statline"><span>Credit report</span>${pill('Reviewed','green')}</div><div class="statline"><span>EIN letter</span>${pill('Processing','blue')}</div><div class="statline"><span>Bank statement</span>${pill('Needs upload','amber')}</div></div></div>`
 const titleMap={home:'Your readiness journey',credit:'Credit profile',foundation:'Business foundation',funding:'Funding readiness',recommendations:'Your next best steps'}
 const body=type==='recommendations'?`<div class="card"><div class="section-label">Recommended next steps</div><div class="priority"><b class="priority-num">1</b><div><div class="item-title">Upload the missing bank statements</div><div class="item-sub">This lets GoClear review the funding-readiness factor.</div></div></div><div class="priority"><b class="priority-num">2</b><div><div class="item-title">Review your business foundation</div><div class="item-sub">One item is still processing.</div></div></div><div class="priority"><b class="priority-num">3</b><div><div class="item-title">Request a GoClear review</div><div class="item-sub">Available after required evidence is received.</div></div></div></div>`:`<div class="grid grid-2"><div class="card"><div class="section-label">Current status</div><div class="metric">${type==='credit'?'In progress':type==='funding'?'Measurement pending':'Step '+(current+1)+' of 5'}</div><p class="small muted">This sample state is intentionally not a funding approval or score.</p><button class="composer-btn primary">Continue →</button></div><div class="card"><div class="section-label">What is missing?</div><div class="statline"><span>Profile answers</span>${pill('Received','green')}</div><div class="statline"><span>Credit report</span>${pill('Reviewed','green')}</div><div class="statline"><span>Bank statements</span>${pill('Needed','amber')}</div><div class="statline"><span>GoClear review</span>${pill('Not started','blue')}</div></div></div>`
 return `${header('GO CLEAR / '+type.toUpperCase(),titleMap[type]||'Client home','A clear next step, with progress and document states visible.')} ${journey}${body}`
}
function render() {
 let html
 if(screen==='command') html=command(); else if(screen==='work') html=work(); else if(screen==='detail') html=detail(); else if(screen==='agents') html=agentsHub(); else if(screen==='hermes') html=conversation('Hermes'); else if(screen==='nova') html=conversation('Nova'); else if(screen==='alpha') html=conversation('Alpha'); else if(screen==='business') html=business(); else if(screen==='studio') html=studio(); else if(screen==='system') html=system(); else html=client(screen)
 content.innerHTML=html
 title.textContent=screen==='command'?'Command':screen==='detail'?'Work item detail':screen==='hermes'?'Hermes':screen==='nova'?'Nova':screen==='alpha'?'Alpha':screen.startsWith('client')||['welcome','home','credit','foundation','funding','upload','recommendations'].includes(screen)?'GoClear Client':screen[0].toUpperCase()+screen.slice(1)
 crumb.textContent=screen.toUpperCase()
 bind()
}
function bind() {
 const screenSelect=document.getElementById('screenSelect'); if(screenSelect){screenSelect.value=screen;screenSelect.addEventListener('change',e=>{screen=e.target.value;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.area===screen));render()})}
 const select=document.getElementById('agentSelect'); if(select){select.value=agent;select.addEventListener('change',e=>{agent=e.target.value;showToast(`${agent} selected · canonical route remains separate`);render()})}
 const mic=document.getElementById('micButton'); if(mic) mic.addEventListener('click',()=>{voiceIndex=(voiceIndex+1)%voiceStates.length;const state=document.getElementById('voiceState');const status=document.getElementById('composerStatus');if(state)state.textContent=voiceStates[voiceIndex];if(status){status.textContent=voiceStates[voiceIndex]==='LIVE TRANSCRIPT'?'Listening · “Nexus what should I...”':voiceStates[voiceIndex]==='TRANSCRIPT READY'?'Transcript ready · review before Send':' ';status.classList.toggle('show',['LIVE TRANSCRIPT','TRANSCRIPT READY','EDITING'].includes(voiceStates[voiceIndex]))}showToast(`Voice state: ${voiceStates[voiceIndex]} · sample interaction`)})
 const send=document.getElementById('sendButton'); if(send) send.addEventListener('click',()=>{const text=document.getElementById('composerText');if(!text.value.trim())text.value='Nexus, what should I focus on today?';showToast(`${agent} receives only after explicit Send · prototype`);})
 document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active')}))
}
function showToast(text){toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2500)}
document.querySelectorAll('.nav-item').forEach(button=>button.addEventListener('click',()=>{area=button.dataset.area;screen=area;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x===button));render()}))
document.getElementById('phoneToggle').addEventListener('click',()=>{shell.classList.toggle('phone-mode');showToast(shell.classList.contains('phone-mode')?'Phone preview: 390px':'Desktop preview')})
// Review-friendly screen switcher: keyboard shortcuts expose every required prototype screen.
document.addEventListener('keydown',e=>{if(e.key==='1')screen='command';if(e.key==='2')screen='work';if(e.key==='3')screen='detail';if(e.key==='4')screen='agents';if(e.key==='5')screen='hermes';if(e.key==='6')screen='nova';if(e.key==='7')screen='alpha';if(e.key==='8')screen='business';if(e.key==='9')screen='studio';if(e.key==='0')screen='system';if(e.key==='c')screen='welcome';if(e.key==='h')screen='home';if(e.key==='r')screen='recommendations';if(e.key==='u')screen='upload';if(['1','2','3','4','5','6','7','8','9','0','c','h','r','u'].includes(e.key))render()})
render()
