#!/usr/bin/env python3
from __future__ import annotations
import argparse,json,subprocess
from same_day_common import ROOT,RUNTIME,SUPABASE_READY,now,read_json,write_json,write_report
def load(stem):return read_json(RUNTIME/f"{stem}_latest.json",{})
def card(i,title,decision,risk="medium"):
 return {"id":i,"tenant_id":"tenant_test_goclear","client_id":"client_test_julius_erving","category":"walkaway_approval","title":title,"status":"pending_Ray_review","priority":"high","risk_level":risk,"automation_level":"approval_required","client_visible":False,"approval_required":True,"exact_decision_needed":decision,"options":["approve","reject","defer"],"external_action_performed":False,"created_at":now()}
def build():
 checkout=load("stripe_test_checkout_session");intent=load("stripe_test_payment_intent");endpoint=load("stripe_webhook_endpoint");webhook=load("stripe_webhook_test_execution_plan");onboarding=load("payment_to_customer_onboarding_dry_run");schema=load("production_schema_readonly_verification");rls=load("production_rls_policy_inspection");rollback=load("synthetic_rollback_transaction_test");gate=load("persistent_fake_customer_insert_gate");frontend=load("frontend_live_data_readiness");resend=load("resend_connection_audit");email=load("onboarding_email_draft");youtube=load("youtube_review_proof");transcript=load("youtube_transcript_import");notebook=load("notebooklm_legacy_adapter_recovery");notebook_import=load("notebooklm_source_import");oanda=load("oanda_demo_verification_plan");trading=load("vibe_paper_backtest_recovery");loop=load("automation_schedule_registry")
 metadata=read_json(SUPABASE_READY/"youtube_video_metadata_latest.json",[]);video=next((x for x in metadata if x.get("video_id")=="zbAmmnMh5ew"),{});probe=read_json(SUPABASE_READY/"youtube_subtitle_availability_latest.json",[]);video_probe=next((x for x in probe if x.get("video_id")=="zbAmmnMh5ew"),{})
 target={"ok":bool(video),"generated_at":now(),"status":"approved_video_metadata_reviewed" if video else "approved_video_metadata_missing","video_id":"zbAmmnMh5ew","title":video.get("title"),"api_metadata_available":video.get("metadata_source")=="youtube_data_api_v3","ytdlp_probe_recorded":bool(video_probe),"subtitle_languages":video_probe.get("manual_subtitle_languages",[]),"automatic_caption_languages":video_probe.get("automatic_caption_languages",[]),"transcript_imported":False,"video_downloaded":False,"audio_downloaded":False,"cookies_used":False,"external_action_performed":False}
 write_report("youtube_approved_video_target","YouTube Approved Video Target",target)
 youtube_full={"ok":youtube.get("ok",False),"generated_at":now(),"status":youtube.get("review_mode"),"approved_targets":5,"reviewed_items":youtube.get("reviewed_items_count",0),"approved_video":target,"transcripts_imported":transcript.get("transcripts_imported",0),"next_instruction":transcript.get("next_required_action"),"external_action_performed":False};write_report("youtube_full_engine","YouTube Full Engine",youtube_full)
 safe_runs=loop.get("loop_safe_executed",[]);safe_loop={"ok":bool(safe_runs) and all(x.get("passed") for x in safe_runs),"generated_at":now(),"status":"bounded_safe_loop_complete","jobs_attempted":len(safe_runs),"jobs_passed":sum(x.get("passed") for x in safe_runs),"jobs":safe_runs,"permanent_daemon_installed":False,"emails_sent":False,"social_posts_published":False,"disputes_sent":False,"database_inserted":False,"trading_orders_placed":False,"external_action_performed":False};write_report("safe_loop_run","Safe Loop Run",safe_loop,{"Jobs":safe_runs})
 cards=[card("walkaway-stripe-checkout","Approve completing Stripe test Checkout manually","Use Stripe test card only; do not use live mode.","high"),card("walkaway-stripe-webhook","Approve Stripe webhook listener test","Run local server/listener and Stripe synthetic triggers; never print/commit the signing secret.","high"),card("walkaway-stripe-intent","Approve Stripe PaymentIntent confirmation using Stripe test method","Use pm_card_visa only in test mode.","high"),card("walkaway-fake-insert","Approve persistent fake customer Supabase insertion","Blocked until direct RLS verification and guaranteed rollback pass.","high"),card("walkaway-client-live-read","Approve /client/dashboard live Supabase read for fake customer","Enable feature flag only after insert/RLS proof.","high"),card("walkaway-resend-test","Approve Resend test email to Ray","Blocked until HTTP 403/domain verification is resolved.","high"),card("walkaway-email-draft","Approve onboarding email draft for test customer","Approve draft content only; sending remains separate."),card("walkaway-youtube-transcript","Approve YouTube transcript import if transcript file is added","User-provided approved TXT only."),card("walkaway-notebooklm","Approve NotebookLM selected notebook import workflow","Manual exports only; no consumer browser automation."),card("walkaway-oanda-demo","Approve Oanda demo connection check with no orders","Require explicit practice environment first.","high"),card("walkaway-vibe-paper","Approve Vibe/paper backtest adapter test","Bounded historical backtest only; no broker credentials."),card("walkaway-safe-loop","Approve safe bounded internal automation loop schedule","Keep all external actions disabled.")]
 write_json(SUPABASE_READY/"walkaway_ray_review_cards_latest.json",cards);write_report("walkaway_ray_review_cards","Walk-Away Ray Review Cards",{"ok":True,"generated_at":now(),"status":"ready_for_Ray_review","cards_created":len(cards),"external_action_performed":False},{"Cards":cards})
 recommendations=["Run the Stripe listener test next; the local signature verifier already passed its bounded fixture.","Do not insert the fake customer until direct RLS inspection and guaranteed rollback pass.","Resolve Resend HTTP 403 and sender-domain verification before any test send.","Add one approved TXT transcript for the new YouTube video.","Use the recovered NotebookLM wrapper only for manual selected exports.","Set explicit OANDA_ENVIRONMENT=practice before a read-only demo check.","Keep Vibe recovery paper/backtest-only and preserve the eight-job bounded loop."]
 hermes={"ok":True,"generated_at":now(),"status":"walkaway_brief_ready","recommendations":recommendations,"recommendations_count":len(recommendations),"next_action":"Approve Stripe webhook listener test, then prove checkout event handling before any persistent test-client insert.","external_action_performed":False};write_report("hermes_walkaway_activation_brief","Hermes Walk-Away Activation Brief",hermes,{"Recommendations":recommendations})
 status={"ok":True,"generated_at":now(),"stripe_checkout":checkout.get("status"),"stripe_payment_intent":intent.get("status"),"stripe_webhook":"local_fixture_verified_listener_not_started","payment_onboarding":onboarding.get("status"),"persistent_fake_customer_gate":gate.get("status"),"frontend_live_data":frontend.get("status"),"resend":resend.get("status"),"email_draft":email.get("status"),"youtube_video_target":target.get("status"),"youtube_transcript":transcript.get("status"),"notebooklm":notebook.get("status"),"oanda":oanda.get("status"),"vibe_paper":trading.get("status"),"safe_loop":safe_loop.get("status"),"next_approvals":[x["title"] for x in cards],"external_action_performed":False};write_report("walkaway_frontend_status","Walk-Away Frontend Status",status)
 branch=subprocess.run(["git","branch","--show-current"],cwd=ROOT,capture_output=True,text=True).stdout.strip();baseline={"ok":True,"generated_at":now(),"build_start_passed":True,"branch":branch,"start_clean":True,"start_commit":"56e9ee1","external_action_performed":False};write_report("walkaway_activation_baseline","Walk-Away Activation Baseline",baseline)
 master={"ok":True,"generated_at":now(),"build_start_result":"passed","stripe_webhook_endpoint_implemented":endpoint.get("ok",False),"stripe_listener_ready":webhook.get("listener_ready",False),"stripe_trigger_attempted":webhook.get("trigger_attempted",False),"local_signed_fixture_received":endpoint.get("event_received",False),"checkout_status":checkout.get("status"),"payment_intent_status":intent.get("payment_intent_status"),"payment_onboarding_dry_run_status":onboarding.get("status"),"persistent_database_insert":False,"rls_verification_result":rls.get("status"),"schema_verification_result":schema.get("status"),"synthetic_rollback_result":rollback.get("status"),"persistent_fake_customer_gate":gate.get("status"),"frontend_live_data_readiness":frontend.get("status"),"resend_connected":resend.get("ok",False),"resend_status":resend.get("status"),"email_sent":False,"email_draft_created":email.get("ok",False),"youtube_video_target_added":bool(video),"youtube_metadata_probe_result":target.get("status"),"youtube_transcript_imported":transcript.get("transcripts_imported",0)>0,"notebooklm_adapter_recovered":notebook.get("ok",False),"notebooklm_sources_imported":notebook_import.get("sources_imported",0),"oanda_demo_verified":oanda.get("practice_environment_verified",False),"oanda_orders_placed":False,"vibe_cli_installed":False,"vibe_paper_adapter_recovered":trading.get("ok",False),"safe_automation_loop_run":safe_loop.get("ok",False),"external_actions_performed":False,"readonly_external_checks_performed":True,"real_charge_made":False,"social_posts_published":False,"disputes_sent":False,"live_trades_placed":False,"ray_review_cards":len(cards),"hermes_recommendations_count":len(recommendations),"what_Ray_should_approve_next":"Stripe webhook listener test using the implemented local signature verifier.","exact_next_command":"stripe listen --forward-to localhost:8787/api/stripe/webhook"};write_report("walkaway_activation_master","Walk-Away Activation Master",master);return master
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--json",action="store_true");a=p.parse_args();r=build();print(json.dumps(r,indent=2) if a.json else r)
