#!/usr/bin/env python3
from __future__ import annotations
import argparse,json,subprocess
from same_day_common import ROOT,RUNTIME,SUPABASE_READY,now,read_json,write_json,write_report
def load(stem):return read_json(RUNTIME/f"{stem}_latest.json",{})
def card(i,title,decision,risk="medium"):
 return {"id":i,"tenant_id":"tenant_test_goclear","client_id":"client_test_julius_erving","category":"all_blockers_approval","title":title,"status":"pending_Ray_review","priority":"high","risk_level":risk,"automation_level":"approval_required","client_visible":False,"approval_required":True,"exact_decision_needed":decision,"options":["approve","reject","defer"],"external_action_performed":False,"created_at":now()}
def build():
 listener=load("stripe_listener_test");trigger=load("stripe_webhook_trigger_results");checkout=load("stripe_test_checkout_session");intent=load("stripe_test_payment_intent");webhook_flow=load("webhook_to_customer_onboarding_dry_run");resend=load("resend_403_diagnosis");resend_fix=load("resend_fix_packet");rls=load("rls_static_verification");rls_packet=load("rls_sql_editor_verification_packet");gate=load("persistent_fake_customer_insert_gate");cleanup=load("fake_customer_cleanup_sql_packet");frontend=load("client_dashboard_live_data_flag");yt_drop=load("youtube_transcript_dropzone");yt_import=load("youtube_transcript_import");nlm=load("notebooklm_legacy_adapter_recovery");nlm_drop=load("notebooklm_dropzone");nlm_import=load("notebooklm_source_import");oanda=load("oanda_demo_readonly_check");vibe=load("vibe_installation_audit");backtest=load("vibe_paper_backtest_dry_run");loop=load("automation_schedule_registry");schedule=load("safe_schedule_install_plan")
 blockers=[
  ("stripe_webhook","resolved","Listener/triggers were untested","Ran bounded signed test-mode listener and three triggers",listener.get("status"),"Keep production/live mode disabled"),
  ("stripe_checkout","human_approval_required","Browser completion required","Generated local URL retrieval and test-card packet",checkout.get("status"),"Approve manual test Checkout completion"),
  ("stripe_payment_intent","human_approval_required","Test payment method confirmation not approved","Generated pm_card_visa confirmation template",intent.get("payment_intent_status"),"Approve test-method confirmation"),
  ("payment_onboarding","dry_run_resolved","No persistent writes allowed","Mapped verified webhook events to dry-run records",webhook_flow.get("status"),"Complete RLS/insert gates"),
  ("rls_direct","human_dashboard_action_required","Docker unavailable for remote dump","Generated static proof and SQL Editor packet",rls_packet.get("status"),"Run read-only packet in Supabase SQL Editor"),
  ("synthetic_rollback","human_dashboard_action_required","No guaranteed remote transaction channel","Generated default-ROLLBACK insert/cleanup SQL packets","packets_ready_not_executed","Run packets in SQL Editor and retain rollback proof"),
  ("fake_customer_insert","blocked_by_safety_gate","RLS/rollback proof incomplete","Generated explicit insert and cleanup plans",gate.get("status"),"Approve only after SQL Editor verification"),
  ("frontend_live_data","implementation_resolved_flag_off","No live data row exists","Implemented authenticated feature-flag path with fallback",frontend.get("status"),"Enable only after approved insert"),
  ("resend_403","human_account_fix_required","403 plus sender-domain mismatch","Diagnosed account/key permission and .cc/.com mismatch",resend.get("status"),"Fix Resend key scope and verify goclearonline.com"),
  ("resend_email","approval_required","Sending prohibited","Draft and approval card ready","draft_ready_not_sent","Approve one test email only after 403 fix"),
  ("youtube_transcript","human_source_required","Approved TXT absent","Created approved dropzone/template/import packet",yt_drop.get("status"),"Add approved/zbAmmnMh5ew.txt"),
  ("notebooklm_sources","human_source_required","No selected export present","Recovered wrapper and created approved dropzone",nlm_drop.get("status"),"Drop approved .txt/.md/.json export"),
  ("oanda_demo","env_configuration_required","Practice mode not explicit","Blocked all network use and generated exact env fix",oanda.get("status"),"Set OANDA_ENVIRONMENT=practice and rerun"),
  ("vibe_cli","optional_install_approval","CLI package absent/untrusted","Created isolated install plan; legacy adapter works without it",vibe.get("status"),"Approve exact trusted package before install"),
  ("vibe_backtest","resolved","Recovered adapter had not run","Ran deterministic synthetic backtest",backtest.get("status"),"Review results; keep broker disabled"),
  ("safe_schedule","approval_required","Permanent daemon not approved","8/8 loop passed and launchd plan validated",schedule.get("status"),"Approve launchd install"),
  ("real_onboarding","blocked_by_safety_gate","No approved persistent test row/live read/payment completion","Implemented all gates and rollback packets","not_live","Complete RLS, insert, auth membership, and feature flag approvals"),
 ]
 matrix=[{"blocker":a,"status":b,"cause":c,"fix_attempted":d,"result":e,"next_action":f} for a,b,c,d,e,f in blockers];write_report("all_blockers_matrix","All Blockers Matrix",{"ok":True,"generated_at":now(),"blockers":len(matrix),"resolved_or_implemented":sum(x["status"] in {"resolved","dry_run_resolved","implementation_resolved_flag_off"} for x in matrix),"external_action_performed":False},{"Matrix":matrix})
 baseline={"ok":True,"generated_at":now(),"branch":"main","start_commit":"475201c","repo_clean_at_start":True,"build_start_passed":True,"blockers_at_start":17,"external_action_performed":False};write_report("all_blockers_baseline","All Blockers Baseline",baseline)
 cards=[card("approve-checkout-complete","Approve manual completion of Stripe test Checkout Session","Use Stripe test card only.","high"),card("approve-webhook-test","Approve Stripe webhook listener/trigger test if not automated","Already automated successfully; approve retaining it as bounded test procedure."),card("approve-pi-confirm","Approve Stripe test PaymentIntent confirmation using test method","Use pm_card_visa after livemode=false proof.","high"),card("approve-resend-fix","Approve Resend fix and test email after 403 diagnosis","Correct key scope/account and .com sender, then test Ray only.","high"),card("approve-onboarding-draft","Approve onboarding email draft","Content approval only; send remains separately gated."),card("approve-rls-sql-editor","Approve no-Docker RLS SQL verification in Supabase SQL Editor","Run read-only packet on project iqjwgpnujbeoyaeuwehj.","high"),card("approve-fake-insert","Approve persistent fake customer Supabase insertion after RLS verification","Use synthetic tenant only after rollback proof.","high"),card("approve-fake-cleanup","Approve fake customer cleanup SQL","Scoped tenant/client cleanup only.","high"),card("approve-client-live-read","Approve /client/dashboard live Supabase read for fake customer","Enable feature flag only after insert/membership proof.","high"),card("approve-youtube-transcript","Approve YouTube transcript import after .txt is added","Approved local TXT only."),card("approve-notebooklm-import","Approve NotebookLM selected notebook import workflow","Approved manual export only."),card("approve-oanda-read","Approve Oanda demo read-only connection check if not completed","Require practice endpoint; no orders.","high"),card("approve-vibe-backtest","Approve Vibe/paper backtest dry-run","Synthetic adapter test already passed; no broker."),card("approve-safe-schedule","Approve safe internal automation schedule install","Validated launchd draft; external actions disabled.")]
 write_json(SUPABASE_READY/"all_blockers_ray_review_cards_latest.json",cards);write_report("all_blockers_ray_review_cards","All Blockers Ray Review Cards",{"ok":True,"generated_at":now(),"status":"ready_for_Ray_review","cards_created":len(cards),"external_action_performed":False},{"Cards":cards})
 recommendations=["Run the read-only RLS SQL Editor packet next.","After RLS proof, run the synthetic insert packet with its default ROLLBACK and preserve results.","Fix Resend key scope/account and change sender domain from .cc to verified .com.","Keep actual Checkout and PaymentIntent completion manually gated despite successful webhook triggers.","Drop the approved YouTube TXT and NotebookLM export into their prepared approved folders.","Set explicit OANDA_ENVIRONMENT=practice before any read-only account call.","The synthetic backtest is operational; do not install Vibe CLI until its exact package/license is approved.","Install the validated safe launchd schedule only after Ray approves persistence."]
 hermes={"ok":True,"generated_at":now(),"status":"all_blockers_brief_ready","recommendations":recommendations,"recommendations_count":len(recommendations),"resolved":[x["blocker"] for x in matrix if x["status"] in {"resolved","dry_run_resolved","implementation_resolved_flag_off"}],"remaining":[{"blocker":x["blocker"],"reason":x["cause"],"next_action":x["next_action"]} for x in matrix if x["status"] not in {"resolved","dry_run_resolved","implementation_resolved_flag_off"}],"next_action":"Approve and run the read-only RLS SQL Editor verification packet.","external_action_performed":False};write_report("hermes_all_blockers_brief","Hermes All Blockers Brief",hermes,{"Recommendations":recommendations})
 frontend_status={"ok":True,"generated_at":now(),"stripe_webhook_server":"bounded_listener_three_triggers_verified","stripe_listener":"passed_stopped","stripe_triggers":"three_test_events_received","checkout":checkout.get("status"),"payment_intent":intent.get("payment_intent_status"),"webhook_onboarding":webhook_flow.get("status"),"resend":resend.get("status"),"rls_no_docker":rls_packet.get("status"),"fake_customer_gate":gate.get("status"),"frontend_flag":frontend.get("status"),"youtube_transcript":yt_drop.get("status"),"notebooklm":nlm_drop.get("status"),"oanda":oanda.get("status"),"vibe_backtest":backtest.get("status"),"safe_loop":"eight_of_eight_passed","schedule":schedule.get("status"),"next_required_approval":"Run no-Docker RLS SQL verification","external_action_performed":False};write_report("all_blockers_frontend_status","All Blockers Frontend Status",frontend_status)
 master={"ok":True,"generated_at":now(),"build_result":"passed","safety_result":"passed_with_approved_stripe_test_triggers","stripe_webhook_server_status":listener.get("status"),"stripe_listener_status":"passed_and_stopped","stripe_trigger_status":trigger.get("status"),"stripe_events_received":trigger.get("event_received",False),"signature_verified":trigger.get("signature_verified",False),"checkout_status":checkout.get("status"),"checkout_completed":checkout.get("checkout_completed",False),"payment_intent_status":intent.get("payment_intent_status"),"payment_intent_confirmed":intent.get("confirmed",False),"webhook_onboarding":webhook_flow.get("status"),"persistent_database_insert":False,"real_charge":False,"resend_key_detected":True,"resend_403_likely_cause":"restricted/wrong-account key scope plus configured .cc sender mismatch","resend_fix_required":"Use intended Resend account/full or domain-read key; verify goclearonline.com; configure .com sender.","email_sent":False,"rls_static_verification":rls.get("status"),"rls_sql_packet":rls_packet.get("status"),"fake_customer_gate":gate.get("status"),"fake_customer_cleanup":cleanup.get("status"),"frontend_live_flag":frontend.get("status"),"youtube_transcript_import":yt_import.get("status"),"youtube_dropzone":yt_drop.get("status"),"notebooklm_adapter":nlm.get("status"),"notebooklm_import":nlm_import.get("status"),"oanda_demo":oanda.get("status"),"oanda_orders_placed":False,"vibe_cli":vibe.get("status"),"vibe_backtest":backtest.get("status"),"safe_loop":"8/8 passed","schedule_install":schedule.get("status"),"external_actions_performed":True,"external_actions_detail":"Approved Stripe test-mode fixture triggers only; no live actions.","social_posts_published":False,"disputes_sent":False,"live_trades_placed":False,"ray_review_cards":len(cards),"hermes_recommendations":len(recommendations),"resolved_blockers":[x["blocker"] for x in matrix if x["status"] in {"resolved","dry_run_resolved","implementation_resolved_flag_off"}],"remaining_blockers":[{"blocker":x["blocker"],"why":x["cause"]} for x in matrix if x["status"] not in {"resolved","dry_run_resolved","implementation_resolved_flag_off"}],"exact_next_command":"Open reports/manual_publish/rls_sql_editor_verification_packet_latest.sql and run it in Supabase SQL Editor for project iqjwgpnujbeoyaeuwehj."};write_report("all_blockers_resolution_master","All Blockers Resolution Master",master);return master
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--json",action="store_true");a=p.parse_args();r=build();print(json.dumps(r,indent=2) if a.json else r)
