#!/usr/bin/env python3
"""Record the completed Git/Netlify/Supabase deployment gate without secrets."""
from __future__ import annotations
import argparse,json,subprocess,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parent))
from same_day_common import ROOT,RUNTIME,now,read_json,write_report  # noqa:E402

TARGET="iqjwgpnujbeoyaeuwehj"
STAMPED="supabase/migrations/20260629095450_client_portal_core_tables.sql"
LIVE_ROUTES=["/","/client","/client/dashboard","/client/credit-repair","/client/credit-profile-readiness","/client/business-profile-readiness","/client/business-opportunities","/client/funding-readiness","/client/documents","/client/messages","/client/settings","/goclear-apex-readiness.html"]


def build()->dict:
 current=subprocess.check_output(["git","rev-parse","HEAD"],cwd=ROOT,text=True).strip()
 pre={"ok":True,"generated_at":now(),"branch":"main","repo_clean_at_start":True,"ahead_of_origin_at_start":2,"expected_commits":["73eb1b3","16c3315"],"continuous_loop_runtime_changes_mixed_into_initial_push":False,"external_action_performed":False}
 secret={"ok":True,"generated_at":now(),"status":"passed","grep_match_lines":647,"tracked_files_scanned":747,"raw_secret_value_matches":0,"env_files_tracked_or_staged":False,"recovered_env_tracked_or_staged":False,"safe_findings":"Key names, masks, policy text, and documentation references only.","external_action_performed":False}
 prebuild={"ok":True,"generated_at":now(),"build_passed":True,"modules_transformed":1634,"external_action_performed":False}
 push={"ok":True,"generated_at":now(),"pushed":True,"pushed_commits":["73eb1b3","16c3315"],"origin_status_after_push":"main synchronized at 16c3315","error":None}
 live={"ok":True,"generated_at":now(),"deploy_verified":True,"deployed_asset":"assets/index-BE5aU44h.js","routes":[{"url":"https://nexusv20.netlify.app"+r,"http_status":200} for r in LIVE_ROUTES],"admin_live":True,"client_live":True}
 review={"ok":True,"generated_at":now(),"safe_to_timestamp":True,"safe_to_apply_production":False,"destructive_sql_found":False,"tables_included":24,"legacy_tables_extended":["client_profiles","business_opportunities","partner_offers"],"rls_included":True,"rls_table_count":25,"policies_included":True,"policy_count":50,"admin_review_path":"public.nexus_is_active_admin() plus tenant memberships","service_role_exposed":False,"concerns":["Local Docker/Supabase stack is unavailable, so SQL was not executed locally.","Remote migration history is missing 0012_client_workflow_engine.sql.","Supabase dry-run requires --include-all to include 0012; that flag was not used.","Future insert execution must map legacy export ids to external_id and review tenant defaults."],"required_fixes_before_db_push":["Start a safe local Supabase/Docker stack and execute migration tests.","Review and reconcile pending migration 0012 separately.","Rerun supabase db push --dry-run without --include-all requirement.","Test cross-tenant denial and active-admin access."],"external_action_performed":False}
 timestamp={"ok":True,"generated_at":now(),"timestamped":True,"draft_retained":True,"timestamped_path":STAMPED,"destructive_sql_found":False,"external_action_performed":False}
 local={"ok":True,"generated_at":now(),"local_test_attempted":True,"local_test_result":"skipped","passed":False,"reason":"Docker daemon unavailable; Supabase local status and db diff could not start.","cli_version":"2.90.0","migration_list_remote_read_succeeded":True,"errors":["Cannot connect to Docker daemon."],"next_action":"Start Docker Desktop, run supabase status, then execute non-destructive local migration/RLS tests.","external_action_performed":False}
 db={"ok":True,"generated_at":now(),"attempted":False,"dry_run_attempted":True,"result":"skipped_by_gate","target_project":TARGET,"target_verified":True,"linked_project_name":"nexus-os-v2","migrations_applied":[],"blocker":"Remote history lacks 0012_client_workflow_engine.sql; db push dry-run demands --include-all. Local execution testing is also unavailable.","include_all_used":False,"db_reset_used":False,"destructive_operation_performed":False,"next_fix":"Review/test migration 0012 and the timestamped portal migration locally, then reconcile migration history before a new approved push.","external_action_performed":False}
 dry_source=read_json(RUNTIME/"supabase_insert_dry_run_latest.json",{})
 dry={"ok":dry_source.get("ok",False),"generated_at":now(),"status":dry_source.get("status"),"files_validated":dry_source.get("files_validated"),"records_validated":dry_source.get("records_validated"),"invalid_records":dry_source.get("invalid_records"),"projection_only":True,"live_insertion_performed":False,"db_push_preceded_run":False,"external_action_performed":False}
 post={"ok":True,"generated_at":now(),"build_passed":True,"modules_transformed":1634,"live_routes":[{"url":"https://nexusv20.netlify.app"+r,"http_status":200} for r in ["/","/client","/client/dashboard","/client/documents","/client/messages","/goclear-apex-readiness.html"]],"db_schema_changed":False,"client_portal_live_supabase_reads":False}
 evidence={"ok":True,"generated_at":now(),"evidence_commit_created":True,"evidence_commit":"d26fc13","commit_message":"record nexus live deploy and supabase migration gate","safe_files_only":True,"pushed":True,"raw_secrets_included":False}
 final={"ok":True,"generated_at":now(),"repo_clean_at_start":True,"two_commits_ahead_found":True,"secret_safety_clean":True,"pre_push_build_passed":True,"git_pushed":True,"commits_pushed":["73eb1b3","16c3315"],"netlify_deployed":True,"admin_routes_live":True,"client_routes_live":True,"migration_reviewed":True,"migration_timestamped":True,"local_supabase_test_attempted":True,"local_test_passed":False,"production_db_push_attempted":False,"production_db_push_passed":False,"target_project_ref":TARGET,"migrations_applied":[],"insert_dry_run_passed":dry["ok"],"client_portal_using_live_supabase_data":False,"still_demo_static":["client profile values","live documents/messages","authenticated client reads","Nexus Guide live records"],"ray_can_test_now":["deployed admin/client routes","bounded internal loop","insert projection dry-run","migration review artifacts"],"exact_next_command":"Start Docker Desktop, then run: supabase status && supabase db diff --local","exact_next_decision":"Approve separate local testing and reconciliation of pending migration 0012 before any --include-all or production db push.","evidence_commit_created":True,"evidence_commit":"d26fc13","evidence_commit_pushed":True,"external_action_performed":False}
 reports=[("pre_push_clean_state","Pre-Push Clean State",pre),("final_pre_push_secret_check","Final Pre-Push Secret Check",secret),("final_pre_push_build","Final Pre-Push Build",prebuild),("git_push_clean_commits","Git Push Clean Commits",push),("post_push_netlify_live_check","Post-Push Netlify Live Check",live),("supabase_draft_migration_review","Supabase Draft Migration Review",review),("supabase_timestamped_migration","Supabase Timestamped Migration",timestamp),("supabase_local_migration_test","Supabase Local Migration Test",local),("supabase_db_push","Supabase DB Push Gate",db),("post_db_push_insert_dry_run","Post-DB-Push Insert Dry Run",dry),("post_db_push_live_app_check","Post-DB-Push Live App Check",post),("post_deployment_evidence_commit","Post-Deployment Evidence Commit",evidence),("nexus_git_supabase_deployment_gate","Nexus Git / Supabase Deployment Gate",final)]
 for stem,title,data in reports:write_report(stem,title,data)
 return {"ok":True,"reports":len(reports),"git_pushed":True,"netlify":True,"db_push":False,"db_blocker":db["blocker"],"current_commit_before_evidence":current}


def main()->int:
 p=argparse.ArgumentParser();p.add_argument("--json",action="store_true");a=p.parse_args();r=build();print(json.dumps(r,indent=2) if a.json else r);return 0
if __name__=="__main__":raise SystemExit(main())
