export type Opportunity={title:string;source:string;category:string;monetizationPath:string;audience:string;effort:"low"|"medium"|"high";cost:"low"|"medium";expectedValue:"unvalidated";risk:"low"|"medium";connectorNeeded:string;nextAction:string;rayReviewRequired:true;owner:"Nexus/GoClear"|"Alpha"};
export function findLocalMoneyOpportunities():Opportunity[]{return [
 {title:"Credit & funding readiness review explainer",source:"nexus_research + GoClear readiness reports",category:"GoClear credit/funding content",monetizationPath:"$97 readiness review education",audience:"business owners preparing for funding",effort:"medium",cost:"low",expectedValue:"unvalidated",risk:"medium",connectorNeeded:"GSC/Analytics for validation",nextAction:"Review landing-page draft and define measurement",rayReviewRequired:true,owner:"Nexus/GoClear"},
 {title:"Business fundability checklist",source:"local business setup research",category:"low-cost lead generation",monetizationPath:"lead magnet plus approved referrals",audience:"new business owners",effort:"low",cost:"low",expectedValue:"unvalidated",risk:"low",connectorNeeded:"approved email platform and affiliate links",nextAction:"Review sample and compliance language",rayReviewRequired:true,owner:"Alpha"},
 {title:"Utilization readiness education series",source:"credit utilization seed research",category:"client education drafts",monetizationPath:"SEO/newsletter education",audience:"credit education readers",effort:"medium",cost:"low",expectedValue:"unvalidated",risk:"medium",connectorNeeded:"GSC/Analytics",nextAction:"Create three evidence-cited outlines",rayReviewRequired:true,owner:"Nexus/GoClear"},
 {title:"Research-to-opportunity newsletter",source:"NotebookLM and YouTube local exports",category:"newsletter ideas",monetizationPath:"audience development and approved affiliates",audience:"operators evaluating AI workflows",effort:"low",cost:"low",expectedValue:"unvalidated",risk:"low",connectorNeeded:"newsletter account and approved links",nextAction:"Select one local research theme",rayReviewRequired:true,owner:"Alpha"}
 ,{title:"Voice-agent readiness audit",source:"Alpha voice-agent opportunity category",category:"low-cost service test",monetizationPath:"manual workflow audit before implementation",audience:"local service businesses",effort:"medium",cost:"low",expectedValue:"unvalidated",risk:"medium",connectorNeeded:"none for interviews; approved voice platform later",nextAction:"Interview five businesses about one call workflow",rayReviewRequired:true,owner:"Alpha"}
]}
export const seoFallbackMode={mode:"local_reports_only",externalWebUsed:false,trafficClaims:false,revenueClaims:false};
