import {inferAlphaMode,type AlphaConversationMode} from './hermesAlphaModeRouter';
import {findLocalMoneyOpportunities} from './alphaSeoMoneyOpportunityEngine';
import {runTradingResearchPipeline} from './alphaTradingResearchPipeline';
import {createAlphaActionDraft} from './hermesAlphaActionDrafts';
export type AlphaProviderStatus={provider:"deterministic_local"|"ollama_local"|"openrouter"|"groq";available:boolean;label:string;external:boolean};
export const alphaProviderStatuses:AlphaProviderStatus[]=[{provider:"deterministic_local",available:true,label:"Deterministic local fallback (active)",external:false},{provider:"ollama_local",available:false,label:"Ollama installed; browser-safe Alpha bridge not configured",external:false},{provider:"openrouter",available:false,label:"OpenRouter key/Alpha gateway not verified",external:true},{provider:"groq",available:false,label:"Groq key/Alpha gateway not verified",external:true}];
export function respondAsAlpha(prompt:string,selectedMode:AlphaConversationMode="General Conversation"){const p=prompt.trim(),q=p.toLowerCase(),mode=inferAlphaMode(p,selectedMode);let text:string;let draft:ReturnType<typeof createAlphaActionDraft>|undefined;
 if(/^(good )?morning[.! ]*$/.test(q))text="Good morning Ray. I’m Alpha — your strategy and opportunity brain. We can talk through business ideas, affiliate plays, SEO opportunities, app ideas, voice agents, trading research, marketing drafts, or anything else you want to explore.";
 else if(/what can you (answer|do)|how can you help|your capabilities/.test(q))text="I can help you pressure-test business ideas, design low-cost startup experiments, find opportunities in Nexus research, shape affiliate and SEO strategies, draft marketing and landing pages, evaluate app and voice-agent ideas, and turn trading ideas into research and demo plans. I can also prepare handoffs and Ray Review drafts. I cannot look up current events yet, use client data, access Supabase, or execute external actions.";
 else if(/soccer match|match score|what happened.*match/.test(q))text="I can discuss this generally, but live web/current lookup is not configured yet. Connect public web/search/news access for current match details.";
 else if(/change the subject/.test(q))text="Subject changed. What do you want to explore next—business, an app, marketing, trading research, or something unrelated?";
 else if(/voice agent/.test(q))text="Yes—voice agents can be a realistic service business if you start narrow.\n\nTarget customer: appointment-based local businesses that miss calls, such as HVAC, dental, legal intake, or home services.\nOffer: one voice workflow—after-hours answering, lead qualification, or appointment requests—with human fallback.\nMVP: map one call script, prototype it with a voice platform, and manually review every outcome.\nPricing test: ask five prospects to compare a $250–$500 setup plus $99–$299 monthly pilot against the cost of missed calls; do not treat those prices as validated.\nCost: keep the first test under $100 using trials and manual setup.\nFirst experiment: interview five owners and secure one written pilot commitment before building integrations.\nRisks: call-recording consent, inaccurate answers, missed escalation, platform costs, and customer-specific integrations.\nNext action: choose one industry and write its ten most common inbound-call scenarios.";
 else if(/3 low-cost startup/.test(q))text="1. Voice-agent workflow audit — cost: under $50; first test: interview five local businesses and map one missed-call workflow; revenue path: paid audit, then setup/pilot service.\n\n2. Business fundability checklist review — cost: under $25; first test: offer five manual checklist walkthroughs; revenue path: a fixed-price readiness review with approved referrals later.\n\n3. Research-to-newsletter service — cost: under $25; first test: create one issue from a client-approved topic and ask five prospects if they would pay for four per month; revenue path: monthly content service.\n\nThese are validation ideas, not revenue forecasts.";
 else if(/money opportunities.*nexus|seo opportun|good seo/.test(q)){const items=findLocalMoneyOpportunities().slice(0,5);text=`Current local-evidence opportunities:\n${items.map((x,i)=>`${i+1}. ${x.title} — ${x.monetizationPath}; value unvalidated.`).join("\n")}\nGSC, Analytics, and live web are not configured, so traffic and revenue cannot be claimed.`;}
 else if(/build an app|app around/.test(q))text="Yes, if the repeated workflow is proven manually first. Define one user, one painful job, one measurable outcome, and a manual concierge version. Build only after 5–10 users complete the workflow and identify the same bottleneck.";
 else if(/landing page/.test(q))text="Draft: Headline—Make the next decision with clearer readiness evidence. Subhead—Review gaps, documents, and practical next steps before applying. CTA—Join the early interest list. Educational only; no approval, funding, credit, or outcome guarantee.";
 else if(/affiliate strateg/.test(q))text="Start with problem-first education, compare an approved free option with paid partners, disclose referral compensation, and track qualified clicks manually. Do not insert links until Ray approves the program, destination, claims, and disclosure.";
 else if(/what should i test first/.test(q))text="Test the Got Funding interest page first: verify the QR destination, submit synthetic form data in a Netlify deploy preview, and measure valid opt-ins. This is cheaper and more informative than ads or product build-out.";
 else if(/trading strateg|can this.*strateg/.test(q)){const x=runTradingResearchPipeline(p);text=`This is researchable, not yet proven. Strategy ${x.strategy_id} requires frozen rules, historical data with costs, out-of-sample testing, and a Ray-approved paper/demo plan. No performance result exists and no order is enabled.`;}
 else if(/handoff prompt/.test(q)){draft=createAlphaActionDraft(p,"handoff");text=`Handoff draft:\nObjective: ${p}\nConstraints: use public/local non-client data, cite evidence, state uncertainty, do not execute external actions, and return a reviewable artifact.`;}
 else if(/ray review draft/.test(q)){draft=createAlphaActionDraft(p);text=`Ray Review draft created locally. Decision requested: approve, reject, or revise a manual experiment. Approval does not execute or publish anything.`;}
 else text=`Tell me a little more about what you want from this—are you deciding whether the idea is worth pursuing, looking for a business model, trying to design the first test, or wanting a concrete draft? I’ll help you work it through plainly. I don’t have live web/current lookup in this workspace, so I’ll flag anything that needs current research.`;
 return {brain:"Hermes Alpha" as const,mode,text,provider:"deterministic_local" as const,providerDisclosure:"Local deterministic fallback—no live model or web call was made.",noSupabaseUsed:true as const,clientDataUsed:false as const,externalActionPerformed:false as const,draft};}
