import {inferAlphaMode,type AlphaConversationMode} from './hermesAlphaModeRouter';
import {findLocalMoneyOpportunities} from './alphaSeoMoneyOpportunityEngine';
import {runTradingResearchPipeline} from './alphaTradingResearchPipeline';
import {createAlphaActionDraft} from './hermesAlphaActionDrafts';
export type AlphaProviderStatus={provider:"deterministic_local"|"ollama_local"|"openrouter"|"groq";available:boolean;label:string;external:boolean};
export const alphaProviderStatuses:AlphaProviderStatus[]=[{provider:"deterministic_local",available:true,label:"Deterministic local fallback (active)",external:false},{provider:"ollama_local",available:false,label:"Ollama installed; browser-safe Alpha bridge not configured",external:false},{provider:"openrouter",available:false,label:"OpenRouter key/Alpha gateway not verified",external:true},{provider:"groq",available:false,label:"Groq key/Alpha gateway not verified",external:true}];
function timeGreeting(nowMs:number):string{const h=new Date(nowMs).getHours();if(h<6)return 'Good night';if(h<12)return 'Good morning';if(h<17)return 'Good afternoon';return 'Good evening'}
function casualReply(prompt:string):string{const q=prompt.toLowerCase().trim();
if(/how did you sleep|did you sleep|rest well/.test(q))return `I don't sleep, but I'm ready to work. Want to use me for strategy, GoClear, Alpha testing, or a money idea?`;
if(/favorite card/.test(q))return `I don't have personal favorites, but for your goals I'd judge cards by reporting, limits, fees, rewards, and business-funding usefulness.`;
if(/favorite (color|food|song|movie)/.test(q))return `I don't have personal favorites, but I can help you compare the options based on what matters to you.`;
if(/what time is it|current time/.test(q))return `Using your browser's local clock, it is ${new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}.`;
if(/where did (that|this|your) answer come from|what source did you use/.test(q))return `Open the response source line under my last answer. It shows the selected and actual provider, session-memory use, report use, web status, model, fallback reason, and confirms that Supabase and client data were not used.`;
if(/what.*name|who are you|your name/.test(q))return `I'm Hermes Alpha — Ray's strategy and opportunity partner. I help pressure-test ideas, find opportunities, and turn rough thoughts into concrete plans.`;
if(/thank|thanks|thx/.test(q))return `Happy to help. Let me know what's next.`;
if(/hello|hi |hey|sup|yo /.test(q))return `Hey. What's on your mind?`;
if(/^(yes|no|ok|okay|sure|yep|nope|nah|yup)$/.test(q))return `Got it. Want to go deeper on that, or move on to something else?`;
if(/bored|nothing to do|what now/.test(q))return `Plenty of things to explore. Pick a direction: business ideas, SEO opportunities, voice agents, app concepts, affiliate strategy, trading research, or just something random you've been thinking about.`;
return ''}
export function respondAsAlpha(prompt:string,selectedMode:AlphaConversationMode="General Conversation",nowMs:number=Date.now()){const p=prompt.trim(),q=p.toLowerCase(),mode=inferAlphaMode(p,selectedMode);let text:string;let draft:ReturnType<typeof createAlphaActionDraft>|undefined;
if(/^(good )?morning[.! ]*$/.test(q))text=`${timeGreeting(nowMs)} Ray. I'm Alpha — your strategy and opportunity brain. What are we working on?`;
else if(/^(good )?afternoon[.! ]*$/.test(q))text=`${timeGreeting(nowMs)} Ray. I'm Alpha — your strategy and opportunity brain. What are we working on?`;
else if(/^(good )?evening[.! ]*$/.test(q))text=`${timeGreeting(nowMs)} Ray. I'm Alpha — your strategy and opportunity brain. What are we working on?`;
else{const casual=casualReply(p);if(casual){text=casual;return {brain:"Hermes Alpha" as const,mode,text,provider:"deterministic_local" as const,providerDisclosure:"Local deterministic fallback—no live model or web call was made.",noSupabaseUsed:true as const,clientDataUsed:false as const,externalActionPerformed:false as const,draft}}if(/what can you (answer|do)|how can you help|your capabilities/.test(q))text=`I can help you pressure-test business ideas, design low-cost startup experiments, find opportunities in Nexus research, shape affiliate and SEO strategies, draft marketing and landing pages, evaluate app and voice-agent ideas, and turn trading ideas into research and demo plans. I can also prepare handoffs and Ray Review drafts. I don't have live web or Supabase access, so I'll be upfront about what needs external research.`;
else if(/soccer match|match score|what happened.*match/.test(q))text=`I can't look up live scores or match results — no web access from this workspace. If you want, I can help you think through how to set up a sports data workflow, or we can talk about something else.`;
else if(/change the subject/.test(q))text=`Sure. What do you want to explore next — business, an app, marketing, trading research, or something completely different?`;
else if(/voice agent/.test(q))text=`Voice agents are a real opportunity if you stay narrow and start with one use case.\n\nHere's how I'd approach it:\n\n1. Pick one customer type — appointment-based local businesses that miss calls (HVAC, dental, legal intake, home services).\n\n2. Define one workflow — after-hours answering, lead qualification, or appointment requests. Human fallback for anything complex.\n\n3. Prototype fast — map one call script, test it with a voice platform, review every outcome manually.\n\n4. Price it simply — $250–$500 setup plus $99–$299 monthly. But validate those numbers with real prospects, not assumptions.\n\n5. Keep first test under $100 using trials.\n\nKey risks: call-recording consent, inaccurate answers, missed escalations, platform costs.\n\nWant me to help you write the first ten call scenarios for a specific industry?`;
else if(/3 low-cost startup|low-cost startup|startup ideas?/.test(q))text=`Here are three directions worth exploring:\n\n1. Voice-agent workflow audit\n   Cost: under $50\n   First test: interview five local businesses, map one missed-call workflow\n   Revenue path: paid audit → setup/pilot service\n\n2. Business fundability checklist review\n   Cost: under $25\n   First test: offer five manual checklist walkthroughs\n   Revenue path: fixed-price readiness review, approved referrals later\n\n3. Research-to-newsletter service\n   Cost: under $25\n   First test: create one issue from a client-approved topic, ask five prospects if they'd pay for four per month\n   Revenue path: monthly content service\n\nThese are validation ideas, not revenue forecasts. Want me to go deeper on any of them?`;
else if(/money opportunities.*nexus|seo opportun|good seo/.test(q)){const items=findLocalMoneyOpportunities().slice(0,5);text=`Here are the local-evidence opportunities I'm seeing:\n\n${items.map((x,i)=>`${i+1}. ${x.title}\n   Monetization: ${x.monetizationPath}\n   Note: value unvalidated — needs GSC/Analytics data`).join("\n\n")}\n\nI don't have live web or GSC access, so these are based on pattern-matching from existing Nexus data. Want me to help you prioritize or dig into any of these?`}
else if(/build an app|app around/.test(q))text=`Yes, but only after you've proven the workflow manually. Here's the framework:\n\n1. Define one user with one painful job\n2. Define one measurable outcome\n3. Build a manual concierge version first\n4. Run 5–10 users through it\n5. If they all hit the same bottleneck, then build the app\n\nWhat's the workflow you're thinking about?`;
else if(/landing page/.test(q))text=`Draft:\n\nHeadline: Make the next decision with clearer readiness evidence\nSubhead: Review gaps, documents, and practical next steps before applying\nCTA: Join the early interest list\n\nThis is educational only — no approval, funding, credit, or outcome guarantee. Want me to flesh out the copy or add sections?`;
else if(/affiliate strateg/.test(q))text=`Start with problem-first education:\n\n1. Compare an approved free option with paid partners\n2. Disclose referral compensation clearly\n3. Track qualified clicks manually\n4. Don't insert links until Ray approves the program, destination, claims, and disclosure\n\nWhat product or niche are you considering?`;
else if(/what should i test first/.test(q))text=`Test the Got Funding interest page first:\n\n1. Verify the QR destination works\n2. Submit synthetic form data in a Netlify deploy preview\n3. Measure valid opt-ins\n\nThis is cheaper and more informative than ads or product build-out. Want me to help you design the test?`;
else if(/trading strateg|can this.*strateg/.test(q)){const x=runTradingResearchPipeline(p);text=`This is researchable, not yet proven. Strategy ${x.strategy_id} requires:\n\n1. Frozen rules — no curve-fitting\n2. Historical data with realistic costs\n3. Out-of-sample testing\n4. A Ray-approved paper/demo plan\n\nNo performance result exists and no order is enabled. Want me to help you structure the backtest?`}
else if(/handoff prompt/.test(q)){draft=createAlphaActionDraft(p,"handoff");text=`Handoff draft:\n\nObjective: ${p}\nConstraints: use public/local non-client data, cite evidence, state uncertainty, do not execute external actions, and return a reviewable artifact.\n\nThis is a draft only — nothing executes until Ray approves.`}
else if(/ray review draft/.test(q)){draft=createAlphaActionDraft(p);text=`Ray Review draft created locally.\n\nDecision requested: approve, reject, or revise a manual experiment.\nApproval does not execute or publish anything.`}
else text=`I need a bit more context to give you a useful answer. Are you:\n\n• Deciding whether an idea is worth pursuing?\n• Looking for a business model?\n• Designing a first test?\n• Wanting a concrete draft or handoff?\n\nTell me where you are and I'll help you move forward. I don't have live web access, so I'll flag anything that needs current research.`;}
return {brain:"Hermes Alpha" as const,mode,text,provider:"deterministic_local" as const,providerDisclosure:"Local deterministic fallback—no live model or web call was made.",noSupabaseUsed:true as const,clientDataUsed:false as const,externalActionPerformed:false as const,draft};}
