import {inferAlphaMode,type AlphaConversationMode} from './hermesAlphaModeRouter';
import {findLocalMoneyOpportunities} from './alphaSeoMoneyOpportunityEngine';
import {runTradingResearchPipeline} from './alphaTradingResearchPipeline';
import {createAlphaActionDraft} from './hermesAlphaActionDrafts';
export type AlphaProviderStatus={provider:"deterministic_local"|"ollama_local"|"openrouter"|"groq";available:boolean;label:string;external:boolean};
export const alphaProviderStatuses:AlphaProviderStatus[]=[{provider:"deterministic_local",available:true,label:"Deterministic local fallback (active)",external:false},{provider:"ollama_local",available:false,label:"Ollama installed; browser-safe Alpha bridge not configured",external:false},{provider:"openrouter",available:false,label:"OpenRouter key/Alpha gateway not verified",external:true},{provider:"groq",available:false,label:"Groq key/Alpha gateway not verified",external:true}];
export function respondAsAlpha(prompt:string,selectedMode:AlphaConversationMode="General Conversation"){const p=prompt.trim(),q=p.toLowerCase(),mode=inferAlphaMode(p,selectedMode);let text:string;let draft:ReturnType<typeof createAlphaActionDraft>|undefined;
 if(/soccer match|match score|what happened.*match/.test(q))text="I can discuss this generally, but live web/current lookup is not configured yet. Connect public web/search/news access for current match details.";
 else if(/change the subject/.test(q))text="Subject changed. What do you want to explore next—business, an app, marketing, trading research, or something unrelated?";
 else if(/voice agent/.test(q))text="Selling voice agents is realistic as a service test if you start with one narrow workflow and manual fulfillment. Interview 5 target businesses, prototype one call flow, measure booked appointments or resolved calls, and verify consent/recording rules before spending on infrastructure.";
 else if(/3 low-cost startup/.test(q))text="1. A manual funding-readiness checklist service. 2. A niche voice-agent setup audit. 3. A local research-to-newsletter service. Test each with one page, five interviews, and manual delivery before software or ads.";
 else if(/money opportunities.*nexus|seo opportun|good seo/.test(q)){const items=findLocalMoneyOpportunities().slice(0,5);text=`Current local-evidence opportunities:\n${items.map((x,i)=>`${i+1}. ${x.title} — ${x.monetizationPath}; value unvalidated.`).join("\n")}\nGSC, Analytics, and live web are not configured, so traffic and revenue cannot be claimed.`;}
 else if(/build an app|app around/.test(q))text="Yes, if the repeated workflow is proven manually first. Define one user, one painful job, one measurable outcome, and a manual concierge version. Build only after 5–10 users complete the workflow and identify the same bottleneck.";
 else if(/landing page/.test(q))text="Draft: Headline—Make the next decision with clearer readiness evidence. Subhead—Review gaps, documents, and practical next steps before applying. CTA—Join the early interest list. Educational only; no approval, funding, credit, or outcome guarantee.";
 else if(/affiliate strateg/.test(q))text="Start with problem-first education, compare an approved free option with paid partners, disclose referral compensation, and track qualified clicks manually. Do not insert links until Ray approves the program, destination, claims, and disclosure.";
 else if(/what should i test first/.test(q))text="Test the Got Funding interest page first: verify the QR destination, submit synthetic form data in a Netlify deploy preview, and measure valid opt-ins. This is cheaper and more informative than ads or product build-out.";
 else if(/trading strateg|can this.*strateg/.test(q)){const x=runTradingResearchPipeline(p);text=`This is researchable, not yet proven. Strategy ${x.strategy_id} requires frozen rules, historical data with costs, out-of-sample testing, and a Ray-approved paper/demo plan. No performance result exists and no order is enabled.`;}
 else if(/handoff prompt/.test(q)){draft=createAlphaActionDraft(p,"handoff");text=`Handoff draft:\nObjective: ${p}\nConstraints: use public/local non-client data, cite evidence, state uncertainty, do not execute external actions, and return a reviewable artifact.`;}
 else if(/ray review draft/.test(q)){draft=createAlphaActionDraft(p);text=`Ray Review draft created locally. Decision requested: approve, reject, or revise a manual experiment. Approval does not execute or publish anything.`;}
 else text=`Let’s evaluate that as a reversible experiment. Clarify the target user, painful job, current alternative, cheapest manual test, success metric, and stop condition. I have no live web/current-data access in this workspace, so current facts need a configured public research connector.`;
 return {brain:"Hermes Alpha" as const,mode,text,provider:"deterministic_local" as const,providerDisclosure:"Local deterministic fallback—no live model or web call was made.",noSupabaseUsed:true as const,clientDataUsed:false as const,externalActionPerformed:false as const,draft};}
