import type { NexusDepartment } from './nexusProjectTypes';

export type NexusFeederEnabledState =
  | 'manual_only'
  | 'ready_for_schedule'
  | 'disabled'
  | 'blocked'
  | 'needs_connector';

export type NexusFeederRiskLevel = 'low' | 'medium' | 'high';

export interface NexusDepartmentFeeder {
  feeder_id: string;
  name: string;
  owning_department: NexusDepartment;
  owner_tab: string;
  purpose: string;
  source_type: string;
  script_or_process: string;
  manual_command: string;
  schedule_recommendation: string;
  enabled_state: NexusFeederEnabledState;
  risk_level: NexusFeederRiskLevel;
  approval_required_for_schedule: boolean;
  writes_to_tables: string[];
  writes_project_cards: boolean;
  writes_nexus_events: boolean;
  required_env: string[];
  required_connector: string | null;
  last_run_source: string;
  proof_event_type: string;
  next_action: string;
  disabled_reason: string | null;
}

export const NEXUS_DEPARTMENT_FEEDERS: NexusDepartmentFeeder[] = [
  {
    feeder_id: 'watched_resource_registry',
    name: 'Watched Resource Registry',
    owning_department: 'source_intake',
    owner_tab: 'intake',
    purpose: 'Save valuable resources as assets Nexus can backfill/watch over time.',
    source_type: 'watched_resources',
    script_or_process: 'scripts/research/watched_resource_registry.py',
    manual_command: 'python3 scripts/research/watched_resource_registry.py --dry-run --json',
    schedule_recommendation: 'No schedule. Registry changes are manual and Ray-approved.',
    enabled_state: 'manual_only',
    risk_level: 'low',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    required_connector: null,
    last_run_source: 'reports/manual_publish/watched_resource_registry_latest.md',
    proof_event_type: 'watched_resource_created',
    next_action: 'Add resources disabled by default; enable only after Ray approval.',
    disabled_reason: null,
  },
  {
    feeder_id: 'watched_resource_watch',
    name: 'Watched Resource Watch',
    owning_department: 'source_intake',
    owner_tab: 'intake',
    purpose: 'Check approved/enabled resources for new items and route scored findings.',
    source_type: 'approved_watched_resources',
    script_or_process: 'scripts/research/run_watched_resource_watch.py',
    manual_command: 'python3 scripts/research/run_watched_resource_watch.py --dry-run --limit 3 --no-external-ai --json',
    schedule_recommendation: 'Future daily/weekly after Ray approves scheduler activation.',
    enabled_state: 'ready_for_schedule',
    risk_level: 'medium',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'research_sources', 'transcript_reviews', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    required_connector: 'YouTube/RSS metadata only when approved',
    last_run_source: 'reports/manual_publish/watched_resource_watch_latest.md',
    proof_event_type: 'watched_resource_update_created',
    next_action: 'Manual watch dry-run now; scheduler activation remains disabled.',
    disabled_reason: null,
  },
  {
    feeder_id: 'research_content_growth_engine',
    name: 'Research + Content Growth Engine',
    owning_department: 'growth',
    owner_tab: 'seo',
    purpose: 'Turn research, keywords, affiliates, content tests, and experiments into department project cards.',
    source_type: 'keywords/affiliates/content_tests/experiments',
    script_or_process: 'scripts/research/*',
    manual_command: 'python3 scripts/research/seo_affiliate_content_planner.py --dry-run --limit 5 --no-external-ai --json',
    schedule_recommendation: 'Manual now; future daily digest after Ray approval.',
    enabled_state: 'manual_only',
    risk_level: 'medium',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    required_connector: null,
    last_run_source: 'reports/manual_publish/nexus_research_content_growth_engine_latest.md',
    proof_event_type: 'research_content_growth_candidate_created',
    next_action: 'Run scouts dry-run and convert high-value findings into experiments.',
    disabled_reason: null,
  },
  {
    feeder_id: 'daily_department_digest',
    name: 'Daily Department Digest',
    owning_department: 'command_center',
    owner_tab: 'command',
    purpose: 'Run the safe department feeder sequence manually and summarize project-card candidates.',
    source_type: 'department_feeders',
    script_or_process: 'scripts/automation/run_daily_department_digest.py',
    manual_command: 'python3 scripts/automation/run_daily_department_digest.py --dry-run --limit-per-feeder 3 --no-external-ai --skip-capture',
    schedule_recommendation: 'Daily morning after Ray approves scheduler activation; currently manual only.',
    enabled_state: 'ready_for_schedule',
    risk_level: 'medium',
    approval_required_for_schedule: true,
    writes_to_tables: ['reports/runtime', 'reports/manual_publish', 'optional task_requests', 'optional nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    required_connector: null,
    last_run_source: 'reports/manual_publish/daily_department_digest_latest.md',
    proof_event_type: 'daily_department_digest_completed',
    next_action: 'Run dry-run manually; scheduler activation requires Ray approval.',
    disabled_reason: null,
  },
  {
    feeder_id: 'source_intake_enrichment_backfill',
    name: 'Source Intake Enrichment Backfill',
    owning_department: 'source_intake',
    owner_tab: 'intake',
    purpose: 'Backfill deterministic project_enrichment for historical saved research sources.',
    source_type: 'research_sources',
    script_or_process: 'scripts/intake/backfill_project_enrichment.py',
    manual_command: 'python3 scripts/intake/backfill_project_enrichment.py --dry-run --limit 10 --no-external-ai',
    schedule_recommendation: 'Manual only. Schedule later only after Ray approves metadata-only backfill cadence.',
    enabled_state: 'manual_only',
    risk_level: 'low',
    approval_required_for_schedule: true,
    writes_to_tables: ['research_sources.metadata', 'transcript_reviews.metadata', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    required_connector: null,
    last_run_source: 'reports/manual_publish/nexus_project_enrichment_backfill_latest.md',
    proof_event_type: 'project_enrichment_backfilled',
    next_action: 'Run dry-run, then bounded live metadata-only backfill when safe.',
    disabled_reason: null,
  },
  {
    feeder_id: 'notebooklm_connector_status_feeder',
    name: 'NotebookLM Connector Status',
    owning_department: 'source_intake',
    owner_tab: 'intake',
    purpose: 'Report optional NotebookLM connector readiness without requiring credentials or sessions.',
    source_type: 'connector_status',
    script_or_process: 'scripts/intake/notebooklm_connector.py',
    manual_command: 'python3 scripts/intake/notebooklm_connector.py --dry-run --mode status --json',
    schedule_recommendation: 'No schedule. Connector actions require explicit Ray-approved setup.',
    enabled_state: 'needs_connector',
    risk_level: 'medium',
    approval_required_for_schedule: true,
    writes_to_tables: ['reports/runtime', 'reports/manual_publish'],
    writes_project_cards: false,
    writes_nexus_events: false,
    required_env: [],
    required_connector: 'Optional NotebookLM account/session kept outside repo',
    last_run_source: 'reports/manual_publish/notebooklm_connector_latest.md',
    proof_event_type: 'notebooklm_connector_status_reported',
    next_action: 'Use local direct enrichment/capture worker until NotebookLM is configured safely.',
    disabled_reason: 'NotebookLM connector is optional and not configured by default.',
  },
  {
    feeder_id: 'direct_source_enrichment_feeder',
    name: 'Direct Source Enrichment',
    owning_department: 'source_intake',
    owner_tab: 'intake',
    purpose: 'Create metadata-first deterministic enrichment from one explicit public URL.',
    source_type: 'explicit_public_url',
    script_or_process: 'scripts/intake/direct_source_enrichment.py',
    manual_command: 'python3 scripts/intake/direct_source_enrichment.py --source-url "<public-url>" --title "<title>" --dry-run --no-external-ai --json',
    schedule_recommendation: 'No schedule; use for one-off Source Intake.',
    enabled_state: 'manual_only',
    risk_level: 'low',
    approval_required_for_schedule: true,
    writes_to_tables: ['research_sources.metadata', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    required_connector: null,
    last_run_source: 'reports/manual_publish/direct_source_enrichment_latest.md',
    proof_event_type: 'direct_source_enrichment_created',
    next_action: 'Use dry-run first for one explicit public source; live metadata write is bounded.',
    disabled_reason: null,
  },
  {
    feeder_id: 'source_capture_queue_worker',
    name: 'Source Capture Queue Worker',
    owning_department: 'source_intake',
    owner_tab: 'intake',
    purpose: 'Process already queued and policy-approved public YouTube capture requests.',
    source_type: 'task_requests',
    script_or_process: 'scripts/intake/run_capture_queue_worker.py',
    manual_command: 'python3 scripts/intake/run_capture_queue_worker.py --once --limit 1 --dry-run --no-external-ai',
    schedule_recommendation: 'Manual only until Ray approves scheduler activation.',
    enabled_state: 'manual_only',
    risk_level: 'medium',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'research_sources', 'intake_events', 'transcript_reviews', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    required_connector: 'yt-dlp only during explicit live capture',
    last_run_source: 'reports/manual_publish/nexus_capture_queue_worker_latest.md',
    proof_event_type: 'source_enriched_for_project_card',
    next_action: 'Keep dry-run as the default; live run only for safe queued items.',
    disabled_reason: null,
  },
  {
    feeder_id: 'ops_improvement_research_feeder',
    name: 'Ops Improvement Research Feeder',
    owning_department: 'ops_improvements',
    owner_tab: 'ops',
    purpose: 'Read safe local docs/reports and propose system improvement task_requests.',
    source_type: 'docs_and_reports',
    script_or_process: 'scripts/automation/run_department_feeder.py',
    manual_command: 'python3 scripts/automation/run_department_feeder.py --feeder-id ops_improvement_research_feeder --dry-run --limit 5 --no-external-ai',
    schedule_recommendation: 'Weekly manual review; scheduler requires Ray approval.',
    enabled_state: 'manual_only',
    risk_level: 'low',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    required_connector: null,
    last_run_source: 'reports/manual_publish/nexus_department_automation_feeders_latest.md',
    proof_event_type: 'department_feeder_ops_improvement_reported',
    next_action: 'Dry-run candidate creation from existing safe reports; live writes deferred.',
    disabled_reason: null,
  },
  {
    feeder_id: 'opportunity_lab_research_feeder',
    name: 'Opportunity Lab Research Feeder',
    owning_department: 'opportunity_lab',
    owner_tab: 'opportunities',
    purpose: 'Promote enriched monetization candidates from research_sources/transcript_reviews into Opportunity Lab work.',
    source_type: 'enriched_research',
    script_or_process: 'scripts/automation/run_department_feeder.py',
    manual_command: 'python3 scripts/automation/run_department_feeder.py --feeder-id opportunity_lab_research_feeder --dry-run --limit 5 --no-external-ai',
    schedule_recommendation: 'Daily candidate review after Ray approves scheduler.',
    enabled_state: 'manual_only',
    risk_level: 'low',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    required_connector: null,
    last_run_source: 'reports/manual_publish/nexus_department_automation_feeders_latest.md',
    proof_event_type: 'opportunity_lab_project_created',
    next_action: 'Dry-run promotion candidates, then run bounded live creation only after reviewing candidates.',
    disabled_reason: null,
  },
  {
    feeder_id: 'creative_studio_project_feeder',
    name: 'Creative Studio Project Feeder',
    owning_department: 'creative_studio',
    owner_tab: 'creative',
    purpose: 'Map existing creative assets, social drafts, reports, and creative research into Creative Studio project work.',
    source_type: 'creative_assets/social_posts/enriched_research',
    script_or_process: 'scripts/automation/run_department_feeder.py',
    manual_command: 'python3 scripts/automation/run_department_feeder.py --feeder-id creative_studio_project_feeder --dry-run --limit 5 --no-external-ai',
    schedule_recommendation: 'Manual campaign review; no publish automation.',
    enabled_state: 'manual_only',
    risk_level: 'medium',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    required_connector: null,
    last_run_source: 'reports/manual_publish/nexus_department_automation_feeders_latest.md',
    proof_event_type: 'creative_studio_project_created',
    next_action: 'Dry-run creative draft candidates; publish remains approval-gated and unexecuted.',
    disabled_reason: null,
  },
  {
    feeder_id: 'seo_marketing_project_feeder',
    name: 'SEO / Marketing Project Feeder',
    owning_department: 'growth',
    owner_tab: 'seo',
    purpose: 'Create Growth project candidates from existing SEO rows/reports.',
    source_type: 'seo_reports/enriched_research',
    script_or_process: 'scripts/automation/run_department_feeder.py',
    manual_command: 'python3 scripts/automation/run_department_feeder.py --feeder-id seo_marketing_project_feeder --dry-run --limit 5 --no-external-ai',
    schedule_recommendation: 'Daily after GSC/GA/DataForSEO connectors are explicitly approved.',
    enabled_state: 'manual_only',
    risk_level: 'medium',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: [],
    required_connector: 'Optional future GSC/GA/DataForSEO connector',
    last_run_source: 'reports/manual_publish/nexus_department_automation_feeders_latest.md',
    proof_event_type: 'seo_marketing_project_created',
    next_action: 'Dry-run existing growth inputs; connector-backed scans remain future work.',
    disabled_reason: null,
  },
  {
    feeder_id: 'design_library_project_feeder',
    name: 'Design Library Project Feeder',
    owning_department: 'design_library',
    owner_tab: 'design',
    purpose: 'Organize existing design inspiration, packets, and UI reviews into design project cards.',
    source_type: 'design_tables/creative_assets/enriched_research',
    script_or_process: 'scripts/design/*',
    manual_command: 'python3 scripts/automation/run_department_feeder.py --feeder-id design_library_project_feeder --dry-run --limit 5 --no-external-ai',
    schedule_recommendation: 'Weekly manual review; scheduler later with approval.',
    enabled_state: 'manual_only',
    risk_level: 'low',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    required_connector: null,
    last_run_source: 'reports/manual_publish/nexus_department_automation_feeders_latest.md',
    proof_event_type: 'design_library_project_created',
    next_action: 'Dry-run existing design rows; no public use or image generation.',
    disabled_reason: null,
  },
  {
    feeder_id: 'agent_jobs_process_feeder',
    name: 'Agent Jobs Process Feeder',
    owning_department: 'agent_jobs',
    owner_tab: 'jobs',
    purpose: 'Summarize job/process state and propose safe task requests.',
    source_type: 'agent_jobs/task_requests/reports',
    script_or_process: 'scripts/automation/run_department_feeder.py',
    manual_command: 'python3 scripts/automation/run_department_feeder.py --feeder-id agent_jobs_process_feeder --dry-run --limit 5 --no-external-ai',
    schedule_recommendation: 'Manual status report; scheduler later with approval.',
    enabled_state: 'manual_only',
    risk_level: 'low',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    required_connector: null,
    last_run_source: 'reports/manual_publish/nexus_department_automation_feeders_latest.md',
    proof_event_type: 'agent_job_project_created',
    next_action: 'Dry-run job/process summaries; do not run or schedule jobs.',
    disabled_reason: null,
  },
  {
    feeder_id: 'command_center_summary_feeder',
    name: 'Command Center Summary Feeder',
    owning_department: 'command_center',
    owner_tab: 'command',
    purpose: 'Summarize department feeder states for the Executive Office.',
    source_type: 'feeder_registry',
    script_or_process: 'src/config/nexusDepartmentFeeders.ts',
    manual_command: 'python3 scripts/automation/run_department_feeder.py --feeder-id command_center_summary_feeder --dry-run --limit 5 --no-external-ai',
    schedule_recommendation: 'Rendered live from config/events; no scheduler needed.',
    enabled_state: 'manual_only',
    risk_level: 'low',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: [],
    required_connector: null,
    last_run_source: 'src/config/nexusDepartmentFeeders.ts',
    proof_event_type: 'command_center_summary_created',
    next_action: 'Dry-run executive summary; no actions are executed.',
    disabled_reason: null,
  },
  {
    feeder_id: 'approvals_decision_desk_feeder',
    name: 'Approvals Decision Desk Feeder',
    owning_department: 'approvals',
    owner_tab: 'approvals',
    purpose: 'Surface approval-required items; never auto-approve.',
    source_type: 'approvals',
    script_or_process: 'universal action policy',
    manual_command: 'python3 scripts/automation/run_department_feeder.py --feeder-id approvals_decision_desk_feeder --dry-run --limit 5 --no-external-ai',
    schedule_recommendation: 'No scheduler; human decision desk.',
    enabled_state: 'manual_only',
    risk_level: 'medium',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: [],
    required_connector: null,
    last_run_source: 'approvals table',
    proof_event_type: 'approval_decision_project_created',
    next_action: 'Dry-run approval decision cards; never approve or reject.',
    disabled_reason: null,
  },
  {
    feeder_id: 'events_feed_ledger_feeder',
    name: 'Events Feed Ledger Feeder',
    owning_department: 'events_feed',
    owner_tab: 'events',
    purpose: 'Proof/history ledger populated by other feeders and actions.',
    source_type: 'nexus_events',
    script_or_process: 'nexus_events writers',
    manual_command: 'python3 scripts/automation/run_department_feeder.py --feeder-id events_feed_ledger_feeder --dry-run --limit 5 --no-external-ai',
    schedule_recommendation: 'No scheduler; event writers append proof.',
    enabled_state: 'manual_only',
    risk_level: 'low',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: [],
    required_connector: null,
    last_run_source: 'nexus_events',
    proof_event_type: 'event_ledger_summary_created',
    next_action: 'Dry-run proof summaries; never modify historical events.',
    disabled_reason: null,
  },
  {
    feeder_id: 'integrations_status_feeder',
    name: 'Integrations Status Feeder',
    owning_department: 'integrations',
    owner_tab: 'integrations',
    purpose: 'Show connector readiness without exposing secrets.',
    source_type: 'integration_registry',
    script_or_process: 'npm run nexus:watch',
    manual_command: 'python3 scripts/automation/run_department_feeder.py --feeder-id integrations_status_feeder --dry-run --limit 5 --no-external-ai',
    schedule_recommendation: 'Manual only; scheduler requires Ray approval.',
    enabled_state: 'manual_only',
    risk_level: 'medium',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: [],
    required_connector: null,
    last_run_source: 'reports/runtime/nexus_watch_report_latest.md',
    proof_event_type: 'integration_status_project_created',
    next_action: 'Dry-run connector status cards; never modify credentials.',
    disabled_reason: null,
  },
  {
    feeder_id: 'goclear_revenue_hub_feeder',
    name: 'GoClear Revenue Hub Feeder',
    owning_department: 'opportunity_lab',
    owner_tab: 'goclear',
    purpose: 'Create GoClear/Apex revenue metric cards from safe existing Nexus tasks, research, and local reports.',
    source_type: 'task_requests/research_sources/reports',
    script_or_process: 'scripts/automation/feeders/goclear_revenue_hub_feeder.py',
    manual_command: 'python3 scripts/automation/run_department_feeder.py --feeder-id goclear_revenue_hub_feeder --dry-run --limit 5 --no-external-ai',
    schedule_recommendation: 'Daily with department digest after Ray approves scheduler activation.',
    enabled_state: 'manual_only',
    risk_level: 'low',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    required_connector: null,
    last_run_source: 'reports/manual_publish/nexus_grouped_next_layer_latest.md',
    proof_event_type: 'goclear_revenue_hub_metrics_updated',
    next_action: 'Run dry-run; connect safe revenue/referral source later.',
    disabled_reason: null,
  },
  {
    feeder_id: 'trading_lab_demo_research_feeder',
    name: 'Trading Lab Demo Research Feeder',
    owning_department: 'trading_lab',
    owner_tab: 'trading',
    purpose: 'Demo/research-only trading ideas; live trading is blocked.',
    source_type: 'vibe_trading_status/backtests/paper_reports',
    script_or_process: 'scripts/automation/run_department_feeder.py',
    manual_command: 'python3 scripts/automation/run_department_feeder.py --feeder-id trading_lab_demo_research_feeder --dry-run --limit 5 --no-external-ai',
    schedule_recommendation: 'Disabled until demo-only source is approved; live trading never scheduled here.',
    enabled_state: 'manual_only',
    risk_level: 'high',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: [],
    required_connector: 'Vibe Trading paper/demo status only',
    last_run_source: 'reports/manual_publish/nexus_trading_lab_vibe_integration_latest.md',
    proof_event_type: 'trading_lab_research_project_created',
    next_action: 'Dry-run paper/demo research cards only; live trading remains blocked.',
    disabled_reason: null,
  },
];

export function feedersForTab(tabId: string): NexusDepartmentFeeder[] {
  return NEXUS_DEPARTMENT_FEEDERS.filter((f) => f.owner_tab === tabId);
}

export function feedersForDepartment(department: NexusDepartment): NexusDepartmentFeeder[] {
  return NEXUS_DEPARTMENT_FEEDERS.filter((f) => f.owning_department === department);
}

export function feederById(feederId: string): NexusDepartmentFeeder | undefined {
  return NEXUS_DEPARTMENT_FEEDERS.find((f) => f.feeder_id === feederId);
}

export function feederStateCounts(feeders = NEXUS_DEPARTMENT_FEEDERS): Record<NexusFeederEnabledState, number> {
  return feeders.reduce<Record<NexusFeederEnabledState, number>>((acc, feeder) => {
    acc[feeder.enabled_state] += 1;
    return acc;
  }, { manual_only: 0, ready_for_schedule: 0, disabled: 0, blocked: 0, needs_connector: 0 });
}
