import type { NexusDepartment } from './nexusProjectTypes';

export type NexusFeederEnabledState =
  | 'manual_only'
  | 'ready_for_schedule'
  | 'disabled'
  | 'blocked'
  | 'needs_connector';

export type NexusFeederRiskLevel = 'low' | 'medium' | 'high';

export interface NexusDepartmentFeeder {
  feeder_id: string;
  name: string;
  owning_department: NexusDepartment;
  owner_tab: string;
  purpose: string;
  source_type: string;
  script_or_process: string;
  manual_command: string;
  schedule_recommendation: string;
  enabled_state: NexusFeederEnabledState;
  risk_level: NexusFeederRiskLevel;
  approval_required_for_schedule: boolean;
  writes_to_tables: string[];
  writes_project_cards: boolean;
  writes_nexus_events: boolean;
  required_env: string[];
  required_connector: string | null;
  last_run_source: string;
  proof_event_type: string;
  next_action: string;
  disabled_reason: string | null;
}

export const NEXUS_DEPARTMENT_FEEDERS: NexusDepartmentFeeder[] = [
  {
    feeder_id: 'source_intake_enrichment_backfill',
    name: 'Source Intake Enrichment Backfill',
    owning_department: 'source_intake',
    owner_tab: 'intake',
    purpose: 'Backfill deterministic project_enrichment for historical saved research sources.',
    source_type: 'research_sources',
    script_or_process: 'scripts/intake/backfill_project_enrichment.py',
    manual_command: 'python3 scripts/intake/backfill_project_enrichment.py --dry-run --limit 10 --no-external-ai',
    schedule_recommendation: 'Manual only. Schedule later only after Ray approves metadata-only backfill cadence.',
    enabled_state: 'manual_only',
    risk_level: 'low',
    approval_required_for_schedule: true,
    writes_to_tables: ['research_sources.metadata', 'transcript_reviews.metadata', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    required_connector: null,
    last_run_source: 'reports/manual_publish/nexus_project_enrichment_backfill_latest.md',
    proof_event_type: 'project_enrichment_backfilled',
    next_action: 'Run dry-run, then bounded live metadata-only backfill when safe.',
    disabled_reason: null,
  },
  {
    feeder_id: 'source_capture_queue_worker',
    name: 'Source Capture Queue Worker',
    owning_department: 'source_intake',
    owner_tab: 'intake',
    purpose: 'Process already queued and policy-approved public YouTube capture requests.',
    source_type: 'task_requests',
    script_or_process: 'scripts/intake/run_capture_queue_worker.py',
    manual_command: 'python3 scripts/intake/run_capture_queue_worker.py --once --limit 1 --dry-run --no-external-ai',
    schedule_recommendation: 'Manual only until Ray approves scheduler activation.',
    enabled_state: 'manual_only',
    risk_level: 'medium',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'research_sources', 'intake_events', 'transcript_reviews', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    required_connector: 'yt-dlp only during explicit live capture',
    last_run_source: 'reports/manual_publish/nexus_capture_queue_worker_latest.md',
    proof_event_type: 'source_enriched_for_project_card',
    next_action: 'Keep dry-run as the default; live run only for safe queued items.',
    disabled_reason: null,
  },
  {
    feeder_id: 'ops_improvement_research_feeder',
    name: 'Ops Improvement Research Feeder',
    owning_department: 'ops_improvements',
    owner_tab: 'ops',
    purpose: 'Read safe local docs/reports and propose system improvement task_requests.',
    source_type: 'docs_and_reports',
    script_or_process: 'scripts/automation/run_department_feeder.py',
    manual_command: 'python3 scripts/automation/run_department_feeder.py --feeder-id ops_improvement_research_feeder --dry-run --limit 5 --no-external-ai',
    schedule_recommendation: 'Weekly manual review; scheduler requires Ray approval.',
    enabled_state: 'manual_only',
    risk_level: 'low',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    required_connector: null,
    last_run_source: 'reports/manual_publish/nexus_department_automation_feeders_latest.md',
    proof_event_type: 'department_feeder_ops_improvement_reported',
    next_action: 'Dry-run candidate creation from existing safe reports; live writes deferred.',
    disabled_reason: null,
  },
  {
    feeder_id: 'opportunity_lab_research_feeder',
    name: 'Opportunity Lab Research Feeder',
    owning_department: 'opportunity_lab',
    owner_tab: 'opportunities',
    purpose: 'Promote enriched monetization candidates from research_sources/transcript_reviews into Opportunity Lab work.',
    source_type: 'enriched_research',
    script_or_process: 'scripts/automation/run_department_feeder.py',
    manual_command: 'python3 scripts/automation/run_department_feeder.py --feeder-id opportunity_lab_research_feeder --dry-run --limit 5 --no-external-ai',
    schedule_recommendation: 'Daily candidate review after Ray approves scheduler.',
    enabled_state: 'manual_only',
    risk_level: 'low',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    required_connector: null,
    last_run_source: 'reports/manual_publish/nexus_department_automation_feeders_latest.md',
    proof_event_type: 'department_feeder_opportunity_reported',
    next_action: 'Dry-run promotion candidates; live creation can be added after review.',
    disabled_reason: null,
  },
  {
    feeder_id: 'creative_design_project_feeder',
    name: 'Creative and Design Project Feeder',
    owning_department: 'creative_studio',
    owner_tab: 'creative',
    purpose: 'Map existing creative assets, social drafts, and design reports into Creative/Design project work.',
    source_type: 'creative_assets',
    script_or_process: 'scripts/automation/run_department_feeder.py',
    manual_command: 'python3 scripts/automation/run_department_feeder.py --feeder-id creative_design_project_feeder --dry-run --limit 5 --no-external-ai',
    schedule_recommendation: 'Manual campaign review; no publish automation.',
    enabled_state: 'manual_only',
    risk_level: 'medium',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'creative_assets.metadata', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    required_connector: null,
    last_run_source: 'reports/manual_publish/nexus_department_automation_feeders_latest.md',
    proof_event_type: 'department_feeder_creative_design_reported',
    next_action: 'Dry-run candidate mapping; publish remains approval-gated.',
    disabled_reason: null,
  },
  {
    feeder_id: 'seo_marketing_project_feeder',
    name: 'SEO / Marketing Project Feeder',
    owning_department: 'growth',
    owner_tab: 'seo',
    purpose: 'Create Growth project candidates from existing SEO rows/reports.',
    source_type: 'seo_reports',
    script_or_process: 'scripts/automation/run_department_feeder.py',
    manual_command: 'python3 scripts/automation/run_department_feeder.py --feeder-id seo_marketing_project_feeder --dry-run --limit 5 --no-external-ai',
    schedule_recommendation: 'Daily after GSC/GA/DataForSEO connectors are explicitly approved.',
    enabled_state: 'needs_connector',
    risk_level: 'medium',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'seo_opportunities', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: [],
    required_connector: 'GSC/GA/DataForSEO or seeded seo_opportunities',
    last_run_source: 'reports/manual_publish/nexus_department_automation_feeders_latest.md',
    proof_event_type: 'department_feeder_seo_reported',
    next_action: 'Seed or connect SEO inputs before live feeder writes.',
    disabled_reason: 'SEO source connector/input is not ready.',
  },
  {
    feeder_id: 'design_library_asset_organizer',
    name: 'Design Library Asset Organizer',
    owning_department: 'design_library',
    owner_tab: 'design',
    purpose: 'Organize existing design inspiration, packets, and UI reviews into design project cards.',
    source_type: 'design_tables',
    script_or_process: 'scripts/design/*',
    manual_command: 'python3 scripts/automation/run_department_feeder.py --feeder-id design_library_asset_organizer --dry-run --limit 5 --no-external-ai',
    schedule_recommendation: 'Weekly manual review; scheduler later with approval.',
    enabled_state: 'manual_only',
    risk_level: 'low',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    required_connector: null,
    last_run_source: 'reports/manual_publish/nexus_department_automation_feeders_latest.md',
    proof_event_type: 'department_feeder_design_reported',
    next_action: 'Dry-run existing design rows; live writes deferred.',
    disabled_reason: null,
  },
  {
    feeder_id: 'agent_jobs_process_registry_feeder',
    name: 'Agent Jobs Process Registry Feeder',
    owning_department: 'agent_jobs',
    owner_tab: 'jobs',
    purpose: 'Summarize job/process state and propose safe task requests.',
    source_type: 'agent_jobs',
    script_or_process: 'scripts/automation/run_department_feeder.py',
    manual_command: 'python3 scripts/automation/run_department_feeder.py --feeder-id agent_jobs_process_registry_feeder --dry-run --limit 5 --no-external-ai',
    schedule_recommendation: 'Manual status report; scheduler later with approval.',
    enabled_state: 'manual_only',
    risk_level: 'low',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: ['SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY'],
    required_connector: null,
    last_run_source: 'reports/manual_publish/nexus_department_automation_feeders_latest.md',
    proof_event_type: 'department_feeder_agent_jobs_reported',
    next_action: 'Dry-run job/process summary.',
    disabled_reason: null,
  },
  {
    feeder_id: 'command_center_executive_summary_feeder',
    name: 'Command Center Executive Summary Feeder',
    owning_department: 'command_center',
    owner_tab: 'command',
    purpose: 'Summarize department feeder states for the Executive Office.',
    source_type: 'feeder_registry',
    script_or_process: 'src/config/nexusDepartmentFeeders.ts',
    manual_command: 'python3 scripts/automation/run_department_feeder.py --department command_center --dry-run --limit 5 --no-external-ai',
    schedule_recommendation: 'Rendered live from config/events; no scheduler needed.',
    enabled_state: 'manual_only',
    risk_level: 'low',
    approval_required_for_schedule: true,
    writes_to_tables: ['nexus_events'],
    writes_project_cards: false,
    writes_nexus_events: true,
    required_env: [],
    required_connector: null,
    last_run_source: 'src/config/nexusDepartmentFeeders.ts',
    proof_event_type: 'department_feeder_command_center_reported',
    next_action: 'Review feeder summary in Command Center.',
    disabled_reason: null,
  },
  {
    feeder_id: 'approvals_decision_desk_feeder',
    name: 'Approvals Decision Desk Feeder',
    owning_department: 'approvals',
    owner_tab: 'approvals',
    purpose: 'Surface approval-required items; never auto-approve.',
    source_type: 'approvals',
    script_or_process: 'universal action policy',
    manual_command: 'Open Approvals tab',
    schedule_recommendation: 'No scheduler; human decision desk.',
    enabled_state: 'manual_only',
    risk_level: 'medium',
    approval_required_for_schedule: true,
    writes_to_tables: ['approvals', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: [],
    required_connector: null,
    last_run_source: 'approvals table',
    proof_event_type: 'approval_required',
    next_action: 'Ray reviews pending approvals manually.',
    disabled_reason: null,
  },
  {
    feeder_id: 'events_feed_ledger_feeder',
    name: 'Events Feed Ledger Feeder',
    owning_department: 'events_feed',
    owner_tab: 'events',
    purpose: 'Proof/history ledger populated by other feeders and actions.',
    source_type: 'nexus_events',
    script_or_process: 'nexus_events writers',
    manual_command: 'Open Events Feed tab',
    schedule_recommendation: 'No scheduler; event writers append proof.',
    enabled_state: 'manual_only',
    risk_level: 'low',
    approval_required_for_schedule: true,
    writes_to_tables: ['nexus_events'],
    writes_project_cards: false,
    writes_nexus_events: true,
    required_env: [],
    required_connector: null,
    last_run_source: 'nexus_events',
    proof_event_type: 'nexus_event',
    next_action: 'Use as proof stream for feeder runs.',
    disabled_reason: null,
  },
  {
    feeder_id: 'integrations_connection_status_feeder',
    name: 'Integrations Connection Status Feeder',
    owning_department: 'integrations',
    owner_tab: 'integrations',
    purpose: 'Show connector readiness without exposing secrets.',
    source_type: 'integration_registry',
    script_or_process: 'npm run nexus:watch',
    manual_command: 'npm run nexus:watch',
    schedule_recommendation: 'Manual only; scheduler requires Ray approval.',
    enabled_state: 'manual_only',
    risk_level: 'medium',
    approval_required_for_schedule: true,
    writes_to_tables: ['system_health', 'nexus_events'],
    writes_project_cards: false,
    writes_nexus_events: true,
    required_env: [],
    required_connector: null,
    last_run_source: 'reports/runtime/nexus_watch_report_latest.md',
    proof_event_type: 'integration_status_reported',
    next_action: 'Run manual watch report; never print secrets.',
    disabled_reason: null,
  },
  {
    feeder_id: 'trading_lab_demo_research_feeder',
    name: 'Trading Lab Demo Research Feeder',
    owning_department: 'trading_lab',
    owner_tab: 'trading',
    purpose: 'Demo/research-only trading ideas; live trading is blocked.',
    source_type: 'demo_research',
    script_or_process: 'scripts/automation/run_department_feeder.py',
    manual_command: 'python3 scripts/automation/run_department_feeder.py --feeder-id trading_lab_demo_research_feeder --dry-run --limit 5 --no-external-ai',
    schedule_recommendation: 'Disabled until demo-only source is approved; live trading never scheduled here.',
    enabled_state: 'blocked',
    risk_level: 'high',
    approval_required_for_schedule: true,
    writes_to_tables: ['task_requests', 'nexus_events'],
    writes_project_cards: true,
    writes_nexus_events: true,
    required_env: [],
    required_connector: null,
    last_run_source: 'manual demo research only',
    proof_event_type: 'department_feeder_trading_demo_reported',
    next_action: 'Keep research-only; do not place trades.',
    disabled_reason: 'Live trading is blocked; demo feeder requires explicit Ray approval.',
  },
];

export function feedersForTab(tabId: string): NexusDepartmentFeeder[] {
  return NEXUS_DEPARTMENT_FEEDERS.filter((f) => f.owner_tab === tabId);
}

export function feedersForDepartment(department: NexusDepartment): NexusDepartmentFeeder[] {
  return NEXUS_DEPARTMENT_FEEDERS.filter((f) => f.owning_department === department);
}

export function feederById(feederId: string): NexusDepartmentFeeder | undefined {
  return NEXUS_DEPARTMENT_FEEDERS.find((f) => f.feeder_id === feederId);
}

export function feederStateCounts(feeders = NEXUS_DEPARTMENT_FEEDERS): Record<NexusFeederEnabledState, number> {
  return feeders.reduce<Record<NexusFeederEnabledState, number>>((acc, feeder) => {
    acc[feeder.enabled_state] += 1;
    return acc;
  }, { manual_only: 0, ready_for_schedule: 0, disabled: 0, blocked: 0, needs_connector: 0 });
}
