/**
 * Nexus automation category matrix — applies the three automation levels to every Nexus category.
 *
 * For each category this declares:
 *  - level_1_allowed_actions      (Autonomous Internal — no Ray approval per item)
 *  - level_2_approval_gated_actions (prepare automatically, Ray approves before execution)
 *  - level_3_blocked_actions      (blocked unless a separate contract/design is approved)
 *
 * Pure / deterministic. No I/O. Never weakens publish/send/trade/deploy gates.
 */
import type { NexusDepartment } from './nexusProjectTypes';
import { AUTOMATION_CATEGORIES, type AutomationCategoryId } from './nexusAutomationCategories';

export interface AutomationCategoryMatrixEntry {
  category_id: AutomationCategoryId;
  category_name: string;
  owner_department: NexusDepartment;
  level_1_allowed_actions: string[];
  level_2_approval_gated_actions: string[];
  level_3_blocked_actions: string[];
  risk_notes: string;
  next_recommended_action: string;
}

const NAME = (id: AutomationCategoryId) => AUTOMATION_CATEGORIES.find((c) => c.category_id === id)!.category_name;
const DEPT = (id: AutomationCategoryId): NexusDepartment => AUTOMATION_CATEGORIES.find((c) => c.category_id === id)!.owner_department;

function entry(
  category_id: AutomationCategoryId,
  level_1_allowed_actions: string[],
  level_2_approval_gated_actions: string[],
  level_3_blocked_actions: string[],
  risk_notes: string,
  next_recommended_action: string,
): AutomationCategoryMatrixEntry {
  return {
    category_id,
    category_name: NAME(category_id),
    owner_department: DEPT(category_id),
    level_1_allowed_actions,
    level_2_approval_gated_actions,
    level_3_blocked_actions,
    risk_notes,
    next_recommended_action,
  };
}

export const AUTOMATION_CATEGORY_MATRIX: AutomationCategoryMatrixEntry[] = [
  entry('research_source_intake',
    ['source intake enrichment', 'scoring', 'routing', 'internal cards', 'internal reports'],
    ['connector activation for live source pulls', 'scheduler activation'],
    ['broad scraping', 'external AI on sensitive/private/customer data'],
    'Internal research is safe; broad scraping and sensitive external AI are blocked.',
    'Keep enrichment/scoring autonomous; leave live connectors and scheduler as approval-gated.'),
  entry('youtube_research',
    ['metadata check (placeholder/fallback)', 'transcript review from local samples', 'scoring/routing', 'internal reports', 'Hermes prep brief'],
    ['metadata connector activation', 'scheduler activation', 'publish of derived content'],
    ['YouTube media downloads', 'broad scraping'],
    'Metadata-only is safe; media downloads are blocked. Connector is currently not_configured.',
    'Run metadata/transcript dry-runs; keep connector + scheduler approval-gated.'),
  entry('seo_marketing',
    ['SEO keyword scoring', 'opportunity scoring', 'internal cards/reports'],
    ['publishing to site', 'site/production change', 'scheduler activation'],
    ['production deploy of site changes', 'external AI on sensitive data'],
    'Scoring is internal; publishing/site changes leave the building.',
    'Keep keyword scoring autonomous; gate any publish/site change.'),
  entry('affiliate_marketing',
    ['affiliate opportunity scoring', 'partner research', 'internal cards/reports'],
    ['publishing affiliate content', 'outbound partner contact'],
    ['spend/commitment actions', 'broad scraping of partner sites'],
    'Scoring is internal; outbound partner contact and publishing are gated.',
    'Keep opportunity scoring autonomous; gate outbound/publish.'),
  entry('content_opportunity_lab',
    ['content opportunity scoring', 'experiment cards', 'internal reports'],
    ['publishing content', 'sending content', 'scheduler activation'],
    ['external AI on sensitive/customer data'],
    'Idea/experiment work is internal; publishing/sending are gated.',
    'Keep experiment cards autonomous; gate publish/send.'),
  entry('creative_studio',
    ['draft creative generation', 'internal review cards', 'internal reports'],
    ['publishing creative', 'sending creative to clients', 'ad creative activation'],
    ['external AI on sensitive/customer data', 'spend on paid creative tools'],
    'Drafts are internal until publish/send; then gated.',
    'Keep drafting autonomous; gate publish/send/client delivery.'),
  entry('design_library',
    ['design library organization', 'tagging', 'internal cards/reports'],
    ['publishing assets externally', 'client delivery'],
    ['external AI on sensitive/customer data'],
    'Organization is internal; external delivery is gated.',
    'Keep organizer autonomous; gate external delivery.'),
  entry('goclear_revenue_hub',
    ['internal revenue metric cards', 'internal reports', 'scoring'],
    ['lead contact', 'payment-link creation', 'campaign publishing', 'scheduler activation'],
    ['payment/spend actions', 'destructive DB writes'],
    'Internal cards are safe; lead contact and payment links leave the building.',
    'Keep revenue cards autonomous; gate lead contact and payment links.'),
  entry('goclear_apex_client_intake',
    ['lead scoring', 'readiness checklist', 'internal cards/reports'],
    ['client notification', 'client contact', 'client-facing scheduling'],
    ['client data exposure externally', 'external AI on customer data'],
    'Scoring/checklists are internal; client contact is gated; client data exposure is blocked.',
    'Keep scoring/checklists autonomous; gate client contact.'),
  entry('credit_repair_funding_guidance',
    ['internal guidance research', 'scoring', 'internal reports'],
    ['client-facing guidance delivery', 'client contact'],
    ['compliance-sensitive claims published without review', 'external AI on credit-sensitive data'],
    'High compliance risk. Research internal; client delivery gated; sensitive external AI blocked.',
    'Keep research autonomous; gate all client-facing delivery; compliance review required.'),
  entry('opportunity_lab',
    ['opportunity research', 'scoring', 'routing', 'internal cards/reports'],
    ['outbound contact', 'publishing', 'scheduler activation'],
    ['broad scraping', 'external AI on sensitive data'],
    'Research is internal; outbound/publish gated; broad scraping blocked.',
    'Keep opportunity research autonomous; gate outbound/publish.'),
  entry('agent_jobs',
    ['job status reporting', 'internal cards', 'internal reports'],
    ['scheduler activation', 'enabling persistent jobs'],
    ['raw auto_executor exposure', 'destructive job actions'],
    'Status is internal; persistent jobs gated; raw auto_executor blocked.',
    'Keep status feeder autonomous; gate scheduler/persistent jobs.'),
  entry('integrations',
    ['integration status reporting', 'internal cards/reports'],
    ['connector activation', 'OAuth setup', 'credential connection'],
    ['credential changes without review', 'connecting sensitive systems', 'secret printing'],
    'Status is internal; connector activation gated; credential changes blocked.',
    'Keep status feeder autonomous; gate connector activation.'),
  entry('events_feed_proof_ledger',
    ['internal proof events', 'internal reports', 'ledger reads'],
    [],
    ['destructive ledger writes', 'tampering with proof history'],
    'Proof logging is internal and append-only; destructive ledger writes are blocked.',
    'Keep proof logging autonomous; never allow destructive ledger writes.'),
  entry('approvals',
    ['approvals reporting (read-only)', 'internal decision briefs'],
    ['Ray decision execution of an approved item'],
    ['auto-approving high-risk items', 'bypassing approval gates'],
    'Reporting is internal; the Ray decision itself is gated; auto-approval blocked.',
    'Keep approvals reporting autonomous; require Ray for each decision.'),
  entry('ray_review_queue',
    ['queue building from true decisions', 'internal reports'],
    ['marking an item approved/executed'],
    ['auto-executing queued items'],
    'Building the queue is internal; execution requires Ray; auto-execute blocked.',
    'Keep queue builder autonomous; never auto-execute queued items.'),
  entry('hermes_jarvis',
    ['internal recommendations', 'prep briefs', 'summaries', 'internal reports'],
    ['Mac/computer-control bridge activation', 'outbound actions on Ray behalf'],
    ['raw command execution from browser', 'external AI on sensitive data'],
    'Recommendations are internal; bridge/outbound actions gated; raw command execution blocked.',
    'Keep Hermes recommendations autonomous; gate any bridge/outbound execution.'),
  entry('trading_lab',
    ['paper-only strategy research', 'backtest imports (local)', 'scoring', 'internal reports'],
    [],
    ['live trading', 'broker execution', 'funded account actions', 'raw auto_executor exposure'],
    'Paper-only research is internal. Live trading/broker/funded actions are BLOCKED Level 3.',
    'Keep paper-only research autonomous; live execution stays blocked under its own contract.'),
  entry('scheduler_automation',
    ['scheduler candidate proposals (proposal-only)', 'internal reports'],
    ['scheduler activation', 'enabling persistent automation'],
    ['cron/launchd/systemd creation without approval'],
    'Proposals are internal; activation is gated; unapproved persistent jobs blocked.',
    'Generate candidates only; never activate a scheduler without Ray approval.'),
  entry('production_deployment',
    ['deploy readiness reports (internal)'],
    ['production change proposal'],
    ['production deploys', 'destructive production actions'],
    'Readiness reporting internal; production deploys blocked unless separately approved.',
    'Keep readiness reporting autonomous; deploys stay blocked/gated.'),
  entry('email_sms_dm_social',
    ['draft messages', 'internal review cards'],
    ['sending email/SMS/DM', 'social posting', 'campaign publishing'],
    ['bulk send', 'spam automation'],
    'Drafts internal; sending is gated; bulk/spam send blocked.',
    'Keep drafting autonomous; gate every send; block bulk/spam.'),
  entry('ads_spend',
    ['ad opportunity research', 'internal cards/reports'],
    ['ad campaign activation proposal'],
    ['ad spend activation', 'payment charges'],
    'Research internal; spend blocked. No money leaves without separate approval.',
    'Keep ad research autonomous; spend stays blocked/gated.'),
  entry('database_supabase',
    ['read-only queries', 'internal schema reports'],
    ['schema change proposal'],
    ['destructive DB writes', 'RLS weakening', 'tenant isolation bypass'],
    'Reads internal; destructive writes / RLS weakening blocked.',
    'Keep reads autonomous; block destructive DB and RLS changes.'),
  entry('files_reports_imports',
    ['local report generation', 'safe local imports', 'internal cards'],
    [],
    ['committing .env/secrets', 'broad scraping into imports'],
    'Local reports/imports internal; secret commits and broad-scrape imports blocked.',
    'Keep local report generation autonomous; never commit secrets.'),
  entry('notebooklm_research_library',
    ['library organization', 'internal summaries', 'internal reports'],
    ['connector activation'],
    ['external AI on sensitive/customer data'],
    'Library organization internal; connector gated; sensitive external AI blocked.',
    'Keep library organization autonomous; gate connector activation.'),
  entry('grants_funding_opportunities',
    ['grant opportunity research', 'scoring', 'internal cards/reports'],
    ['application submission', 'outbound contact'],
    ['spend/commitment actions'],
    'Research internal; submissions/outbound gated.',
    'Keep grant research autonomous; gate submissions/outbound.'),
  entry('business_credit_vendor_accounts',
    ['vendor research', 'scoring', 'internal cards/reports'],
    ['account application', 'outbound vendor contact'],
    ['credential changes', 'spend/commitment actions'],
    'Research internal; applications/contact gated; credential changes blocked.',
    'Keep vendor research autonomous; gate applications/contact.'),
  entry('client_portal',
    ['internal portal content drafts', 'internal reports'],
    ['client-facing portal publishing', 'client notification'],
    ['client data exposure externally', 'external AI on customer data'],
    'Drafts internal; client-facing publishing gated; client data exposure blocked.',
    'Keep portal drafts autonomous; gate client-facing publishing.'),
  entry('admin_tenants_users',
    ['internal admin reporting (read-only)'],
    ['tenant/user configuration change proposal'],
    ['tenant isolation bypass', 'destructive admin actions', 'credential changes'],
    'Reporting internal; config changes gated; isolation bypass blocked.',
    'Keep admin reporting autonomous; gate config changes; block isolation bypass.'),
  entry('monitoring_health',
    ['health checks', 'internal status reports', 'proof events'],
    [],
    ['destructive remediation without approval'],
    'Monitoring is internal; destructive auto-remediation blocked.',
    'Keep monitoring autonomous; gate any destructive remediation.'),
];

export function getCategoryMatrixEntry(id: AutomationCategoryId): AutomationCategoryMatrixEntry | undefined {
  return AUTOMATION_CATEGORY_MATRIX.find((e) => e.category_id === id);
}
