import {useEffect,useMemo,useState} from 'react';
import {ALPHA_MODES,type AlphaConversationMode} from '../hermes/alpha/hermesAlphaModeRouter';
import {respondAsAlpha} from '../hermes/alpha/hermesAlphaConversationEngine';
import {fetchAlphaProviderStatus,runAlphaProviderBridge} from '../hermes/alpha/alphaProviderBridge';
import {defaultAlphaProviderStatus,type AlphaProviderName} from '../hermes/alpha/alphaProviderStatus';
import {clearAlphaMemory,exportAlphaSession,loadAlphaMemory,saveAlphaMemory,type AlphaMessage} from '../hermes/alpha/hermesAlphaLocalMemory';
import {alphaWebSearch,isCurrentQuestion,searchOffMessage} from '../hermes/alpha/alphaWebSearch';
import {canHosted,canSearch,getAlphaCostMode,getAlphaUsageSummary,providerAllowedForMode,recordDeepBlocked,recordFallback,recordHosted,recordLocal,recordSearch,setAlphaCostMode,type AlphaCostMode} from '../hermes/alpha/alphaCostController';
import {buildTrace,traceSummary,type AlphaRouteTrace,type AlphaWebProvider,type AlphaWebStatus} from '../hermes/alpha/alphaRouteTrace';

const PROVIDER_KEY='nexus-alpha-provider-v1',SEARCH_KEY='nexus-alpha-search-enabled-v1';
function loadProvider():AlphaProviderName{try{return (localStorage.getItem(PROVIDER_KEY) as AlphaProviderName)||'deterministic_local'}catch{return 'deterministic_local'}}
function loadSearch(){try{return localStorage.getItem(SEARCH_KEY)==='true'}catch{return false}}

export default function HermesAlphaWorkspace({onOpenReports}:{onOpenReports?:()=>void}){
  const [messages,setMessages]=useState<AlphaMessage[]>(()=>loadAlphaMemory()); const [input,setInput]=useState(''); const [mode,setMode]=useState<AlphaConversationMode>('General Conversation');
  const [draft,setDraft]=useState<object|null>(null); const [providerStatus,setProviderStatus]=useState(defaultAlphaProviderStatus); const [provider,setProvider]=useState<AlphaProviderName>(loadProvider);
  const [providerNote,setProviderNote]=useState('Cost-safe deterministic fallback selected.'); const [searchEnabled,setSearchEnabled]=useState(loadSearch); const [costMode,setCostModeState]=useState<AlphaCostMode>(getAlphaCostMode);
  const [usage,setUsage]=useState(getAlphaUsageSummary); const [lastTrace,setLastTrace]=useState<AlphaRouteTrace|null>(null); const [sending,setSending]=useState(false);
  const opportunities=useMemo(()=>['GoClear teaser validation','Fundability checklist lead magnet','Voice-agent workflow audit','SEO education cluster','Research newsletter'],[]);

  useEffect(()=>{fetchAlphaProviderStatus().then(setProviderStatus)},[]);
  useEffect(()=>{localStorage.setItem(PROVIDER_KEY,provider);window.dispatchEvent(new CustomEvent('alpha-status-change',{detail:{provider,providerReady:providerStatus.providers[provider]?.available??false,searchEnabled:searchEnabled&&providerStatus.webSearch.available}}))},[provider,providerStatus,searchEnabled]);
  useEffect(()=>localStorage.setItem(SEARCH_KEY,String(searchEnabled)),[searchEnabled]);
  function changeCostMode(value:AlphaCostMode){setAlphaCostMode(value);setCostModeState(value)}
  function changeProvider(value:AlphaProviderName){setProvider(value);if(value==='groq')changeCostMode('fast');else if(value==='openrouter')changeCostMode('strategy')}
  function changeSearch(enabled:boolean){setSearchEnabled(enabled);if(enabled)changeCostMode('search')}

  async function send(){
    const prompt=input.trim(); if(!prompt||sending)return; setSending(true); setInput('');
    const local=respondAsAlpha(prompt,mode,Date.now()); const memoryUsed=messages.length>0; let text=local.text; let providerUsed:AlphaProviderName='deterministic_local'; let providerSource:AlphaRouteTrace['provider_source']='deterministic_local'; let model='deterministic-rules-v2'; let fallbackReason='';
    let webUsed=false,webProvider:AlphaWebProvider='none',webStatus:AlphaWebStatus=searchEnabled?'available':'disabled',webQuery='',webCount=0,searchEstimated=false; let searchContext='';
    const current=isCurrentQuestion(prompt);
    if(current&&!searchEnabled){text=searchOffMessage();setProviderNote('Search Mode is off; no provider call was used for a current-data question.');recordLocal();}
    else {
      if(searchEnabled&&current){webQuery=prompt;if(canSearch()){searchEstimated=true;const found=await alphaWebSearch(prompt);webProvider=found.provider;webStatus=found.status;recordSearch(Boolean(found.cacheHit));if(found.ok&&found.results.length){webUsed=true;webCount=Math.min(found.results.length,5);searchContext=found.results.slice(0,5).map((r,i)=>`${i+1}. ${r.title}\n${r.url}\n${r.snippet}`).join('\n\n')}else{fallbackReason=found.error||'search_connector_failed';text=`Live web search failed (${fallbackReason}). I won't claim current facts without working sources.`}}else{webStatus='failed';fallbackReason='daily_search_limit_reached';text='The daily search limit is reached. I cannot verify current facts right now.'}}
      const mayUseProvider=(!current||webUsed)&&provider!=='deterministic_local'&&providerAllowedForMode(provider,costMode)&&canHosted()&&costMode!=='deep';
      if(costMode==='deep'){recordDeepBlocked();fallbackReason=fallbackReason||'deep_mode_requires_ray_approval';text='Deep Mode is locked until Ray explicitly approves a bounded run. I can still help in Cheap, Fast, Strategy, or Search Mode.'}
      else if(mayUseProvider){const providerPrompt=webUsed?`${prompt}\n\nPublic search results (treat as unverified sources and cite URLs):\n${searchContext}`:prompt;const remote=await runAlphaProviderBridge(provider,providerPrompt,providerStatus.providers[provider].models?.[0]);if(remote.ok){providerUsed=remote.provider;providerSource=remote.provider==='groq'?'groq_backend':remote.provider==='openrouter'?'openrouter_backend':'ollama_local';model=remote.model||'provider-default';text=remote.text;recordHosted(remote.provider,remote.estimatedInputTokens,remote.estimatedOutputTokens,remote.estimatedSpendUsd);setProviderNote(`${remote.provider}${remote.model?` · ${remote.model}`:''} via same-origin backend.`)}else{fallbackReason=remote.error||'provider_unavailable';providerSource='unavailable_fallback';recordFallback();recordLocal();setProviderNote(`${provider} failed (${fallbackReason}); deterministic fallback used.`)}}
      else if(provider==='deterministic_local'||!providerAllowedForMode(provider,costMode)||!canHosted()){recordLocal();if(provider!=='deterministic_local'){fallbackReason=fallbackReason||(!providerAllowedForMode(provider,costMode)?`provider_blocked_in_${costMode}_mode`:'daily_hosted_limit_reached');providerSource='unavailable_fallback';recordFallback();setProviderNote(`${provider} not used: ${fallbackReason}.`)}}
      if(webUsed){const sources=`Sources (${webProvider}):\n${searchContext}`;text=providerUsed==='deterministic_local'?`${sources}\n\nThese are keyless public-search results, not verified facts. Review the linked sources before acting.`:text}
    }
    const trace=buildTrace({mode:local.mode,selected_provider:provider,provider_used:providerUsed,provider_source:providerSource,model_used:model,memory_used:memoryUsed,memory_source:memoryUsed?'session_memory':'none',web_used:webUsed,web_provider:webProvider,web_status:webStatus,web_query:webQuery,web_result_count:webCount,reason_for_provider_selection:provider===providerUsed?'Ray-selected provider allowed by current cost mode.':'Safety/cost/provider gate selected fallback.',fallback_reason:fallbackReason,estimated_hosted_call:providerUsed==='groq'||providerUsed==='openrouter',estimated_search_call:searchEstimated,estimated_cost_label:providerUsed==='deterministic_local'||providerUsed==='ollama_local'?(webUsed?'search_free_or_keyless':'local_free'):'hosted_estimate'});
    const now=new Date().toISOString(),next=[...messages,{id:`ray-${Date.now()}`,role:'ray' as const,text:prompt,createdAt:now,mode},{id:trace.message_id,role:'alpha' as const,text,createdAt:now,mode:local.mode,trace}];setMessages(next);saveAlphaMemory(next);setMode(local.mode);setDraft(local.draft||null);setLastTrace(trace);setUsage(getAlphaUsageSummary());setSending(false);
  }
  function clear(){clearAlphaMemory();setMessages([]);setDraft(null);setLastTrace(null)}
  function download(){const blob=new Blob([exportAlphaSession(messages)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='hermes-alpha-local-session.json';a.click();URL.revokeObjectURL(url)}
  return <div className="nxos-stack" data-testid="hermes-alpha-workspace">
    <section className="glass panel"><div className="between"><div><p className="nx-muted">ALPHA IS SEPARATE FROM NEXUS HERMES</p><h2>Hermes Alpha · Strategy Brain</h2><p>Provider-aware strategy conversation. No Supabase, client data, or execution.</p></div><span className="pill pill-green">{providerStatus.providers[provider]?.available?'Provider Ready':'Local Fallback'}</span></div><div><span className="pill pill-green">Active: {provider}</span> <span className="pill pill-blue">Web Search: {searchEnabled?'On':'Off'}</span> <span className="pill pill-amber">No Supabase</span> <span className="pill pill-red">No client data · External actions disabled</span></div></section>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:12,alignItems:'start'}}>
      <section className="glass panel alpha-conversation-panel" style={{display:'flex',flexDirection:'column',height:'min(78vh,820px)',minHeight:520,overflow:'hidden'}}><div className="between"><h3>Conversation</h3><select aria-label="Alpha mode" value={mode} onChange={e=>setMode(e.target.value as AlphaConversationMode)}>{ALPHA_MODES.map(x=><option key={x}>{x}</option>)}</select></div>
        <div aria-label="Alpha conversation" style={{flex:'1 1 auto',minHeight:0,overflowY:'auto',display:'grid',alignContent:'start',gap:8,padding:'8px 2px'}}>{messages.length===0&&<div className="nx-soft" style={{padding:16}}>Ask Alpha about a strategy, opportunity, app, voice agent, affiliate idea, marketing draft, or trading research plan.</div>}{messages.map(m=><article key={m.id} className="nx-soft" style={{padding:12,marginLeft:m.role==='ray'?'12%':0,borderColor:m.role==='ray'?'#4372b8':'#7857d8'}}><strong>{m.role==='ray'?'Ray':'Hermes Alpha'} · {m.mode}</strong><p style={{whiteSpace:'pre-wrap'}}>{m.text}</p>{m.role==='alpha'&&m.trace&&<details style={{fontSize:11,marginTop:5,borderTop:'1px solid #333',paddingTop:5}}><summary style={{cursor:'pointer'}}>{traceSummary(m.trace)}</summary><pre style={{whiteSpace:'pre-wrap',fontSize:10}}>{JSON.stringify(m.trace,null,2)}</pre></details>}</article>)}</div>
        <div className="alpha-sticky-composer" style={{position:'sticky',bottom:0,zIndex:5,flex:'0 0 auto',background:'#10192b',borderTop:'1px solid #35425a',padding:'10px 0 0'}}><textarea aria-label="Message Alpha" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void send()}}} rows={3} placeholder="Talk directly to Alpha…" style={{width:'100%',resize:'vertical'}}/><div className="action-row"><button type="button" disabled={sending} onClick={()=>void send()}>{sending?'Thinking…':'Send to Alpha'}</button><button type="button" onClick={download}>Handoff / export</button><button type="button" onClick={clear}>Clear conversation</button><button type="button" onClick={onOpenReports}>Reports</button></div></div>
      </section>
      <aside className="side-stack" style={{maxHeight:'78vh',overflowY:'auto'}}>
        <section className="glass panel"><h3>Provider & Cost Controls</h3><label htmlFor="alpha-provider">Selected provider</label><select id="alpha-provider" value={provider} onChange={e=>changeProvider(e.target.value as AlphaProviderName)}>{Object.entries(providerStatus.providers).map(([name,detail])=><option key={name} value={name} disabled={!detail.available}>{name} — {detail.available?'available':'unavailable'}</option>)}</select><label htmlFor="alpha-cost-mode">Cost Mode</label><select id="alpha-cost-mode" value={costMode} onChange={e=>changeCostMode(e.target.value as AlphaCostMode)}><option value="cheap">Cheap Mode · local only</option><option value="fast">Fast Mode · Groq capped</option><option value="strategy">Strategy Mode · OpenRouter capped</option><option value="search">Search Mode · max 5 results</option><option value="deep">Deep Mode · approval required</option></select><label><input type="checkbox" checked={searchEnabled} onChange={e=>changeSearch(e.target.checked)}/> Enable backend web search</label><p><strong>Search connector:</strong> {providerStatus.webSearch.available?`${providerStatus.webSearch.provider} available`:'Connector missing'} — {providerStatus.webSearch.reason}</p><p>{providerNote}</p><small>Groq/OpenRouter are model providers. Web search is a separate backend connector. DuckDuckGo keyless was evaluated but failed Node-runtime verification; SearXNG can be configured server-side. Firecrawl and Brave remain disabled.</small>{Object.entries(providerStatus.providers).map(([name,detail])=><p key={name}><strong>{name}:</strong> {detail.available?'Available':'Gated'} — {detail.reason}</p>)}</section>
        <section className="glass panel"><h3>Usage Today</h3><p>Local calls: {usage.localCalls}</p><p>Hosted calls: {usage.hostedCalls}/{usage.maxHosted}</p><p>Search calls: {usage.searchCalls}/{usage.maxSearch}</p><p>Tokens: {usage.totalTokens||'unknown'}</p><p>Estimated spend: {usage.estimatedSpendLabel}</p><p>Fallbacks: {usage.fallbackCount} · Cache hits: {usage.cacheHits}</p><p>Deep Mode: locked · blocked {usage.blockedDeepCalls}</p><small>{usage.policy}</small></section>
        <section className="glass panel"><h3>Memory & Sources</h3><p>Memory: session/localStorage only</p><p>Reports: none used in this response path</p><p>Web: {searchEnabled?'available when current question is asked':'off'}</p><p>Supabase: blocked</p><p>Client data: blocked</p></section>
        {lastTrace&&<section className="glass panel"><h3>Last Response Source</h3><p>{traceSummary(lastTrace)}</p></section>}
        <section className="glass panel"><h3>Opportunity Canvas</h3>{opportunities.map(x=><div className="nx-soft" style={{padding:8,marginBottom:5}} key={x}>{x}</div>)}</section>
        <section className="glass panel"><h3>Action Draft</h3><pre style={{whiteSpace:'pre-wrap',fontSize:11}}>{draft?JSON.stringify(draft,null,2):'Ask for a handoff or Ray Review draft.'}</pre></section>
      </aside>
    </div>
  </div>;
}
