import {useEffect,useMemo,useState} from 'react';
import {ALPHA_MODES,type AlphaConversationMode} from '../hermes/alpha/hermesAlphaModeRouter';
import {respondAsAlpha} from '../hermes/alpha/hermesAlphaConversationEngine';
import {fetchAlphaProviderStatus,runAlphaProviderBridge} from '../hermes/alpha/alphaProviderBridge';
import {defaultAlphaProviderStatus,type AlphaProviderName} from '../hermes/alpha/alphaProviderStatus';
import {clearAlphaMemory,exportAlphaSession,loadAlphaMemory,saveAlphaMemory,type AlphaMessage} from '../hermes/alpha/hermesAlphaLocalMemory';
export default function HermesAlphaWorkspace({onOpenReports}:{onOpenReports?:()=>void}){const [messages,setMessages]=useState<AlphaMessage[]>(()=>loadAlphaMemory());const [input,setInput]=useState('');const [mode,setMode]=useState<AlphaConversationMode>('General Conversation');const [draft,setDraft]=useState<object|null>(null);const [providerStatus,setProviderStatus]=useState(defaultAlphaProviderStatus);const [provider,setProvider]=useState<AlphaProviderName>('deterministic_local');const [providerNote,setProviderNote]=useState('Local deterministic fallback—no model or web call.');const opportunities=useMemo(()=>["GoClear teaser validation","Fundability checklist lead magnet","Voice-agent workflow audit","SEO education cluster","Research newsletter"],[]);
 useEffect(()=>{fetchAlphaProviderStatus().then(status=>{setProviderStatus(status);if(status.providers.ollama_local.available)setProvider('ollama_local')})},[]);
 async function send(){const p=input.trim();if(!p)return;const local=respondAsAlpha(p,mode);let text=local.text;if(provider!=='deterministic_local'){const remote=await runAlphaProviderBridge(provider,p,providerStatus.providers[provider].models?.[0]);if(remote.ok){text=remote.text;setProviderNote(`${remote.provider}${remote.model?` · ${remote.model}`:''} — provider response through same-origin bridge.`)}else setProviderNote(`${provider} unavailable (${remote.error}); deterministic local fallback used.`)}else setProviderNote('Local deterministic fallback—no model or web call.');const now=new Date().toISOString();const next=[...messages,{id:`ray-${Date.now()}`,role:'ray' as const,text:p,createdAt:now,mode},{id:`alpha-${Date.now()}`,role:'alpha' as const,text,createdAt:now,mode:local.mode}];setMessages(next);saveAlphaMemory(next);setMode(local.mode);setDraft(local.draft||null);setInput('')}
 function clear(){clearAlphaMemory();setMessages([]);setDraft(null)} function download(){const blob=new Blob([exportAlphaSession(messages)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='hermes-alpha-local-session.json';a.click();URL.revokeObjectURL(url)}
 return <div className="nxos-stack" data-testid="hermes-alpha-workspace"><section className="glass panel"><div className="between"><div><p className="nx-muted">ALPHA IS SEPARATE FROM NEXUS HERMES</p><h2>Hermes Alpha Conversation Workspace</h2><p>Direct Alpha conversation. No Nexus Hermes routing, Supabase, client data, or execution.</p></div><span className="pill pill-green">Conversational · Provider-aware</span></div><div><span className="pill pill-green">Active: {provider}</span> <span className="pill pill-amber">Live web unavailable</span> <span className="pill pill-green">Supabase not connected</span> <span className="pill pill-red">Client data blocked · External actions disabled</span></div></section>
 <div style={{display:'grid',gridTemplateColumns:'minmax(0,2fr) minmax(280px,1fr)',gap:12}}><section className="glass panel"><div className="between"><h3>Conversation</h3><select aria-label="Alpha mode" value={mode} onChange={e=>setMode(e.target.value as AlphaConversationMode)}>{ALPHA_MODES.map(x=><option key={x}>{x}</option>)}</select></div><div aria-label="Alpha conversation" style={{minHeight:360,maxHeight:520,overflowY:'auto',display:'grid',gap:8,padding:'8px 0'}}>{messages.length===0&&<div className="nx-soft" style={{padding:16}}>Ask Alpha about a business idea, SEO opportunity, landing page, app, voice agent, affiliate strategy, or trading research plan.</div>}{messages.map(m=><article key={m.id} className="nx-soft" style={{padding:12,marginLeft:m.role==='ray'?'12%':0,borderColor:m.role==='ray'?'#4372b8':'#7857d8'}}><strong>{m.role==='ray'?'Ray':'Hermes Alpha'} · {m.mode}</strong><p style={{whiteSpace:'pre-wrap'}}>{m.text}</p></article>)}</div><textarea aria-label="Message Alpha" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} rows={3} placeholder="Talk directly to Alpha…" style={{width:'100%'}}/><div className="action-row"><button type="button" onClick={send}>Send to Alpha</button><button type="button" onClick={download}>Handoff / export</button><button type="button" onClick={clear}>Clear conversation</button><button type="button" onClick={onOpenReports}>Open Alpha reports</button></div></section>
 <aside className="side-stack"><section className="glass panel"><h3>Idea / Opportunity Canvas</h3>{opportunities.map(x=><div className="nx-soft" style={{padding:8,marginBottom:5}} key={x}>{x}</div>)}</section><section className="glass panel"><h3>Provider Status</h3><label htmlFor="alpha-provider">Active provider</label><select id="alpha-provider" value={provider} onChange={e=>setProvider(e.target.value as AlphaProviderName)}>{Object.entries(providerStatus.providers).map(([name,detail])=><option key={name} value={name} disabled={!detail.available}>{name} — {detail.available?'available':'unavailable'}</option>)}</select><p>{providerNote}</p>{Object.entries(providerStatus.providers).map(([name,detail])=><p key={name}><strong>{name}:</strong> {detail.available?'Available':'Missing/gated'} — {detail.reason}</p>)}<p><strong>Live web:</strong> unavailable</p><p><strong>Supabase:</strong> not connected</p><p><strong>Client data:</strong> blocked</p></section><section className="glass panel"><h3>Action Draft</h3><pre style={{whiteSpace:'pre-wrap',fontSize:11}}>{draft?JSON.stringify(draft,null,2):'Ask for a handoff or Ray Review draft.'}</pre></section><section className="glass panel"><h3>Local Session Memory</h3><p>{messages.length} messages in browser localStorage. No server persistence.</p></section></aside></div></div>}
