"""Build the shared operational truth consumed by Admin and Hermes.

Only operational metadata is emitted. Missing or stale sources remain
UNKNOWN/STALE; report text and registry presence cannot make a job RUNNING.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

from nexus_agent_platform.capability_broker import load_manifest
from nexus_agent_platform.process_broker import read_processes

ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = ROOT / "public/runtime/nexus-live-telemetry.json"
CAMPAIGN_PATH = ROOT / "data/runtime/nexus_completion_campaign.json"
PREFLIGHT_PATH = ROOT / "reports/runtime/capability_broker/executor_preflight.json"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _read(path: Path, default: Any) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError, TypeError):
        return default


def build_telemetry() -> Dict[str, Any]:
    manifest = load_manifest()
    preflight = _read(PREFLIGHT_PATH, {})
    campaign = _read(CAMPAIGN_PATH, {})
    processes = read_processes()
    matrix = preflight.get("matrix", []) if isinstance(preflight, dict) else []
    passed = sum(row.get("verified") is True for row in matrix)
    attempted = sum(row.get("executed") is True for row in matrix)
    failed = [row.get("capability_id") for row in matrix if row.get("verified") is False]
    return {
        "schema_version": "nexus.live-telemetry.v1", "generated_at": _now(),
        "source": "canonical_telemetry.build_telemetry", "read_only": True,
        "system": {"overall_status": "DEGRADED" if failed else "UNKNOWN" if not matrix else "HEALTHY",
                    "production_sha": "UNKNOWN", "last_natural_cycle": "UNKNOWN", "next_expected_cycle": "UNKNOWN"},
        "proof": {"coverage": round(passed / attempted, 3) if attempted else 0.0,
                   "verified_no_change": "UNKNOWN", "watchdog": "PASS" if any(row.get("capability_id") == "proof.watchdog" and row.get("verified") for row in matrix) else "UNKNOWN",
                   "stalled": [], "recovering": []},
        "active_jobs": processes.get("processes", []),
        "preflight": {"registered": len(manifest["capabilities"]), "attempted": attempted, "verified": passed,
                       "failed": failed, "ready_tonight": bool(preflight.get("ready_tonight"))},
        "campaign": {"campaign_id": campaign.get("campaign_id", "NEXUS_COMPLETION_DAY_2026_08_26"),
                     "status": campaign.get("status", "UNKNOWN"), "current_wave": campaign.get("current_wave", "UNKNOWN"),
                     "current_objective": campaign.get("current_objective", "UNKNOWN"),
                     "checkpoint_sha": campaign.get("checkpoint_sha", "UNKNOWN")},
        "repairs": {"automatic": [], "waiting_ray": campaign.get("true_gates", [])},
        "morning_report": {"status": "UNKNOWN", "source": "not generated by this read model"},
        "safety": {"arbitrary_shell": "PROHIBITED", "funded_trading": "PROHIBITED", "external_actions": "GOVERNED"},
    }


def write_telemetry(path: Path | None = None) -> Dict[str, Any]:
    payload = build_telemetry()
    path = path or OUTPUT_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    temporary.replace(path)
    return payload


if __name__ == "__main__":
    print(json.dumps(write_telemetry(), indent=2))
