"""Generate a redacted post-Keychain credential and loop readiness audit."""
from __future__ import annotations
import json, subprocess
from pathlib import Path
from nexus_agent_platform.credential_control_plane import write_reports

ROOT=Path(__file__).resolve().parents[2]; OUT=ROOT/'reports/certification'; PREV='87356da754b0994f3e0a5e8b3d77e713a4a2092f'
def load_previous():
    p=subprocess.run(['git','show',f'{PREV}:reports/runtime/nexus_credential_catalog_latest.json'],capture_output=True,text=True,check=False)
    try: return {x['credential_id']:x for x in json.loads(p.stdout).get('credentials',[])}
    except Exception: return {}
def main():
    current=write_reports(); previous=load_previous(); recovered=[]; still=[]
    for row in current['credentials']:
        before=previous.get(row['credential_id'],{}).get('result'); after=row.get('result')
        if before in {'MISSING','NOT_FOUND'} and after in {'AVAILABLE','CONFIGURED'} and row.get('source_found')==['MACOS_KEYCHAIN']: recovered.append({'credential_id':row['credential_id'],'before':before,'after':after,'source':'MACOS_KEYCHAIN'})
        if after in {'MISSING','NOT_FOUND'}: still.append(row['credential_id'])
    by={r['credential_id']:r for r in current['credentials']}
    def state(ids): return [{'credential_id':i,'state':by.get(i,{}).get('result','UNKNOWN'),'source':by.get(i,{}).get('source_found',[])} for i in ids]
    loops=[
      {'loop':'CONTINUOUS/AUTONOMY CORE','required_credentials':[],'credential_state':'NONE_REQUIRED','infrastructure_state':'existing deterministic runtime','authority_state':'deterministic authority','operational_now':'YES','blocker':None},
      {'loop':'ACTIVE OPERATOR','required_credentials':['credential.telegram.hermes.prod.v1','credential.supabase.admin.prod.v1'],'credential_state':state(['credential.telegram.hermes.prod.v1','credential.supabase.admin.prod.v1']),'infrastructure_state':'existing operator/runtime paths','authority_state':'outbound communication governed','operational_now':'PARTIAL','blocker':'no new credential blocker; outbound actions remain governed'},
      {'loop':'FOREX MARKET DATA SCANNER','required_credentials':['credential.oanda.market_data.practice.v1'],'credential_state':state(['credential.oanda.market_data.practice.v1']),'infrastructure_state':'OANDA Practice read checks passed','authority_state':'practice/paper only; live disabled','operational_now':'YES','blocker':None},
      {'loop':'ORACLE GEMMA BACKGROUND REASONING','required_credentials':[],'credential_state':'NONE_REQUIRED','infrastructure_state':'supervised private tunnel and Oracle Ollama','authority_state':'advisory only','operational_now':'YES','blocker':None},
      {'loop':'GENERAL WEB RESEARCH','required_credentials':['credential.searxng.web_search.prod.v1','credential.brave.web_search.prod.v1'],'credential_state':state(['credential.searxng.web_search.prod.v1','credential.brave.web_search.prod.v1']),'infrastructure_state':'SearXNG not installed; Brave configured','authority_state':'read-only','operational_now':'PARTIAL','blocker':'SearXNG installation pending; Brave provider payment-limited'},
      {'loop':'BRAVE WEB SEARCH','required_credentials':['credential.brave.web_search.prod.v1'],'credential_state':state(['credential.brave.web_search.prod.v1']),'infrastructure_state':'adapter/canary exists','authority_state':'read-only','operational_now':'PARTIAL','blocker':'provider HTTP 402/payment required'},
      {'loop':'SEARXNG WEB SEARCH','required_credentials':['credential.searxng.web_search.prod.v1'],'credential_state':state(['credential.searxng.web_search.prod.v1']),'infrastructure_state':'not installed','authority_state':'read-only','operational_now':'NO','blocker':'install/private endpoint approval required; base URL not yet applicable'},
      {'loop':'GOOGLE WORKSPACE','required_credentials':['credential.google.workspace.prod.v1'],'credential_state':state(['credential.google.workspace.prod.v1']),'infrastructure_state':'live read certification passed','authority_state':'read-only application contract','operational_now':'YES','blocker':None},
      {'loop':'YOUTUBE RESEARCH','required_credentials':['credential.google.youtube.prod.v1'],'credential_state':state(['credential.google.youtube.prod.v1']),'infrastructure_state':'metadata connector available','authority_state':'read-only','operational_now':'PARTIAL','blocker':'content/transcript scenario requires supplied URL and separate approval'},
      {'loop':'HERMES TELEGRAM / MOBILE','required_credentials':['credential.telegram.hermes.prod.v1'],'credential_state':state(['credential.telegram.hermes.prod.v1']),'infrastructure_state':'existing Telegram runtime','authority_state':'outbound gated','operational_now':'PARTIAL','blocker':'no credential blocker; outbound policy gate remains'},
      {'loop':'SUPABASE ADMIN','required_credentials':['credential.supabase.admin.prod.v1'],'credential_state':state(['credential.supabase.admin.prod.v1']),'infrastructure_state':'configured','authority_state':'admin gated','operational_now':'PARTIAL','blocker':'application-specific approval gates'},
      {'loop':'NETLIFY RELEASE','required_credentials':['credential.netlify.release.prod.v1'],'credential_state':state(['credential.netlify.release.prod.v1']),'infrastructure_state':'configured','authority_state':'release gated','operational_now':'PARTIAL','blocker':'release authority intentionally gated'},
      {'loop':'EMAIL / RESEND','required_credentials':['credential.resend.email.prod.v1'],'credential_state':state(['credential.resend.email.prod.v1']),'infrastructure_state':'configured','authority_state':'outbound gated','operational_now':'PARTIAL','blocker':'sending intentionally gated'},
      {'loop':'SOCIAL / META','required_credentials':['credential.meta.social.prod.v1'],'credential_state':state(['credential.meta.social.prod.v1']),'infrastructure_state':'configured','authority_state':'publishing gated','operational_now':'PARTIAL','blocker':'publishing intentionally gated'},
      {'loop':'VOICE / CLOUDFLARE','required_credentials':['credential.cloudflare.voice_service.prod.v1'],'credential_state':state(['credential.cloudflare.voice_service.prod.v1']),'infrastructure_state':'local voice path exists','authority_state':'read-only transport','operational_now':'NO','blocker':'Cloudflare voice credential missing; local voice can remain independent'},
      {'loop':'STRIPE / PAYMENTS','required_credentials':['credential.stripe.payments.test.v1'],'credential_state':state(['credential.stripe.payments.test.v1']),'infrastructure_state':'test integration configured','authority_state':'payments disabled','operational_now':'NO','blocker':'intentionally disabled; no credential action required'},
      {'loop':'OPTIONAL EXTERNAL MODEL PROVIDERS','required_credentials':['credential.openrouter.models.prod.v1','credential.openai.models.prod.v1','credential.groq.models.prod.v1','credential.google.gemini.prod.v1','credential.anthropic.models.prod.v1'],'credential_state':state(['credential.openrouter.models.prod.v1','credential.openai.models.prod.v1','credential.groq.models.prod.v1','credential.google.gemini.prod.v1','credential.anthropic.models.prod.v1']),'infrastructure_state':'Oracle Gemma available','authority_state':'advisory/read-only','operational_now':'PARTIAL','blocker':'optional providers missing; Oracle Gemma covers current reasoning lane'},
    ]
    report={'schema_version':'nexus.credential-recertification.v1','generated_at':current['generated_at'],'credential_count':len(current['credentials']),'recovered_after_keychain_fix':recovered,'still_missing':still,'classifications':{'RECOVERED_AFTER_KEYCHAIN_FIX':recovered,'STILL_MISSING':still,'CONFIGURED_HEALTHY':['credential.google.workspace.prod.v1','credential.oanda.market_data.practice.v1'],'PROVIDER_BLOCKED':['credential.brave.web_search.prod.v1'],'CONFIGURED_UNTESTED':[x['credential_id'] for x in current['credentials'] if x['result']=='AVAILABLE' and x['credential_id'] not in {'credential.google.workspace.prod.v1','credential.oanda.market_data.practice.v1'}]},'loops':loops,'required_current_core':['credential.oanda.market_data.practice.v1','credential.google.workspace.prod.v1'],'next_approved_capability':['credential.searxng.web_search.prod.v1'],'optional_fallbacks':['credential.brave.web_search.prod.v1','credential.openrouter.models.prod.v1'],'intentionally_disabled':['credential.stripe.payments.test.v1'],'user_action_required':[],'recommended_next_activation':'Install SearXNG privately after the separate VM audit/installation approval; no credential is required before installation.'}
    (OUT/'nexus_credential_recertification_latest.json').write_text(json.dumps(report,indent=2)+'\n')
    lines=['# Nexus Credential Recertification','','Fully redacted post-Keychain-fix audit.','',f"- registered identities: {len(current['credentials'])}",f"- recovered after Keychain fix: {len(recovered)}",f"- still missing: {len(still)}",'','## Recovered After Keychain Fix','']
    lines += [f"- `{x['credential_id']}`: {x['before']} -> {x['after']} via {x['source']}" for x in recovered] or ['- none']
    lines += ['', '## Loop Readiness', '', '| Loop | Credentials | Infrastructure | Authority | Operational now | Blocker |','|---|---|---|---|---|---|']
    for x in loops: lines.append(f"| {x['loop']} | {', '.join(x['required_credentials']) or 'none'} | {x['infrastructure_state']} | {x['authority_state']} | {x['operational_now']} | {x['blocker'] or 'none'} |")
    lines += ['', '## User Credential Actions', '', '- none. Missing identities are optional, provider-blocked, or infrastructure/authority gates.', '', '## Recommended Next Activation', '', report['recommended_next_activation']]
    (OUT/'nexus_credential_recertification_latest.md').write_text('\n'.join(lines)+'\n')
if __name__=='__main__': main()
