"""Feature flags for the Agent Platform.

All flags default to OFF.  Set to "true" in runtime.env to enable.
"""

from __future__ import annotations

import os


def _flag(name: str, default: str = "false") -> bool:
    return os.getenv(name, default).lower() == "true"


# Core platform
NEXUS_AGENT_PLATFORM_ENABLED = _flag("NEXUS_AGENT_PLATFORM_ENABLED")

# Hermes
NEXUS_HERMES_LANGGRAPH_ENABLED = _flag("NEXUS_HERMES_LANGGRAPH_ENABLED")
NEXUS_HERMES_CONVERSATIONAL_FRONT_BRAIN_ENABLED = _flag("NEXUS_HERMES_CONVERSATIONAL_FRONT_BRAIN_ENABLED")
LEGACY_HERMES_ROUTER_FALLBACK_ENABLED = _flag("LEGACY_HERMES_ROUTER_FALLBACK_ENABLED", "true")

# Alpha
ALPHA_LANGGRAPH_ENABLED = _flag("ALPHA_LANGGRAPH_ENABLED")

# Hermes Nova — isolated conversational agent
HERMES_NOVA_ENABLED = _flag("HERMES_NOVA_ENABLED")

# Infrastructure
TEMPORAL_WORKFLOWS_ENABLED = _flag("TEMPORAL_WORKFLOWS_ENABLED")
SCHEDULE_REPORT_EXECUTION_MODE = os.getenv("SCHEDULE_REPORT_EXECUTION_MODE", "local_file")
LITELLM_GATEWAY_ENABLED = _flag("LITELLM_GATEWAY_ENABLED")
LANGFUSE_TRACING_ENABLED = _flag("LANGFUSE_TRACING_ENABLED")

# Debug
AGENT_PLATFORM_DEBUG = _flag("AGENT_PLATFORM_DEBUG")


def status() -> dict[str, bool]:
    return {
        "NEXUS_AGENT_PLATFORM_ENABLED": NEXUS_AGENT_PLATFORM_ENABLED,
        "NEXUS_HERMES_LANGGRAPH_ENABLED": NEXUS_HERMES_LANGGRAPH_ENABLED,
        "NEXUS_HERMES_CONVERSATIONAL_FRONT_BRAIN_ENABLED": NEXUS_HERMES_CONVERSATIONAL_FRONT_BRAIN_ENABLED,
        "ALPHA_LANGGRAPH_ENABLED": ALPHA_LANGGRAPH_ENABLED,
        "HERMES_NOVA_ENABLED": HERMES_NOVA_ENABLED,
        "TEMPORAL_WORKFLOWS_ENABLED": TEMPORAL_WORKFLOWS_ENABLED,
        "SCHEDULE_REPORT_EXECUTION_MODE": SCHEDULE_REPORT_EXECUTION_MODE,
        "LITELLM_GATEWAY_ENABLED": LITELLM_GATEWAY_ENABLED,
        "LANGFUSE_TRACING_ENABLED": LANGFUSE_TRACING_ENABLED,
        "LEGACY_HERMES_ROUTER_FALLBACK_ENABLED": LEGACY_HERMES_ROUTER_FALLBACK_ENABLED,
        "AGENT_PLATFORM_DEBUG": AGENT_PLATFORM_DEBUG,
    }
