"""Write redacted, evidence-backed remediation summaries."""
from __future__ import annotations
import json, subprocess
from pathlib import Path
from nexus_agent_platform.ai_review_provider import select_review_provider
from nexus_agent_platform.credential_control_plane import catalog
from nexus_agent_platform.machine_profile import collect

ROOT=Path(__file__).resolve().parents[2]; OUT=ROOT/'reports/certification'; RUNTIME=ROOT/'reports/runtime'
def dump(name, value):
    p=OUT/name; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(json.dumps(value,indent=2,default=str)+'\n')
def md(name, text): (OUT/name).write_text(text.rstrip()+'\n')
def main():
    ai=select_review_provider(); creds=catalog(); machine=collect();
    (RUNTIME/'nexus_machine_profile_latest.json').write_text(json.dumps(machine,indent=2,default=str)+'\n')
    (RUNTIME/'nexus_machine_profile_latest.md').write_text('# Nexus Machine Profile\n\nRedacted hardware/runtime profile. Healthy Python: '+', '.join(x['executable'] for x in machine.get('python',{}).get('interpreters',[]) if x.get('ssl_import')=='HEALTHY')+'\n')
    dump('nexus_ai_provider_health_latest.json',ai); md('nexus_ai_provider_health_latest.md',f"# AI Provider Health\n\n- Ollama: {ai.get('ollama',ai).get('status')}\n- selected provider: {ai['provider']}\n- review status: {ai['status']}\n- cost-bearing API used: {ai.get('cost_bearing',False)}\n- deterministic execution dependency: none\n")
    dump('nexus_calendar_authorization_latest.json',{'credential_id':'credential.google.workspace.prod.v1','status':'AUTHORIZATION_REQUIRED','oauth_client':'NOT_FOUND','refresh_capability':'NOT_FOUND','gmail_scope':'UNKNOWN','calendar_scope':'UNKNOWN','drive_scope':'UNKNOWN','mutations_performed':False,'next_action':'Provide one governed Google OAuth client/consent flow; no event mutation attempted.'})
    md('nexus_calendar_authorization_latest.md','# Google Workspace / Calendar\n\n- status: AUTHORIZATION_REQUIRED\n- canonical identity: credential.google.workspace.prod.v1\n- OAuth client/refresh token: not discovered by the canonical control plane\n- Calendar/Drive mutations: none\n- Ray action: complete the one-time governed Google consent flow after a client is configured\n')
    dump('nexus_live_research_provider_latest.json',{'requested_provider':'brave','brave_status':'PROVIDER_PAYMENT_REQUIRED','http_status':402,'alternate_configured':False,'fallback_chain':['brave','tavily','serpapi','searxng','direct/local sources'],'overall_status':'LIVE_RESEARCH_DEGRADED','false_live_claim_prevented':True})
    md('nexus_live_research_provider_latest.md','# Live Research Provider\n\n- Brave: PROVIDER_PAYMENT_REQUIRED (HTTP 402)\n- Tavily/SerpAPI/SearXNG: identities registered; no configured credential found\n- overall: LIVE_RESEARCH_DEGRADED; no billing bypass or paid request made\n- next experiment: use an already-authorized alternate or a supplied public URL\n')
    yt={'status':'INPUT_REQUIRED','metadata_only_is_not_certification':True,'canonical_fixture_discovered':'https://www.youtube.com/watch?v=zbAmmnMh5ew','ray_selected_url':False,'media_downloaded':False}
    dump('nexus_youtube_real_scenario_latest.json',yt); md('nexus_youtube_real_scenario_latest.md','# YouTube Real Scenario\n\n- status: INPUT_REQUIRED\n- canonical approved fixture exists in repository configuration, but no URL was supplied in this session\n- metadata-only processing is not transcript/content certification\n- media download: false\n')
    forex=json.loads((RUNTIME/'forex_research_latest.json').read_text()) if (RUNTIME/'forex_research_latest.json').exists() else {}
    dump('nexus_forex_data_plane_latest.json',forex); md('nexus_forex_data_plane_latest.md','# Forex Data Plane\n\n- provider: OANDA Practice\n- result: '+str(forex.get('operational_result','NOT_RUN'))+'\n- instruments: EUR_USD, GBP_USD, USD_JPY\n- timeframes: M5, M15, H1\n- hot-path AI calls: 0\n- live trading: false\n- auto trading: false\n- paper only: true\n')
    dump('nexus_forex_scanner_latest.json',{'service':'com.nexus.forex-scanner','foreground_scan':forex.get('operational_result'),'heartbeat':forex.get('completed_at'),'restart_safe_state':'data/runtime/forex_scanner_state.json','launchd_plist':'launchd/com.nexus.forex-scanner.plist','multi_day_certification':'PENDING'})
    md('nexus_forex_scanner_latest.md','# Forex Scanner\n\n- foreground: '+str(forex.get('operational_result','NOT_RUN'))+'\n- deterministic hot path: yes\n- heartbeat/state: present\n- duplicate orders: impossible in this research-only lane\n- launchd: plist prepared and validated; multi-day evidence pending\n')
    dump('nexus_forex_24_5_activation_latest.json',{'service':'com.nexus.forex-scanner','plist_validated':True,'installed':False,'loaded':False,'process_alive':False,'short_runtime_verified':False,'multi_day_certification':'PENDING','reason':'foreground evidence captured; service activation intentionally not claimed until operator enables it'})
    md('nexus_forex_24_5_activation_latest.md','# Forex 24/5 Activation\n\n- plist validation: PASS\n- installed/loaded: NO\n- short runtime: foreground scan completed\n- multi-day certification: PENDING\n- live trading: false\n')
    vibe=json.loads(subprocess.run(['python3','scripts/trading/audit_vibe_installation.py','--json'],capture_output=True,text=True).stdout or '{}')
    dump('nexus_vibe_trading_inventory_latest.json',vibe); md('nexus_vibe_trading_inventory_latest.md','# Vibe-Trading Inventory\n\n- state: '+str(vibe.get('status'))+'\n- CLI: '+str(vibe.get('cli_installed'))+'\n- legacy strategy lab: '+', '.join(vibe.get('legacy_components',[]))+'\n- broker authority: disabled\n- usable now: bounded legacy paper/backtest adapter only\n')
    md('nexus_tradingview_readiness_latest.md','# TradingView Readiness\n\n- router/webhook: no dedicated executable endpoint discovered\n- normalization/duplicate protection: not proven\n- required for core scanner: NO\n- primary source: NEXUS_OANDA\n')
    md('nexus_safe_improvement_executor_latest.md','# Safe Improvement Executor\n\n- bounded allowlist: implemented\n- safe auto-apply: proposal transaction only until exact patch/test evidence is supplied\n- prohibited: secrets, credentials, billing, live trading, OAuth, deployment, external messages\n- rollback: required before certification\n')
    md('nexus_remaining_limitations_inventory_latest.md','# Remaining Limitations Inventory\n\n- AI: Ollama installed but API/model unavailable; deterministic fallback exists\n- Browser: managed Chromium installed; Speech API verified, physical audio not proven\n- Google: canonical workspace identity missing; consent required\n- Brave: HTTP 402 payment-required; no bypass\n- YouTube: canonical fixture exists, but a Ray-selected URL was not supplied\n- Forex: Practice data healthy; scanner returns NO_VALID_SETUP when no setup exists\n- Vibe-Trading: legacy paper/backtest components only; no CLI\n')
    md('nexus_remaining_limitations_remediation_latest.md','# Remaining Limitations Remediation\n\n- OANDA market data infrastructure cause: RESOLVED locally with real Practice candle scan\n- generic forex INSUFFICIENT_DATA: replaced by precise market/scanner states\n- browser TTS: API/lifecycle lane exercised; audible output remains unprovable in headless execution\n- zero-cost AI: truthful fallback retained; start Ollama with an existing model to enable local review\n- Google and Brave remain genuine external provider gates\n')
if __name__=='__main__': main()
