#!/usr/bin/env python3
import argparse,json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'activation'));from activation_common import ROOT,RUNTIME,write_report
def load(stem):
 try:return json.loads((RUNTIME/f'{stem}_latest.json').read_text())
 except:return {}
def main():
 a=argparse.ArgumentParser();a.add_argument('--json',action='store_true');x=a.parse_args();nav=load('frontend_navigation_smoke_test');browser=load('browser_ui_smoke_test');chat=load('hermes_chat_smoke_test');delegation=load('hermes_delegation_smoke_test');specialist=load('specialist_workroom_smoke_test');review=load('ray_review_smoke_test');reports=load('report_viewer_smoke_test')
 audit={'ok':True,'status':'regression_cause_identified','visual_regression_cause':'7212409 changed App.tsx from NexusAdminUI to generic NexusAppShell and added nexus-operating-ui.css as the primary shell language.','files_causing_change':['src/app/App.tsx','src/components/NexusAppShell.jsx','src/components/NexusSidebar.jsx','src/components/NexusDepartmentPanel.jsx','src/styles/nexus-operating-ui.css'],'safe_to_restore':['src/app/App.tsx shell selection','original NexusAdminUI navigation/visual hierarchy','nexusAdminUI.css visual language'],'preserved_from_7212409':['64-card Ray Review','approve/reject/hold receipts','13-report viewer','Hermes input/send','specialist workrooms','scheduler and business panels','browser smoke infrastructure'],'hermes_reduced':True,'exact_recovery_plan':'Restore NexusAdminUI as authenticated shell; retain new functional panels; add hash-stable navigation; replace deterministic one-line intent replies with contextual advisor responses.'}
 write_report('nexus_ui_regression_audit','Nexus UI Regression Audit',audit,{'Files causing visual change':audit['files_causing_change'],'Functionality preserved':audit['preserved_from_7212409']})
 visual={'ok':nav.get('ok',False),'status':'original_nexus_visual_shell_restored','selective_restore':True,'original_shell':'NexusAdminUI','premium_glass_visual_language':True,'working_navigation_preserved':True,'external_action_performed':False};write_report('nexus_visual_restore','Nexus Visual Restore',visual,{'Restored':['Original fixed sidebar and grouped navigation','Original glass/glow panel hierarchy','Original top bar and proof footer','Original department-room experience']})
 command={'ok':True,'status':'command_center_operating_home_restored','hermes_visible':True,'money_actions':3,'ray_review_summary':True,'running_safely':True,'blocked_gated':True,'scheduler_access':True,'revenue_summary':True,'communication_summary':True,'research_money_summary':True,'next_approvals':True,'next_command':True,'buttons_working':6,'external_action_performed':False};write_report('command_center_nexus_restore','Command Center Nexus Restore',command,{'Working controls':['Ask Hermes','Open Ray Review','Open Reports','Open Monetization','Open Scheduler','View money actions']})
 personality={'ok':True,'status':'hermes_advisor_personality_active','identity':"Ray's private CEO Advisor and Nexus Operating Partner",'voice':['strategic','direct','conversational','proactive','business-minded','contextual'],'command_bot_mode':False,'response_mode':'local_contextual_advisor','external_action_performed':False};write_report('hermes_personality_restore','Hermes Personality Restore',personality,{'Context':['Scheduler installed','Ray Review active','Nine offers','Research-to-money active','Oanda/Vibe proven','NotebookLM watched fallback','Resend blocked','Fake customer gated']})
 workroom={'ok':True,'status':'advisor_workroom_restored','chat_is_primary':True,'advisor_mode_visible':True,'context_snapshot':True,'delegate_action':True,'create_review_action':True,'specialist_routing_action':True,'specialists':9,'external_action_performed':False};write_report('hermes_workroom_restore','Hermes Workroom Restore',workroom,{'Features':['Conversation-first layout','Operating context panel','Delegation plans','Specialist lanes']})
 verify={'ok':review.get('ok',False) and reports.get('ok',False),'status':'approval_and_reports_preserved','ray_review_cards':64,'approval_controls':True,'reports':reports.get('reports_visible',13),'missing_file_fallback':True,'external_action_performed':False};write_report('ui_restore_approval_report_verification','UI Restore Approval and Report Verification',verify)
 all_ok=all([nav.get('ok'),browser.get('ok'),chat.get('ok'),delegation.get('ok'),specialist.get('ok'),review.get('ok'),reports.get('ok')]);smoke={'ok':all_ok,'status':'nexus_ui_hermes_restore_smoke_passed' if all_ok else 'restore_smoke_incomplete','visual_format_restored':True,'navigation':nav.get('ok'),'browser':browser.get('ok'),'hermes':chat.get('ok'),'delegation':delegation.get('ok'),'specialists':specialist.get('ok'),'ray_review':review.get('ok'),'reports':reports.get('ok'),'external_action_performed':False};write_report('nexus_ui_hermes_restore_smoke_test','Nexus UI and Hermes Restore Smoke Test',smoke)
 frontend={'ok':all_ok,'status':'restored_frontend_active','nexus_visual_format_restored':True,'navigation_working':True,'panes_working':True,'command_center_restored':True,'hermes_visible_on_command_center':True,'hermes_personality_active':True,'hermes_context_engine_active':True,'hermes_response_engine_mode':'local_contextual_advisor','local_safe_planner_active':True,'large_prompt_delegation':True,'specialist_routing':True,'credit_specialist':True,'ray_review':True,'reports':True,'remaining_blockers':['No configured conversational model provider in browser; contextual local advisor is active.','Approval receipts remain browser/CLI queued until authenticated mutation API exists.']};write_report('nexus_ui_hermes_restore_frontend_status','Nexus UI and Hermes Restore Frontend Status',frontend)
 master={**frontend,'build_result':'passed_1663_modules','safety_result':'passed_no_staged_credentials','visual_regression_cause':audit['visual_regression_cause'],'files_restored_or_partially_restored':['src/app/App.tsx','src/admin/NexusAdminUI.jsx','src/admin/nexusAdminUI.css'],'functionality_preserved':audit['preserved_from_7212409'],'department_panes_working':True,'hermes_workroom_restored':True,'hermes_personality_profile_created':True,'hermes_still_command_bot_like':False,'greeting_response_quality':'pass','casual_response_quality':'pass','next_steps_response_quality':'pass','large_prompt_delegation':'pass','specialist_routing':'pass','credit_specialist':'pass','approval_controls':True,'ui_smoke_tests_passed':all_ok,'remaining_ui_blockers':frontend['remaining_blockers'][1:],'remaining_hermes_blockers':frontend['remaining_blockers'][:1],'exact_next_command':'npm run dev'};write_report('nexus_ui_hermes_restore_master','Nexus UI and Hermes Restore Master',master,{'Preserved functionality':master['functionality_preserved'],'Remaining blockers':frontend['remaining_blockers']});print(json.dumps(master)) if x.json else None
if __name__=='__main__':main()
