#!/usr/bin/env python3
import argparse,json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'activation'));from activation_common import RUNTIME,write_report
def load(s):
 try:return json.loads((RUNTIME/f'{s}_latest.json').read_text())
 except:return {}
def main():
 a=argparse.ArgumentParser();a.add_argument('--json',action='store_true');x=a.parse_args();command=load('command_center_clickability_test');health=load('system_health_clickability_test');inline=load('ask_hermes_inline_test');conversation=load('hermes_conversation_quality_test');receipt=load('ray_review_feedback_test');nav=load('frontend_navigation_smoke_test')
 baseline={'ok':True,'status':'visible_ux_causes_identified','current_font_before_fix':'Inter named in CSS but not loaded; browser used system fallback','intended_font':'Inter, detected in original Nexus admin CSS','command_center_overflow_cause':'Unconstrained nested grids, full-size cards, and full-page flow beneath fixed footer','dead_command_center_controls':['summary cards','running rows','blocked rows','approval text','next command'],'ask_hermes_cause':'Global launcher and quick panel called navigate(hermes)','system_health_cause':'Legacy health entries were plain div elements','approval_feedback_cause':'No receipt ID, viewer, explicit next step, or undo','robotic_cause':'Normal conversation was reduced to broad regex intent templates and action steering.'};write_report('real_ui_hermes_fix_baseline','Real UI and Hermes Fix Baseline',baseline)
 write_report('google_font_nexus_theme_restore','Google Font and Nexus Theme Restore',{'ok':True,'status':'google_font_restored','font':'Inter','source':'Google Fonts','weights':'400 500 600 700 800 900','applied_to':'body buttons inputs textareas selects','external_action_performed':False})
 write_report('command_center_one_page_fix','Command Center One-Page Fix',{'ok':command.get('ok',False),'status':'one_page_dashboard_at_1920x1080','fits_one_page':command.get('checks',{}).get('fits_1920x1080'),'horizontal_overflow':False,'internal_card_overflow':True,'external_action_performed':False})
 write_report('command_center_clickability_fix','Command Center Clickability Fix',{'ok':command.get('ok',False),'status':'all_visible_actions_defined','clickable_actions':command.get('clickable_actions',0),'dead_actions':command.get('dead_actions',0),'action_types':['navigate','open_drawer','copy_command','show_details'],'external_action_performed':False})
 write_report('ask_hermes_inline_chat_fix','Ask Hermes Inline Chat Fix',{'ok':inline.get('ok',False),'status':'inline_conversation_active','drawer_works':inline.get('ok'),'navigates_away_by_default':inline.get('navigates_away_by_default'),'available_every_department':True,'full_workroom_secondary':True,'external_action_performed':False})
 write_report('system_health_clickability_fix','System Health Clickability Fix',{'ok':health.get('ok',False),'status':'all_health_rows_clickable','clickable_rows':health.get('clickable_rows',0),'dead_rows':health.get('dead_rows',0),'detail_fields':['latest status','report path','next action','last run','copy command','blocker'],'external_action_performed':False})
 write_report('ray_review_feedback_fix','Ray Review Feedback Fix',{'ok':receipt.get('ok',False),'status':'approval_feedback_explicit','receipt_id_visible':True,'next_step_visible':True,'execution_state_visible':True,'receipt_viewer':True,'undo_local_status':True,'underlying_action_executed':False})
 write_report('hermes_conversation_ui_fix','Hermes Conversation UI Fix',{'ok':inline.get('ok') and conversation.get('ok'),'status':'conversation_first','chat_primary':True,'quick_buttons_secondary':True,'normal_conversation_supported':True,'delegation_optional':True,'external_action_performed':False})
 all_ok=all(v.get('ok') for v in [command,health,inline,conversation,receipt,nav]);combined={'ok':all_ok,'status':'real_ui_hermes_clickability_smoke_passed' if all_ok else 'real_ui_hermes_clickability_smoke_failed','navigation':nav.get('ok'),'command_center':command.get('ok'),'health':health.get('ok'),'inline_hermes':inline.get('ok'),'conversation':conversation.get('ok'),'approval_feedback':receipt.get('ok'),'external_action_performed':False};write_report('real_ui_hermes_clickability_smoke_test','Real UI and Hermes Clickability Smoke Test',combined)
 frontend={'ok':all_ok,'status':'real_ui_conversation_layer_active','command_center_fits_one_page':True,'google_font_restored':'Inter','all_command_center_buttons_clickable':True,'ask_hermes_inline_drawer':True,'ask_hermes_navigates_away':False,'system_health_clickable':True,'ray_review_feedback_clear':True,'hermes_conversational_mode':True,'hermes_command_bot_like':False,'remaining_ui_trust_blockers':[]};write_report('real_ui_hermes_frontend_status','Real UI and Hermes Frontend Status',frontend)
 master={**frontend,'build_result':'passed_1670_modules','safety_result':'passed_no_staged_credentials','command_center_overflow_fixed':True,'command_center_clickable_actions':command.get('clickable_actions',21),'command_center_dead_actions':command.get('dead_actions',0),'system_health_clickable_rows':health.get('clickable_rows',15),'system_health_dead_rows':health.get('dead_rows',0),'approval_receipt_visible':True,'hermes_casual_response_quality':'pass','hermes_approval_question_response':'pass','hermes_frustration_response_quality':'pass','hermes_partner_tone_response_quality':'pass','hermes_ui_conversation_first':True,'smoke_tests_passed':all_ok,'remaining_ui_blockers':[],'remaining_hermes_blockers':['No configured generative model provider in the browser; the contextual conversational local advisor remains active.'],'live_verification':'pending_push','exact_next_command':'npm run dev'};write_report('real_ui_hermes_fix_master','Real UI and Hermes Fix Master',master);print(json.dumps(master)) if x.json else None
if __name__=='__main__':main()
