#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from stripe_test_execution_common import RUNTIME,SUPABASE_READY,now,read_json,write_json,write_report
def build():
 checkout=read_json(RUNTIME/"stripe_test_checkout_session_latest.json",{});intent=read_json(RUNTIME/"stripe_test_payment_intent_latest.json",{})
 cards=[{"id":"approve-manual-test-checkout","title":"Approve manual completion of Stripe test Checkout Session","status":"pending_Ray_review","approval_required":True,"test_mode_only":True,"exact_action":"Retrieve the gitignored URL locally and complete with Stripe test card 4242 4242 4242 4242.","external_action_performed":False,"created_at":now()},{"id":"approve-test-intent-confirm","title":"Approve Stripe test PaymentIntent confirmation using test payment method","status":"pending_Ray_review","approval_required":True,"test_mode_only":True,"exact_action":"Attach pm_card_visa and confirm only after re-verifying livemode=false.","external_action_performed":False,"created_at":now()}]
 write_json(SUPABASE_READY/"stripe_payment_test_approval_cards_latest.json",cards)
 packet={"ok":True,"generated_at":now(),"status":"manual_test_completion_approval_required","checkout_status":checkout.get("status"),"checkout_completed":checkout.get("checkout_completed",False),"payment_intent_status":intent.get("payment_intent_status"),"payment_intent_confirmed":intent.get("confirmed",False),"local_checkout_url_retrieval_command":"python3 -c 'import json; print(json.load(open(\".stripe_test_runtime/stripe_test_objects_latest.local.json\"))[\"checkout\"][\"url\"])'","payment_intent_confirmation_command_template":"stripe payment_intents confirm <LOCAL_TEST_PI_ID> --payment-method pm_card_visa","raw_checkout_url_included":False,"raw_payment_id_included":False,"real_charge_made":False,"approval_cards_created":len(cards),"external_action_performed":False}
 write_report("stripe_manual_test_completion_packet","Stripe Manual Test Completion Packet",packet,{"Approval cards":cards});blocker={"ok":True,"generated_at":now(),"status":"human_test_completion_required","checkout":checkout.get("status"),"payment_intent":intent.get("payment_intent_status"),"webhook_path_verified":read_json(RUNTIME/"stripe_listener_test_latest.json",{}).get("ok",False),"real_charge_made":False,"next_action":"Ray approves manual Checkout completion and/or test-method PaymentIntent confirmation.","external_action_performed":False};write_report("stripe_checkout_paymentintent_blocker","Stripe Checkout and PaymentIntent Blocker",blocker);return packet
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--json",action="store_true");a=p.parse_args();r=build();print(json.dumps(r,indent=2) if a.json else r)
