import React, { useMemo, useState } from 'react';
import { ArrowLeft, Check, ChevronDown, ExternalLink, FileText, Image as ImageIcon, LockKeyhole, Play, RotateCcw, ShieldCheck, X } from 'lucide-react';
import { createEvent } from '../lib/ledger';
import { goclearCampaignReview as campaign } from '../data/campaignReviewFixture';
import './campaignReviewCenter.css';

const REVIEW_KEY = `nexus-campaign-review:${campaign.campaign_review_id}`;
function readReview() { try { return JSON.parse(localStorage.getItem(REVIEW_KEY) || 'null') || { review_status: campaign.review_status, audit: [] }; } catch { return { review_status: campaign.review_status, audit: [] }; } }

function Status({ children, tone = 'neutral' }) { return <span className={`campaign-status campaign-status-${tone}`}>{children}</span>; }
function Field({ label, children }) { return <div className="campaign-field"><span>{label}</span><strong>{children}</strong></div>; }
function Section({ eyebrow, title, children, className = '' }) { return <section className={`campaign-section ${className}`}><div className="campaign-section-heading"><span>{eyebrow}</span><h2>{title}</h2></div>{children}</section>; }
function ArtifactMeta({ artifact }) { return <div className="campaign-artifact-meta"><span>{artifact.surface || artifact.dimensions || 'Creative artifact'}</span><span>{artifact.version || artifact.duration || ''}</span><code>{artifact.hash}</code></div>; }

export default function CampaignReviewCenter() {
  const [review, setReview] = useState(readReview);
  const [notes, setNotes] = useState('');
  const [technicalOpen, setTechnicalOpen] = useState(false);
  const [compare, setCompare] = useState(false);
  const [message, setMessage] = useState('');
  const pending = review.review_status === 'PENDING';
  const artifactCount = useMemo(() => Object.values(campaign.artifacts).filter(Boolean).length - 2, []);

  async function recordDecision(decision) {
    const now = new Date().toISOString();
    const nextStatus = decision === 'approve' ? 'APPROVED' : decision === 'revision' ? 'REVISION_REQUESTED' : 'REJECTED';
    const audit = { campaign_review_id: campaign.campaign_review_id, campaign_id: campaign.campaign_id, decision: nextStatus, reviewer: 'authenticated_admin', timestamp: now, revision_notes: notes || null, prior_state: review.review_status, new_state: nextStatus };
    const next = { ...review, review_status: nextStatus, reviewed_at: now, audit: [...(review.audit || []), audit] };
    localStorage.setItem(REVIEW_KEY, JSON.stringify(next));
    setReview(next);
    setMessage(`Decision staged: ${nextStatus}. No publishing or deployment action was triggered.`);
    await createEvent({ lane: 'creative', action: `campaign_review_${decision}`, status: 'success', title: `${nextStatus}: ${campaign.campaign_name}`, summary: notes || `Admin campaign review decision staged for ${campaign.campaign_id}.`, payload: audit });
  }

  return <main className="campaign-review-page">
    <header className="campaign-review-topbar"><a href="/admin" className="campaign-back"><ArrowLeft size={15} /> Admin command center</a><div className="campaign-topbar-right"><LockKeyhole size={14} /> Admin-only review <span>·</span> No publishing authority</div></header>
    <div className="campaign-review-shell">
      <div className="campaign-review-breadcrumb">REVIEW CENTER <span>/</span> CAMPAIGN PACKAGE</div>
      <section className="campaign-review-hero"><div><p className="campaign-kicker">GOCLEAR · CAMPAIGN REVIEW</p><h1>{campaign.campaign_name}</h1><p className="campaign-lede">One governed view of what Nexus created, why it created it, and what Ray can authorize next.</p><div className="campaign-hero-tags"><Status tone="amber">{review.review_status}</Status><Status tone="teal">{campaign.status}</Status><span>{campaign.department}</span><span>{campaign.created_at.slice(0, 10)}</span></div></div><div className="campaign-hero-mark"><ShieldCheck size={22} /><strong>Human gate</strong><small>Approval never publishes, deploys, spends, or launches ads.</small></div></section>

      <Section eyebrow="CAMPAIGN OVERVIEW" title="What this work is trying to do"><div className="campaign-overview-grid"><Field label="Audience">{campaign.target_audience}</Field><Field label="Marketing objective">{campaign.marketing_objective}</Field><Field label="Desired action">{campaign.desired_action}</Field><Field label="Primary CTA">{campaign.primary_cta}</Field></div><div className="campaign-response"><div className="campaign-response-label">RESPONSE STRATEGY</div><div className="campaign-response-triad"><div><b>FEEL</b><strong>{campaign.response_strategy.feel}</strong></div><div><b>THINK</b><strong>{campaign.response_strategy.think}</strong></div><div><b>ACT</b><strong>{campaign.response_strategy.act}</strong></div></div><div className="campaign-hook"><span>HOOK</span><strong>{campaign.response_strategy.hook}</strong><small>{campaign.response_strategy.tension}</small></div></div></Section>

      <Section eyebrow="CREATIVE DIRECTION" title={campaign.creative_direction_id}><div className="campaign-concept-grid"><Field label="Human insight">{campaign.creative_direction.human_insight}</Field><Field label="Core tension">{campaign.creative_direction.core_tension}</Field><Field label="Big idea">{campaign.creative_direction.big_idea}</Field><Field label="Visual metaphor">{campaign.creative_direction.visual_metaphor}</Field><Field label="Page story">{campaign.creative_direction.page_story}</Field></div></Section>

      <Section eyebrow="OPEN IDEATION · NOT SELECTED" title="Meta-originated concepts for Ray review" className="open-ideation-section"><div className="campaign-open-ideation-banner"><ShieldCheck size={15} /><span>Open ideation used business context and accessible brand facts only. No prior campaign solution was supplied. These concepts are review options, not approved production direction.</span></div><div className="campaign-open-ideation-meta"><Status tone="purple">{campaign.open_ideation.mode}</Status><span>{campaign.open_ideation.metaProvider} · {campaign.open_ideation.metaSession}</span><code>{campaign.open_ideation.promptHash}</code></div><details className="campaign-prompt-details campaign-open-prompt"><summary>Exact open ideation prompt sent to Meta</summary><pre>{campaign.open_ideation.prompt}</pre></details><div className="campaign-open-concept-grid">{campaign.open_ideation.concepts.map((concept, index) => <article className="campaign-open-concept-card" key={concept.title}><div className="campaign-open-concept-heading"><span>CONCEPT {String.fromCharCode(65 + index)}</span><Status tone="amber">NOT SELECTED</Status></div><h3>{concept.title}</h3><p>{concept.premise}</p><div className="campaign-open-concept-field"><b>CREATIVE WORLD</b><span>{concept.world}</span></div><div className="campaign-open-concept-field"><b>INTENDED RESPONSE</b><span>{concept.response}</span></div><div className="campaign-open-concept-field"><b>WHY GOCLEAR</b><span>{concept.goclear}</span></div><div className="campaign-open-concept-field"><b>EXTENSION</b><span>{concept.extension}</span></div><div className="campaign-open-concept-field"><b>ORIGINALITY / CRITIC</b><span>{concept.originality} · {concept.critic}</span></div><small>Meta provenance: {campaign.open_ideation.rawOutputPath}</small></article>)}</div><div className="campaign-open-critic"><b>CREATIVE DIRECTOR CRITIQUE — NO RANKING</b><p>{campaign.open_ideation.critic.finding}</p><small>{campaign.open_ideation.critic.provider} · {campaign.open_ideation.critic.model} · {campaign.open_ideation.critic.rawPath}</small></div></Section>

      <Section eyebrow="VISUAL REFERENCE RESEARCH" title="Reference only — not copied"><div className="campaign-reference-grid">{campaign.references.map(reference => <article className="campaign-reference-card" key={reference.id}><img src={reference.preview} alt={`${reference.title} reference preview`} /><div><div className="campaign-reference-title"><strong>{reference.title}</strong><Status tone="purple">{reference.style}</Status></div><p>{reference.principle}</p><small>{reference.source} · <a href={reference.url} target="_blank" rel="noreferrer">source <ExternalLink size={11} /></a></small></div></article>)}</div><p className="campaign-boundary"><ShieldCheck size={14} /> Extracted principles only. Source artwork, copy, identity, code, and exact layouts were not used.</p></Section>

      <Section eyebrow="ART DIRECTION" title="The visual system behind the package"><div className="campaign-direction-grid">{Object.entries({ 'Visual north star': campaign.art_direction.visual_north_star, 'Visual world': campaign.art_direction.visual_world, Imagery: campaign.art_direction.imagery, Typography: campaign.art_direction.typography, 'Color system': campaign.art_direction.color_system, 'Motion language': campaign.art_direction.motion_language, 'Distinctive brand signal': campaign.art_direction.distinctive_brand_signal }).map(([label, value]) => <Field key={label} label={label}>{value}</Field>)}</div><div className="campaign-callout"><b>Reference transformation</b><p>{campaign.art_direction.reference_transformation}</p><small>{campaign.art_direction.anti_generic}</small></div></Section>

      <Section eyebrow="CREATIVE OUTPUTS" title="Inspect the actual campaign artifacts"><div className="campaign-output-grid"><article className="campaign-output-card campaign-image-card"><div className="campaign-output-heading"><span><ImageIcon size={15} /> IMAGE</span><Status tone="teal">{campaign.artifacts.image.surface}</Status></div><img src={campaign.artifacts.image.path} alt="Fresh GoClear campaign creative" /><ArtifactMeta artifact={campaign.artifacts.image} /><p>Fresh Meta image generated in the canonical campaign session.</p></article><article className="campaign-output-card"><div className="campaign-output-heading"><span><Play size={15} /> VIDEO</span><Status tone="teal">LOCAL MP4 AVAILABLE</Status></div><video controls preload="metadata" poster={campaign.artifacts.image.path} src={campaign.artifacts.video.path} aria-label="Fresh GoClear campaign video" /><ArtifactMeta artifact={campaign.artifacts.video} /><p>Fresh 10-second Meta video generated in the same campaign session.</p></article></div></Section>

      <Section eyebrow="LANDING / FUNNEL" title="Meta campaign funnel"><div className="campaign-mockup-note"><FileText size={16} /><div><strong>FRESH META FUNNEL GENERATED · LOCAL HTML RETRIEVAL BLOCKED</strong><span>Meta produced a real HTML artifact in the authenticated campaign session. Its download/preview endpoint returned an internal server error, so no local desktop/mobile export is represented as available.</span></div></div><div className="campaign-page-previews"><figure><figcaption>Meta funnel artifact evidence · review capture</figcaption><img src={campaign.artifacts.funnelEvidence.path} alt="Meta funnel artifact evidence" /></figure><figure><figcaption>Desktop export · NOT RETRIEVED</figcaption><div className="campaign-field"><span>STATUS</span><strong>GENERATED_REAL_RETRIEVAL_BLOCKED</strong></div><div className="campaign-field"><span>MOBILE EXPORT</span><strong>NOT RETRIEVED</strong></div></figure></div><div className="campaign-version-proof"><span>FUNNEL CONTINUITY</span><strong>Scattered paperwork → Business Identity folder → low-pressure next step</strong><small>Primary CTA: {campaign.primary_cta} · Free-information path: {campaign.free_information_path}</small></div></Section>

      <Section eyebrow="QA / PROVENANCE" title="Evidence behind the review"><div className="campaign-qa-grid">{Object.entries(campaign.qa).map(([key, value]) => <Field key={key} label={key.replaceAll('_', ' ')}><Status tone={value.includes('HUMAN') ? 'amber' : value.includes('PASS') ? 'teal' : 'neutral'}>{value}</Status></Field>)}</div><button type="button" className="campaign-technical-toggle" onClick={() => setTechnicalOpen(!technicalOpen)}><ChevronDown size={15} className={technicalOpen ? 'rotated' : ''} /> Technical provenance and receipts</button>{technicalOpen && <div className="campaign-technical"><Field label="Creative Director">{campaign.provenance.creative_director_model}</Field><Field label="Art Director">{campaign.provenance.art_director_model}</Field><Field label="Prompt Architect">{campaign.provenance.prompt_architect_model}</Field><Field label="Provider">{campaign.provenance.provider}</Field><Field label="Tokens / cost">{campaign.provenance.input_tokens} · {campaign.provenance.estimated_model_cost}</Field><Field label="Artifact lineage">{campaign.creative_direction_sha256} · {campaign.art_direction_sha256}</Field><Field label="Receipts">{campaign.provenance.receipts.join(' · ')}</Field><Field label="Final prompt hash">{campaign.provenance.final_meta_prompt_hash}</Field><details className="campaign-prompt-details"><summary>Exact prompt sent to Meta</summary><pre>{campaign.provenance.final_meta_prompt}</pre></details></div>}</Section>

      <Section eyebrow="RAY DECISION" title="What should happen next?" className="campaign-decision-section"><p className="campaign-decision-copy">This package is review-ready. Choosing an action records an append-only review event; it does not activate the Creative queue or publish anything.</p><textarea value={notes} onChange={event => setNotes(event.target.value)} placeholder="Optional revision or rejection notes" aria-label="Review notes" /><div className="campaign-decision-actions"><button type="button" className="decision-approve" onClick={() => recordDecision('approve')} disabled={!pending}><Check size={16} /> APPROVE</button><button type="button" className="decision-revision" onClick={() => recordDecision('revision')} disabled={!pending}><RotateCcw size={16} /> REQUEST REVISION</button><button type="button" className="decision-reject" onClick={() => recordDecision('reject')} disabled={!pending}><X size={16} /> REJECT</button></div>{message && <div className="campaign-decision-message" role="status">{message}</div>}<small className="campaign-no-side-effects">NEXT STAGE CONTRACT ONLY · APPROVAL DOES NOT PUBLISH, DEPLOY, SPEND, OR LAUNCH ADS.</small></Section>
    </div>
  </main>;
}
