import React, { useState } from 'react'
import { Activity, AlertTriangle, BarChart3, Bot, CheckCircle2, CheckSquare, Clock3, Database, FileText, Gauge, LifeBuoy, LockKeyhole, Network, Radar, RefreshCw, Settings, ShieldCheck, Users, Wrench } from 'lucide-react'
import { entitiesByType } from '../lib/organizationalEntities'

function PageHeader({ eyebrow, title, description, icon: Icon }) {
  return <header className="live-surface-header canonical-page-header"><div><span className="live-command-eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div><div className="canonical-page-mark"><Icon size={26} /><span>GOCLEAR NEXUS OS</span></div></header>
}

function Stat({ label, value, note, tone = 'cyan' }) { return <article className={`live-surface-stat tone-${tone}`}><span>{label}</span><strong>{value ?? '—'}</strong><small>{note}</small></article> }
function Panel({ title, eyebrow, children, className = '' }) { return <section className={`live-command-panel canonical-panel ${className}`}><header className="live-command-panel-head"><div><span className="live-command-eyebrow">{eyebrow}</span><h3>{title}</h3></div></header>{children}</section> }
function Empty({ icon: Icon = FileText, title, detail }) { return <div className="live-honest-empty"><Icon size={19} /><strong>{title}</strong><span>{detail}</span></div> }
function Status({ value }) { const normalized = String(value || 'UNKNOWN').replaceAll('_', ' '); return <span className={`canonical-status ${/healthy|active|ready|completed|running/i.test(normalized) ? 'good' : /failed|blocked|degraded/i.test(normalized) ? 'bad' : 'wait'}`}>{normalized}</span> }

export function TasksPage({ state }) {
  const [filter, setFilter] = useState('ALL')
  const queue = state.queue_metrics || {}
  const filters = ['ALL', 'READY', 'RUNNING', 'WAITING_ON_DECISION', 'COMPLETED', 'FAILED_RETRYABLE']
  const rows = Array.isArray(state.task_items) ? state.task_items : []
  return <div className="canonical-page canonical-tasks-page"><PageHeader eyebrow="WORK / EXECUTION QUEUE" title="Tasks" description="See what work exists, what is running, and what is waiting for a decision." icon={CheckSquare} /><div className="canonical-stat-grid"><Stat label="Ready" value={queue.READY} note="executable now" /><Stat label="Running" value={queue.RUNNING} note="claimed work" tone="purple" /><Stat label="Waiting on decision" value={queue.WAITING_ON_DECISION ?? queue.WAITING_APPROVAL} note="human boundary" tone="amber" /><Stat label="Completed" value={queue.COMPLETED} note="receipt-backed" tone="green" /><Stat label="Retryable failures" value={queue.FAILED_RETRYABLE} note="safe recovery queue" tone="orange" /></div><Panel title="Work queue" eyebrow="CANONICAL TASK STATE"><div className="canonical-tabs">{filters.map(item => <button type="button" className={filter === item ? 'active' : ''} onClick={() => setFilter(item)} key={item}>{item.replaceAll('_', ' ')}</button>)}</div>{rows.length ? <div className="canonical-task-list">{rows.filter(item => filter === 'ALL' || item.status === filter).map(item => <div className="canonical-task-row" role="button" tabIndex="0" key={item.id} onClick={() => window.dispatchEvent(new CustomEvent('task-detail', { detail: item }))} onKeyDown={event => event.key === 'Enter' && window.dispatchEvent(new CustomEvent('task-detail', { detail: item }))}><CheckSquare size={15} /><div><strong>{item.title || item.name}</strong><small>{item.owner || 'Owner unavailable'} · {item.project || 'Project unavailable'} · {item.next_action || 'Next action unavailable'}</small></div><Status value={item.status} /></div>)}</div> : <Empty icon={CheckSquare} title="No task detail records currently available" detail="Queue counts remain source-backed; task rows will appear when the governed task read model is available." />}</Panel><div className="canonical-two-column"><Panel title="Continuation" eyebrow="NEXT MACHINE ACTION"><div className="canonical-callout"><Clock3 size={18} /><strong>{state.next_machine_action || 'Scheduler-managed continuation'}</strong></div></Panel><Panel title="Decision relationship" eyebrow="HUMAN BOUNDARY"><Empty icon={ShieldCheck} title="Tasks and Decisions are separate objects" detail="Linked WAITING_ON_DECISION tasks appear only when a canonical relationship exists." /></Panel></div></div>
}

export function KnowledgePage({ state }) {
  const findings = state.recent_findings || []
  return <div className="canonical-page canonical-knowledge-page"><PageHeader eyebrow="INTELLIGENCE / RETAINED KNOWLEDGE" title="Knowledge" description="What Nexus has learned: findings, claims, methods, comparisons, and provenance." icon={Database} /><div className="canonical-stat-grid"><Stat label="Knowledge sources" value={state.research_v2?.sources ?? findings.length} note="processed records" /><Stat label="Findings" value={findings.length} note="source-backed" tone="teal" /><Stat label="Validated claims" value={state.youtube?.claims_validated} note="current validation" tone="green" /><Stat label="Comparisons" value={state.research_v2?.comparisons ?? '—'} note="qualitative links" tone="purple" /></div><div className="canonical-two-column"><Panel title="Recent intelligence" eyebrow="RESEARCH OUTPUT"><div className="canonical-knowledge-list">{findings.length ? findings.map((item, index) => <article key={item.title || index}><Radar size={15} /><div><strong>{item.title || 'Finding'}</strong><small>{item.lane || 'Research lane unavailable'} · {item.state || 'Status unavailable'}</small></div><Status value={item.state} /></article>) : <Empty icon={Database} title="No retained findings currently available" detail="Nothing is fabricated to fill the institutional knowledge view." />}</div></Panel><Panel title="Evidence and provenance" eyebrow="SOURCE HISTORY"><div className="canonical-definition-list"><div><span>Canonical source</span><strong>{state.provenance || 'Durable Research artifacts'}</strong></div><div><span>Follow-up Research</span><strong>{state.research_v2?.follow_ups ?? '—'}</strong></div><div><span>Source reputation</span><strong>Evidence accumulated over time</strong></div><div><span>Nexus outcomes</span><strong>Only observed outcomes are retained</strong></div></div></Panel></div><Panel title="Knowledge boundary" eyebrow="INSTITUTIONAL MEMORY"><p className="live-surface-copy">Knowledge is retained intelligence. Active questions and investigations remain in Research; completed findings can be compared here without becoming automatic action.</p></Panel></div>
}

export function AnalyticsPage({ state }) {
  const r = state.research || {}; const v2 = state.research_v2 || {}; const q = state.queue_metrics || {}
  return <div className="canonical-page canonical-analytics-page"><PageHeader eyebrow="OBSERVABILITY / OUTCOMES" title="Analytics" description="What the numbers and observed outcomes say about Nexus operations." icon={BarChart3} /><div className="canonical-stat-grid"><Stat label="Research useful output" value={r.useful_output_rate ?? v2.useful_output_rate ?? '—'} note="substantive output only" tone="teal" /><Stat label="Sources processed" value={v2.sources ?? r.sources_processed} note="source-backed" /><Stat label="Questions resolved" value={r.questions_resolved ?? '—'} note="Research progress" tone="purple" /><Stat label="Tasks completed" value={q.COMPLETED} note="canonical queue" tone="green" /><Stat label="Observed outcomes" value={state.outcomes?.count ?? '—'} note="Nexus results only" tone="amber" /></div><div className="canonical-analytics-grid"><Panel title="Research throughput" eyebrow="PRODUCTIVITY"><div className="canonical-bars"><div><span>Sources processed</span><i><em style={{ width: '0%' }} /></i><strong>{v2.sources ?? '—'}</strong></div><div><span>Investigations advanced</span><i><em style={{ width: '0%' }} /></i><strong>{r.investigations_advanced ?? '—'}</strong></div><div><span>Questions resolved</span><i><em style={{ width: '0%' }} /></i><strong>{r.questions_resolved ?? '—'}</strong></div></div></Panel><Panel title="Outcome boundary" eyebrow="MEASURED RESULTS"><div className="canonical-outcome"><Gauge size={22} /><strong>{state.outcomes?.status || 'No business outcome dataset reported'}</strong><p>External Research evidence and Nexus-observed outcomes remain separate. Unavailable metrics are not estimated.</p></div></Panel></div><div className="canonical-two-column"><Panel title="Department productivity" eyebrow="OWNERSHIP"><Empty icon={Users} title="Department outcome metrics unavailable" detail="No fabricated performance values are shown." /></Panel><Panel title="Trend coverage" eyebrow="TIME SERIES"><Empty icon={Activity} title="Trend series unavailable" detail="Historical trend data will appear when the governed analytics read model provides it." /></Panel></div></div>
}

export function AutomationPage({ state }) {
  const workers = state.supervisor?.workers || []; const runtime = state.runtime || {}
  return <div className="canonical-page canonical-automation-page"><PageHeader eyebrow="SYSTEM / AUTONOMOUS CONTINUATION" title="Automation" description="What runs by itself: workers, schedules, heartbeats, recovery, and the next wake." icon={Bot} /><div className="canonical-stat-grid"><Stat label="Supervisor" value={state.supervisor_status || runtime.supervisor_status} note="process liveness" tone="green" /><Stat label="Scheduler" value={runtime.scheduler} note="continuation state" tone="teal" /><Stat label="Queue depth" value={state.queue_metrics?.executable_queue_depth} note="executable work" tone="purple" /><Stat label="Next wake" value={runtime.next_wake || state.next_wake_at} note="scheduler-managed" tone="amber" /></div><div className="canonical-two-column"><Panel title="Supervised workers" eyebrow="WORKER HEALTH"><div className="canonical-worker-list">{workers.length ? workers.map(worker => <div key={worker.id || worker.name}><Bot size={15} /><div><strong>{worker.name || worker.id || 'Worker'}</strong><small>{worker.last_run || 'Last run unavailable'} · {worker.next_action || 'Next action unavailable'}</small></div><Status value={worker.status} /></div>) : <Empty icon={Bot} title="Worker detail is unavailable" detail="Supervisor liveness remains separate from productive Research." />}</div></Panel><Panel title="Recovery and events" eyebrow="RECENT AUTOMATION"><div className="canonical-definition-list"><div><span>Last heartbeat</span><strong>{runtime.supervisor_last_heartbeat || 'Unavailable'}</strong></div><div><span>Next machine action</span><strong>{state.next_machine_action || 'Unavailable'}</strong></div><div><span>Recovery status</span><strong>{state.system_health || 'Unavailable'}</strong></div><div><span>Research productivity</span><strong>{state.research?.productivity_health || 'Unavailable'}</strong></div></div></Panel></div><Panel title="Autonomy boundary" eyebrow="GOVERNED CONTINUATION"><div className="canonical-callout"><ShieldCheck size={18} /><strong>Automation continues only through supervised, governed workers.</strong></div></Panel></div>
}

export function DepartmentsPage({ state }) {
  const [type, setType] = useState('DEPARTMENT'); const entities = entitiesByType(type); const types = ['DEPARTMENT', 'AGENT', 'ENGINE', 'CAPABILITY', 'SERVICE', 'EXECUTIVE']
  return <div className="canonical-page canonical-departments-page"><PageHeader eyebrow="OPERATIONS / OWNERSHIP" title="Operating Entities" description="Departments, agents, engines, capabilities, services, and executive interfaces are distinct canonical objects." icon={Users} /><div className="canonical-tabs">{types.map(item => <button type="button" className={type === item ? 'active' : ''} onClick={() => setType(item)} key={item}>{item}</button>)}</div><div className="canonical-stat-grid"><Stat label="Visible entities" value={entities.length} note={type.toLowerCase()} /><Stat label="Active" value={entities.filter(d => /active|healthy/i.test(d.status || '')).length} note="operating now" tone="green" /><Stat label="Current work" value={entities.filter(d => d.current_work && !/no active|available when/i.test(d.current_work)).length} note="assigned or active" tone="teal" /></div><Panel title={`${type} directory`} eyebrow="CANONICAL ENTITY TAXONOMY">{entities.length ? <div className="canonical-department-grid">{entities.map(entity => <details key={entity.entity_id}><summary><div className="canonical-department-icon"><Users size={16} /></div><div><strong>{entity.name}</strong><small>{entity.mission}</small><span>{entity.owner} · {entity.current_work}</span></div><Status value={entity.status} /></summary><div className="canonical-entity-detail"><p><b>Handoffs:</b> {entity.handoffs.join(', ') || 'None'}</p><p><b>Capabilities:</b> {entity.capabilities.join(', ') || 'None'}</p>{entity.parent_department && <p><b>Parent department:</b> {entity.parent_department}</p>}</div></details>)}</div> : <Empty icon={Users} title="No entities in this class" detail="The canonical taxonomy returned no records." />}</Panel></div>
}

export function SettingsPage({ state }) {
  const sections = ['GENERAL', 'AI / MODELS', 'RESEARCH', 'AUTOMATION', 'NOTIFICATIONS', 'INTEGRATIONS', 'SECURITY', 'SYSTEM']
  return <div className="canonical-page canonical-settings-page"><PageHeader eyebrow="SYSTEM / SAFE CONFIGURATION" title="Settings" description="What Ray can configure, what is read-only, and what remains protected." icon={Settings} /><div className="canonical-settings-grid"><Panel title="Editable settings" eyebrow="SAFE WRITE PATHS"><Empty icon={Settings} title="No safe editable settings are currently exposed" detail="Settings remain read-only until a canonical governed write path exists." /></Panel><Panel title="Read-only system state" eyebrow="CURRENT CONFIGURATION"><div className="canonical-definition-list"><div><span>Timezone</span><strong>{state.timezone || 'Unavailable from read model'}</strong></div><div><span>Research cadence</span><strong>{state.research?.cadence || 'Scheduler-managed'}</strong></div><div><span>Default model</span><strong>Protected / not reported</strong></div><div><span>Tenant guard</span><strong>ENABLED</strong></div></div></Panel></div><Panel title="Configuration categories" eyebrow="GOVERNANCE"><div className="canonical-settings-list">{sections.map(section => <div key={section}><Settings size={14} /><strong>{section}</strong><Status value="NOT_YET_EDITABLE" /><span>Read-only until safely backed</span></div>)}</div></Panel><Panel title="Protected credentials" eyebrow="SECURITY"><div className="canonical-callout"><LockKeyhole size={18} /><strong>Protected credential status only. Secrets, keys, and private material are never rendered.</strong></div></Panel></div>
}

export function SupportPage({ state }) {
  const checks = [['System health', state.system_health], ['Supervisor', state.supervisor_status], ['Scheduler', state.runtime?.scheduler], ['Research', state.research?.health], ['Storage', state.provenance ? 'AVAILABLE' : 'UNKNOWN'], ['Network', 'NOT_REPORTED']]
  return <div className="canonical-page canonical-support-page"><PageHeader eyebrow="HELP / DIAGNOSTICS" title="Support" description="What is wrong, what happened, and how Nexus can diagnose it safely." icon={LifeBuoy} /><div className="canonical-stat-grid"><Stat label="System health" value={state.system_health} note="runtime signal" tone="green" /><Stat label="Active incidents" value={state.incidents?.active ?? '—'} note="governed records" tone="orange" /><Stat label="Recent recoveries" value={state.recoveries?.recent ?? '—'} note="receipt-backed" tone="teal" /><Stat label="Storage" value={state.provenance ? 'AVAILABLE' : 'UNKNOWN'} note="artifact evidence" tone="purple" /></div><Panel title="Diagnostic matrix" eyebrow="CURRENT HEALTH"><div className="canonical-health-grid">{checks.map(([label, value]) => <div key={label}><Activity size={15} /><span>{label}</span><Status value={value} /></div>)}</div></Panel><div className="canonical-two-column"><Panel title="Recent errors" eyebrow="INCIDENTS"><Empty icon={AlertTriangle} title="No current incident detail available" detail="Support does not invent incidents or recovery claims." /></Panel><Panel title="Safe support actions" eyebrow="GOVERNED CONTROLS"><div className="canonical-support-actions"><button type="button" disabled title="NOT_YET_AVAILABLE: health-check write path is not exposed"><RefreshCw size={14} />Run health check <small>Not yet available</small></button><button type="button" disabled title="READ_ONLY: logs are not exposed in this surface"><FileText size={14} />View logs <small>Read-only</small></button><button type="button" disabled title="NOT_YET_AVAILABLE: safe worker retry path is not exposed"><Wrench size={14} />Retry worker <small>Not yet available</small></button></div></Panel></div></div>
}
