import React, { useEffect, useState } from 'react'
import { Activity, AlertTriangle, CheckCircle2, Clock3, FileCheck2, ShieldAlert } from 'lucide-react'
import './companyCycleOperations.css'

const fallback = { company_cycle_id: 'company_cycle_ddc1b360d7a64a3085b819bec48554f1', status: 'WAITING_RAY', current_stage: 'ADMIN_APPROVAL', objective: 'Discover and investigate one current funding-readiness customer problem, challenge it with Alpha, and prepare a bounded approved response.', research_package_id: 'research_package_c12e6faaab884d5aa34c76641bc5c33c', alpha_decision: 'RESEARCH_MORE', alpha_receipt_id: 'alpha_receipt_481fd7fad572404da766712c0b2fc9d6', admin_approval_package_id: 'admin_approval_1465222613e04f1fa8a10e8e8a83674c', campaign_approval_id: 'appr_f1c900e26b494b71b576877b9019b891', repair_control_plane: { status: 'PASS_REAL', repair_plan_id: 'repair_plan_8c4ce0df7a074dcf97d85f4f235b9d5e', stage_resumed: 'SEO' }, research_tools_used: ['Last30Days', 'official SBA guidance', 'Federal Reserve Small Business Credit Survey'], stages: { RESEARCH: { status: 'PASS_REAL', owner: 'Research AI', latest_result: 'Fresh demand signal plus two official source processors; follow-up persisted.' }, ALPHA: { status: 'PASS_REAL', owner: 'Alpha', latest_result: 'RESEARCH_MORE after follow-up; evidence incomplete, not rejected.' }, DEPARTMENTS: { status: 'PASS_REAL', owner: 'Department coordinators', latest_result: 'Marketing, Creative, SEO, Clyde/Funding, Compliance, and Customer Service drafts persisted.' }, ADMIN_APPROVAL: { status: 'WAITING_RAY', owner: 'Ray', latest_result: 'Consolidated package rendered; publication and email remain gated.' } } }

const tone = status => String(status).includes('PASS') ? 'green' : String(status).includes('WAIT') ? 'purple' : String(status).includes('FAIL') ? 'red' : 'blue'
const Icon = ({ status }) => String(status).includes('PASS') ? <CheckCircle2 /> : String(status).includes('WAIT') ? <ShieldAlert /> : <Activity />

export default function CompanyCycleOperations() {
  const [cycle, setCycle] = useState(fallback)
  useEffect(() => { fetch('/company-cycle-operations.json', { cache: 'no-store' }).then(r => r.ok ? r.json() : fallback).then(setCycle).catch(() => {}) }, [])
  const stages = ['RESEARCH', 'ALPHA', 'DEPARTMENTS', 'ADMIN_APPROVAL', 'SOCIAL', 'EMAIL', 'OUTCOME']
  const openStage = name => { window.location.hash = name === 'ADMIN_APPROVAL' ? '/decisions' : name === 'RESEARCH' ? '/research' : '/departments' }
  return <main className="cycle-ops"><header className="cycle-ops-header"><div><span className="cycle-eyebrow">NEXUS / LIVE COMPANY CYCLE</span><h1>GoClear Operations</h1><p>{cycle.objective}</p></div><div className={`cycle-status tone-${tone(cycle.status)}`}><Icon status={cycle.status} /><strong>{cycle.status}</strong><small>Stage: {cycle.current_stage}</small></div></header>
    <section className="cycle-identity"><span>COMPANY CYCLE</span><strong>{cycle.company_cycle_id}</strong><small>Objective-scoped evidence only · refreshed from canonical checkpoint</small></section>
    <section className="cycle-stage-grid">{stages.map(name => { const item = cycle.stages?.[name] || { status: 'NOT_STARTED', owner: 'Nexus', latest_result: 'Waiting for prior stage.' }; return <button type="button" className={`cycle-stage tone-${tone(item.status)}`} key={name} onClick={() => openStage(name)}><div className="cycle-stage-top"><Icon status={item.status} /><span>{name.replace('_', ' ')}</span><b>{item.status}</b></div><small>Owner · {item.owner}</small><p>{item.latest_result}</p><footer><Clock3 /> Next action: {item.next_action || (item.status === 'WAITING_RAY' ? 'Ray decision required' : 'Continue from checkpoint')}</footer></button> })}</section>
    <section className="cycle-evidence"><h2>Evidence, repairs & decisions</h2><div className="cycle-evidence-row"><FileCheck2 /><div><strong>Research package</strong><small>{cycle.research_package_id}</small></div></div><div className="cycle-evidence-row"><AlertTriangle /><div><strong>Alpha</strong><small>{cycle.alpha_decision} · {cycle.alpha_receipt_id}</small></div></div><div className="cycle-evidence-row"><Activity /><div><strong>Repair control plane</strong><small>{cycle.repair_control_plane?.status || 'NOT_RECORDED'} · {cycle.repair_control_plane?.repair_plan_id || '—'} · local resume {cycle.repair_control_plane?.stage_resumed || '—'}</small></div></div><div className="cycle-evidence-row"><ShieldAlert /><div><strong>Ray approval</strong><small>{cycle.admin_approval_package_id} · {cycle.campaign_approval_id}</small></div></div><div className="cycle-tools"><strong>Tools used</strong><span>{(cycle.research_tools_used || []).join(' · ')}</span></div></section>
    <div className="cycle-actions"><a href="/admin/decisions">VIEW DECISIONS</a><a href="/admin/research">VIEW RESEARCH</a><button type="button" disabled>ASK NOVA</button></div>
  </main>
}
