import React, { useEffect, useState } from 'react'
import { createGuestInvitation, loadClientAiAdminState, loadCustomerCommunications, loadGuestInvitations, updateClientAiControls } from '../lib/testerInvitationClient'
import './r28AdminOperations.css'

const STATUS_TONES = { SENT: 'good', DELIVERED: 'good', FREE_ACTIVE: 'good', SIGNED_UP: 'good', FAILED: 'bad', EXPIRED: 'muted', REVOKED: 'bad' }
function Status({ value }) { return <span className={`r28-status ${STATUS_TONES[value] || 'pending'}`}>{value}</span> }

export default function R28AdminOperationsPanel() {
  const [name, setName] = useState(''), [email, setEmail] = useState(''), [days, setDays] = useState('14'), [note, setNote] = useState('')
  const [invitations, setInvitations] = useState([]), [communications, setCommunications] = useState([]), [aiState, setAiState] = useState({ conversations: [], escalations: [], controls: [] }), [busy, setBusy] = useState(false), [message, setMessage] = useState('')
  async function refresh() { const [i, c, ai] = await Promise.all([loadGuestInvitations(), loadCustomerCommunications(), loadClientAiAdminState()]); setInvitations(i.invitations); setCommunications(c.communications); setAiState({ conversations: ai.conversations, escalations: ai.escalations, controls: ai.controls || [] }); if (i.error || c.error || ai.error) setMessage('Some live Admin data is unavailable; no mock state is shown.') }
  useEffect(() => { void refresh() }, [])
  async function create() { if (!name.trim() || !email.trim() || busy) return; setBusy(true); setMessage(''); const result = await createGuestInvitation({ name, email, expiresInDays: Number(days) || 14, note }); setBusy(false); if (!result.ok) { setMessage(result.error || 'Invitation could not be created.'); return } setName(''); setEmail(''); setNote(''); setMessage(result.data?.email_status === 'SENT' ? 'Guest invitation created and sent.' : 'Guest invitation created; delivery needs review.'); await refresh() }
  return <div className="r28-admin-panel">
    <div className="r28-panel-hero"><div><div className="nx2-eyebrow">R28 / ACCESS + COMMUNICATIONS</div><h2>Guest access, clearly governed.</h2><p>Create expiring FREE_GUEST access for onboarding and readiness only. Paid funding work remains behind the payment or service-agreement gate.</p></div><span className="r28-boundary">Admin-only control</span></div>
    <div className="r28-panel-grid"><section className="r28-card"><div className="nx2-eyebrow">INVITE GUEST</div><h3>Free guest invitation</h3><label>Name<input value={name} onChange={e => setName(e.target.value)} placeholder="Guest name" /></label><label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="guest@example.com" /></label><label>Expires in days<input type="number" min="1" max="30" value={days} onChange={e => setDays(e.target.value)} /></label><label>Optional note<textarea value={note} onChange={e => setNote(e.target.value)} rows="3" placeholder="Internal note" /></label><button className="nx2-primary-button" disabled={busy || !name.trim() || !email.trim()} onClick={create}>{busy ? 'Creating…' : 'Create and send invitation'}</button>{message && <p className="r28-message" role="status">{message}</p>}<small className="r28-help">GUEST_FREE · FREE_GUEST · ONBOARDING_AND_READINESS · PAYMENT_OR_SERVICE_AGREEMENT_REQUIRED</small></section><section className="r28-card"><div className="nx2-eyebrow">ACCESS POLICY</div><h3>Free means readiness, not funding execution.</h3><ul><li>Profile, education, documents, bankability, and readiness preparation are allowed.</li><li>Paid funding execution and concierge services remain locked.</li><li>Invites expire, are single-use, tenant-scoped, auditable, and never grant Admin access.</li></ul><div className="r28-policy-row"><span>Provider</span><b>Resend</b></div><div className="r28-policy-row"><span>External publication</span><b>Approval-gated</b></div></section></div>
    <section className="r28-card"><div className="r28-section-head"><div><div className="nx2-eyebrow">LIVE STATE</div><h3>Guest invitations</h3></div><button className="nx2-outline-button" onClick={refresh}>Refresh</button></div><div className="r28-table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Tier</th><th>Status</th><th>Expires</th></tr></thead><tbody>{invitations.map(item => <tr key={item.id}><td>{item.name}</td><td>{item.email}</td><td>{item.access_tier}</td><td><Status value={item.status} /></td><td>{new Date(item.expires_at).toLocaleDateString()}</td></tr>)}{!invitations.length && <tr><td colSpan="5">No live guest invitations.</td></tr>}</tbody></table></div></section>
    <section className="r28-card"><div className="nx2-eyebrow">COMMUNICATION TIMELINE</div><h3>Recent customer communications</h3><div className="r28-table-wrap"><table><thead><tr><th>Template</th><th>Recipient</th><th>Status</th><th>Created</th></tr></thead><tbody>{communications.map(item => <tr key={item.id}><td>{item.template_id}</td><td>{item.recipient}</td><td><Status value={item.status} /></td><td>{new Date(item.created_at).toLocaleString()}</td></tr>)}{!communications.length && <tr><td colSpan="4">No live communications.</td></tr>}</tbody></table></div></section>
    <section className="r28-card"><div className="nx2-eyebrow">CLIENT AI GOVERNANCE</div><h3>Clyde conversations and escalations</h3><div className="r28-table-wrap"><table><thead><tr><th>Intent</th><th>Decision</th><th>Owner / Status</th><th>Created</th></tr></thead><tbody>{aiState.conversations.slice(0, 12).map(item => <tr key={item.id}><td>{item.intent}</td><td><Status value={item.policy_decision} /></td><td>{aiState.escalations.find(x => x.client_id === item.client_id)?.recommended_owner || 'Clyde · TIER_0'}</td><td>{new Date(item.created_at).toLocaleString()}</td></tr>)}{!aiState.conversations.length && <tr><td colSpan="4">No live client AI conversations.</td></tr>}</tbody></table></div><small className="r28-help">Client AI is Supabase-first, tenant-scoped, cost-bounded, and cannot access Nexus internal tools.</small></section>
    <section className="r28-card"><div className="nx2-eyebrow">PER-CLIENT CONTROLS</div><h3>Persisted AI controls</h3>{aiState.controls.map(control => <div key={control.id} className="r28-policy-row"><span>{control.client_id} · {control.access_tier}</span><span><button className="nx2-outline-button" onClick={async () => { await updateClientAiControls({ tenant_id: control.tenant_id, client_id: control.client_id, clyde_enabled: !control.clyde_enabled }); await refresh() }}>{control.clyde_enabled ? 'Disable Clyde' : 'Enable Clyde'}</button><button className="nx2-outline-button" onClick={async () => { await updateClientAiControls({ tenant_id: control.tenant_id, client_id: control.client_id, customer_service_ai_enabled: !control.customer_service_ai_enabled }); await refresh() }}>{control.customer_service_ai_enabled ? 'Disable Service AI' : 'Enable Service AI'}</button></span></div>)}{!aiState.controls.length && <p>No persisted client control records yet; controls are created when an Admin selects a client through the governed control API.</p>}<small className="r28-help">Server-enforced controls include pause, access tier, limits, escalation-only, guest revoke, and paid-workflow transition.</small></section>
  </div>
}
