-- Research-to-Clyde v1. Additive only; existing research inbox/history remains canonical.
alter table public.credit_strategy_sources add column if not exists tenant_id text, add column if not exists source_url text, add column if not exists author_publisher text, add column if not exists transcript_hash text, add column if not exists duplicate_of uuid references public.credit_strategy_sources(id), add column if not exists reliability_score integer not null default 0 check (reliability_score between 0 and 100), add column if not exists promotional_risk_score integer not null default 0 check (promotional_risk_score between 0 and 100), add column if not exists authority_level text not null default 'practitioner', add column if not exists processing_state text not null default 'discovered' check (processing_state in ('discovered','ingested','extracted','classified','needs_evidence','needs_review','approved_for_strategy_development','rejected','archived')), add column if not exists sanitized_summary text, add column if not exists provenance_metadata jsonb not null default '{}'::jsonb, add column if not exists updated_at timestamptz not null default now();
alter table public.credit_strategy_claims add column if not exists source_location text, add column if not exists exact_excerpt text, add column if not exists claim_category text, add column if not exists claim_type text not null default 'educational_concept' check (claim_type in ('factual','procedural','legal_claim','practitioner_method','promotional_claim','outcome_claim','unsupported_claim','educational_concept')), add column if not exists supporting_authority jsonb not null default '[]'::jsonb, add column if not exists contradictory_authority jsonb not null default '[]'::jsonb, add column if not exists evidence_level text not null default 'unsupported' check (evidence_level in ('authoritative','strong','moderate','limited','anecdotal','unsupported','contradicted')), add column if not exists evidence_score integer not null default 0 check (evidence_score between 0 and 100), add column if not exists guarantee_language boolean not null default false, add column if not exists universal_claim boolean not null default false, add column if not exists legal_conclusion boolean not null default false, add column if not exists client_safe boolean not null default false, add column if not exists actionable boolean not null default false, add column if not exists review_required boolean not null default true, add column if not exists approval_state text not null default 'needs_review' check (approval_state in ('needs_review','approved_for_strategy_development','rejected','archived')), add column if not exists rejection_reason text, add column if not exists updated_at timestamptz not null default now();
alter table public.credit_strategy_definitions add column if not exists stable_key text, add column if not exists category text, add column if not exists educational_purpose text, add column if not exists eligibility_conditions jsonb not null default '[]'::jsonb, add column if not exists inapplicable_conditions jsonb not null default '[]'::jsonb, add column if not exists applicable_discrepancy_types jsonb not null default '[]'::jsonb, add column if not exists applicable_account_types jsonb not null default '[]'::jsonb, add column if not exists evidence_level text not null default 'limited', add column if not exists risk_level text not null default 'medium', add column if not exists required_disclaimers jsonb not null default '[]'::jsonb, add column if not exists possible_outputs jsonb not null default '[]'::jsonb, add column if not exists retired_at timestamptz, add column if not exists retirement_reason text;
update public.credit_strategy_definitions set stable_key=coalesce(stable_key,id), category=coalesce(category,id), educational_purpose=coalesce(educational_purpose,description), applicable_discrepancy_types=case when applicable_discrepancy_types='[]'::jsonb then applicable_categories else applicable_discrepancy_types end, possible_outputs=case when possible_outputs='[]'::jsonb then draft_tools else possible_outputs end where stable_key is null or category is null or educational_purpose is null;
create unique index if not exists credit_strategy_definitions_stable_key_idx on public.credit_strategy_definitions(stable_key);

create table if not exists public.credit_strategy_versions (
 id uuid primary key default gen_random_uuid(), strategy_id text not null references public.credit_strategy_definitions(id), version integer not null, title text not null, category text not null, educational_purpose text not null, plain_language_explanation text not null, eligibility_conditions jsonb not null default '[]', required_client_facts jsonb not null default '[]', required_evidence jsonb not null default '[]', applicable_discrepancy_types jsonb not null default '[]', applicable_account_types jsonb not null default '[]', inapplicable_conditions jsonb not null default '[]', evidence_level text not null check (evidence_level in ('authoritative','strong','moderate','limited','anecdotal')), risk_level text not null check (risk_level in ('low','medium','high')), limitations jsonb not null default '[]', required_disclaimers jsonb not null default '[]', prohibited_wording jsonb not null default '[]', possible_outputs jsonb not null default '[]', approval_state text not null check (approval_state in ('draft','evidence_review','needs_changes','approved','rejected','retired')), approved_by text, approved_at timestamptz, review_due_at timestamptz, retired_at timestamptz, retirement_reason text, created_at timestamptz not null default now(), unique(strategy_id,version)
);
create table if not exists public.credit_strategy_version_claims (strategy_version_id uuid not null references public.credit_strategy_versions(id), claim_id uuid not null references public.credit_strategy_claims(id), relationship text not null check (relationship in ('supports','contradicts','discovery')), primary key(strategy_version_id,claim_id));
create table if not exists public.credit_strategy_matches (
 id uuid primary key default gen_random_uuid(), tenant_id text not null, client_id text not null, report_id text not null, canonical_account_id text, discrepancy_id text, strategy_id text not null, strategy_version integer not null, match_score integer not null check(match_score between 0 and 100), match_reasons jsonb not null default '[]', exclusion_reasons jsonb not null default '[]', status text not null default 'matched' check(status in ('matched','presented','excluded','expired')), ruleset_version text not null, client_visible boolean not null default false, created_at timestamptz not null default now(), unique(discrepancy_id,strategy_id,strategy_version,ruleset_version)
);
create table if not exists public.credit_strategy_client_selections (
 id uuid primary key default gen_random_uuid(), tenant_id text not null, client_id text not null, report_id text not null, canonical_account_id text, discrepancy_id text, strategy_id text not null, strategy_version integer not null, match_id uuid references public.credit_strategy_matches(id), selected_option text, client_answers jsonb not null default '{}', evidence_references jsonb not null default '[]', status text not null default 'presented' check(status in ('presented','saved','selected','evidence_requested','evidence_received','draft_ready','awaiting_client_review','authorized','declined','withdrawn','completed','escalated')), consent_state text not null default 'not_requested', authorization_state text not null default 'not_authorized', revision integer not null default 1, actor text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), withdrawn_at timestamptz
);
create table if not exists public.credit_strategy_selection_history (id uuid primary key default gen_random_uuid(), selection_id uuid not null references public.credit_strategy_client_selections(id), tenant_id text not null, client_id text not null, revision integer not null, previous_state jsonb not null default '{}', new_state jsonb not null default '{}', actor_type text not null, actor_id text, reason text, created_at timestamptz not null default now(), unique(selection_id,revision));
create table if not exists public.credit_strategy_evidence_links (id uuid primary key default gen_random_uuid(), selection_id uuid not null references public.credit_strategy_client_selections(id), tenant_id text not null, client_id text not null, document_id text not null references public.client_documents(id), report_id text not null, discrepancy_id text, status text not null default 'uploaded' check(status in ('requested','uploaded','accepted','insufficient','rejected')), review_reason text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.credit_strategy_drafts (id uuid primary key default gen_random_uuid(), selection_id uuid not null references public.credit_strategy_client_selections(id), tenant_id text not null, client_id text not null, strategy_id text not null, strategy_version integer not null, template_version text not null, output_type text not null, content jsonb not null, status text not null default 'draft_ready' check(status in ('draft_ready','blocked','awaiting_client_review','authorized','withdrawn','completed')), safety_result jsonb not null default '{}', client_review_required boolean not null default true, client_authorized boolean not null default false, mail_created boolean not null default false check(mail_created=false), actor_type text not null, provenance jsonb not null default '{}', created_at timestamptz not null default now());
create table if not exists public.credit_strategy_exceptions (id uuid primary key default gen_random_uuid(), tenant_id text not null, client_id text, report_id text, discrepancy_id text, selection_id uuid references public.credit_strategy_client_selections(id), exception_code text not null, reason text not null, confidence text not null, risk text not null, recommended_action text not null, status text not null default 'required' check(status in ('required','in_review','resolved','rejected')), assigned_reviewer text, resolution_notes text, created_at timestamptz not null default now(), resolved_at timestamptz);
create table if not exists public.research_strategy_audit_events (id uuid primary key default gen_random_uuid(), tenant_id text, client_id text, report_id text, canonical_account_id text, discrepancy_id text, strategy_id text, strategy_version integer, event_type text not null, actor_type text not null, actor_id text, metadata jsonb not null default '{}', ruleset_version text, created_at timestamptz not null default now());

create index if not exists credit_strategy_matches_client_idx on public.credit_strategy_matches(tenant_id,client_id,created_at); create index if not exists credit_strategy_selections_client_idx on public.credit_strategy_client_selections(tenant_id,client_id,updated_at); create index if not exists credit_strategy_evidence_selection_idx on public.credit_strategy_evidence_links(selection_id); create index if not exists credit_strategy_exceptions_status_idx on public.credit_strategy_exceptions(status,created_at); create index if not exists research_strategy_audit_report_idx on public.research_strategy_audit_events(report_id,created_at);
alter table public.credit_strategy_versions enable row level security; alter table public.credit_strategy_version_claims enable row level security; alter table public.credit_strategy_matches enable row level security; alter table public.credit_strategy_client_selections enable row level security; alter table public.credit_strategy_selection_history enable row level security; alter table public.credit_strategy_evidence_links enable row level security; alter table public.credit_strategy_drafts enable row level security; alter table public.credit_strategy_exceptions enable row level security; alter table public.research_strategy_audit_events enable row level security;
create policy credit_strategy_versions_read on public.credit_strategy_versions for select to authenticated using (approval_state='approved' or public.nexus_is_active_admin()); create policy credit_strategy_versions_admin on public.credit_strategy_versions for all to authenticated using(public.nexus_is_active_admin()) with check(public.nexus_is_active_admin()); create policy credit_strategy_version_claims_admin on public.credit_strategy_version_claims for all to authenticated using(public.nexus_is_active_admin()) with check(public.nexus_is_active_admin());
create policy credit_strategy_matches_read on public.credit_strategy_matches for select to authenticated using(public.nexus_is_active_admin() or (client_visible and exists(select 1 from public.tenant_memberships tm where tm.user_id=auth.uid() and tm.tenant_id=credit_strategy_matches.tenant_id and tm.client_id=credit_strategy_matches.client_id))); create policy credit_strategy_matches_admin on public.credit_strategy_matches for all to authenticated using(public.nexus_is_active_admin()) with check(public.nexus_is_active_admin());
create policy credit_strategy_selections_read on public.credit_strategy_client_selections for select to authenticated using(public.nexus_is_active_admin() or exists(select 1 from public.tenant_memberships tm where tm.user_id=auth.uid() and tm.tenant_id=credit_strategy_client_selections.tenant_id and tm.client_id=credit_strategy_client_selections.client_id)); create policy credit_strategy_selections_client_insert on public.credit_strategy_client_selections for insert to authenticated with check(exists(select 1 from public.tenant_memberships tm where tm.user_id=auth.uid() and tm.tenant_id=credit_strategy_client_selections.tenant_id and tm.client_id=credit_strategy_client_selections.client_id) and actor='client');
create policy credit_strategy_history_read on public.credit_strategy_selection_history for select to authenticated using(public.nexus_is_active_admin() or exists(select 1 from public.tenant_memberships tm where tm.user_id=auth.uid() and tm.tenant_id=credit_strategy_selection_history.tenant_id and tm.client_id=credit_strategy_selection_history.client_id)); create policy credit_strategy_history_client_insert on public.credit_strategy_selection_history for insert to authenticated with check(exists(select 1 from public.tenant_memberships tm where tm.user_id=auth.uid() and tm.tenant_id=credit_strategy_selection_history.tenant_id and tm.client_id=credit_strategy_selection_history.client_id));
create policy credit_strategy_evidence_read on public.credit_strategy_evidence_links for select to authenticated using(public.nexus_is_active_admin() or exists(select 1 from public.tenant_memberships tm where tm.user_id=auth.uid() and tm.tenant_id=credit_strategy_evidence_links.tenant_id and tm.client_id=credit_strategy_evidence_links.client_id)); create policy credit_strategy_evidence_client_insert on public.credit_strategy_evidence_links for insert to authenticated with check(exists(select 1 from public.tenant_memberships tm where tm.user_id=auth.uid() and tm.tenant_id=credit_strategy_evidence_links.tenant_id and tm.client_id=credit_strategy_evidence_links.client_id));
create policy credit_strategy_drafts_read on public.credit_strategy_drafts for select to authenticated using(public.nexus_is_active_admin() or exists(select 1 from public.tenant_memberships tm where tm.user_id=auth.uid() and tm.tenant_id=credit_strategy_drafts.tenant_id and tm.client_id=credit_strategy_drafts.client_id)); create policy credit_strategy_drafts_admin on public.credit_strategy_drafts for all to authenticated using(public.nexus_is_active_admin()) with check(public.nexus_is_active_admin()); create policy credit_strategy_exceptions_admin on public.credit_strategy_exceptions for all to authenticated using(public.nexus_is_active_admin()) with check(public.nexus_is_active_admin()); create policy research_strategy_audit_admin on public.research_strategy_audit_events for all to authenticated using(public.nexus_is_active_admin()) with check(public.nexus_is_active_admin());
grant select,insert on public.credit_strategy_client_selections,public.credit_strategy_selection_history,public.credit_strategy_evidence_links to authenticated; grant select on public.credit_strategy_versions,public.credit_strategy_matches,public.credit_strategy_drafts to authenticated; grant all on public.credit_strategy_versions,public.credit_strategy_version_claims,public.credit_strategy_matches,public.credit_strategy_client_selections,public.credit_strategy_selection_history,public.credit_strategy_evidence_links,public.credit_strategy_drafts,public.credit_strategy_exceptions,public.research_strategy_audit_events to service_role;

-- Ray's explicit sprint directive approves these reusable educational v1 frameworks.
insert into public.credit_strategy_versions(strategy_id,version,title,category,educational_purpose,plain_language_explanation,eligibility_conditions,required_client_facts,required_evidence,applicable_discrepancy_types,applicable_account_types,inapplicable_conditions,evidence_level,risk_level,limitations,required_disclaimers,prohibited_wording,possible_outputs,approval_state,approved_by,approved_at,review_due_at)
select d.id,1,d.name,d.id,'Explain objective structured report differences and organize safe client next steps.',d.client_education_copy,d.required_report_facts,d.optional_client_confirmations,d.required_evidence,d.applicable_categories,'[]'::jsonb,jsonb_build_array('Ambiguous account match','Unsupported client assertion'),'moderate','medium',jsonb_build_array(d.limitations),jsonb_build_array('Nexus provides education and organization tools; outcomes are not guaranteed.'),jsonb_build_array('guaranteed deletion','guaranteed removal','must delete','automatic damages','original signed contract always required'),d.draft_tools,'approved','ray_sprint_directive',now(),now()+interval '1 year'
from public.credit_strategy_definitions d where d.id in ('cross_bureau_balance_review','purchased_debt_documentation','original_creditor_request','cross_bureau_status_review','cross_bureau_date_review','duplicate_account_review')
on conflict(strategy_id,version) do nothing;
