import type { V2ViewData } from '../types/v2-models'
import { buildBusinessPlanContext, evidence, type CustomerGoal, type UseOfFundsItem } from '../../lib/customerGoalsModel'
export function resolveCustomerGoals(data: V2ViewData) {
  const now = new Date().toISOString(); const clientId = data.resolvedClientId || 'current-client'; const goalId = `goal-${clientId}-business-readiness`; const missing = data.readiness.outstandingRequirements || []
  const goal: CustomerGoal = { goalId, customerOrClientId: clientId, goalType: 'BUSINESS_READINESS', title: 'Build a fundable business foundation', description: 'Track verified steps and evidence for the next reviewed funding stage.', targetOutcome: 'Business and funding readiness review', priority: 1, currentStatus: missing.length ? 'IN_PROGRESS' : 'READY_FOR_REVIEW', currentProgress: data.readiness.overallScore || null, milestones: missing.slice(0, 5).map((item, i) => ({ milestoneId: `${goalId}-milestone-${i + 1}`, title: item, status: 'IN_PROGRESS', completionState: 'OPEN', evidence: evidence('Supabase client readiness context', 'UNVERIFIED'), dependencies: [], nextAction: `Resolve or provide evidence for ${item}.` })), dependencies: [], blockers: missing, evidenceRequirements: missing, relatedFundingObjective: 'funding-readiness-review', relatedBusinessPlan: goalId, evidence: evidence('Supabase client readiness context', missing.length ? 'PARTIAL' : 'SUPPORTED', data.resolvedClientId || undefined), createdAt: now, updatedAt: now }
  const useOfFunds: UseOfFundsItem[] = [{ useOfFundsId: `${goalId}-use-of-funds`, category: 'BUSINESS_READINESS_PREPARATION', description: 'Readiness preparation linked to the customer goal.', businessPurpose: 'Prepare for a governed funding review', relatedGoal: goalId, supportingEvidence: evidence('No use-of-funds document supplied', 'MISSING'), evidenceStatus: 'MISSING', confidence: 'NONE', knownGaps: ['Supporting use-of-funds evidence'] }]
  return { goals: [goal], useOfFunds, source: data.mode === 'live' ? 'Supabase client readiness context' : 'Design-neutral demo adapter', realBackendConnected: data.mode === 'live' }
}
export function customerGoalBusinessPlanContext(data: V2ViewData) { const resolved = resolveCustomerGoals(data); return buildBusinessPlanContext(resolved.goals[0], resolved.useOfFunds) }
